[translation]
10129-BirthdayJp = "August 31st"
10129-CharacterAgeJp = "16 years old"
10129-CharacterSSRNewJp = "S-Sensei...! \nT-this outfit... well... it's not what you think!"
10129-FamilyNameJp = "Morizuki"
10129-FullNameJp = "Suzumi Morizuki"
10129-HobbyJp = "Patrolling, Strolling"
10129-PersonalNameJp = "Suzumi"
10129-ProfileIntroductionJp = "A student of Trinity General School who ended up wearing a magical girl costume to carry out an infiltration mission for the Vigilante Crew.\n\nShe is unfamiliar with the magical girl genre and doesn't quite understand the costume. While she is not good at standing out in public, she has resolved to face this adversity with her natural sincerity."
10129-SchoolYearJp = "2nd Year"
10129-StatusMessageJp = "I hope today will be a peaceful day..."
10129-WeaponDescJp = "The assault rifle held by Suzumi.\n\nIt has been decorated cutely for the sake of the infiltration mission. It is a precious partner to Suzumi."
10129-WeaponNameJp = "Safety"