[translation]
10130-BirthdayJp = "March 9th"
10130-CharacterAgeJp = "17 years old"
10130-CharacterSSRNewJp = "Welcome to Arius."
10130-FamilyNameJp = "Kakehashi"
10130-FullNameJp = "Subaru Kakehashi"
10130-HobbyJp = "Playing harmonica"
10130-PersonalNameJp = "Subaru"
10130-ProfileIntroductionJp = "A student of the Arius Branch School who guides the remaining students in Arius.\n\nShe is gentle, kind to everyone, and very approachable. She is deeply trusted by her juniors. For their sake, she is prepared to pull the trigger without hesitation at any moment."
10130-SchoolYearJp = "3rd Year"
10130-StatusMessageJp = "Every day, one step at a time."
10130-WeaponDescJp = "The battle rifle used by Subaru.\n\n She customized this gun herself with functionality in mind. At first glance, there may not seem to be much difference, but her meticulous attention to detail can be seen throughout."
10130-WeaponNameJp = "Anomoios"