[translation]
101350001-BirthdayJp = "March 25th"
101350001-CharacterAgeJp = "??"
101350001-CharacterSSRNewJp = "Wh-What is it...? \nIf you have something to say, just say it!"
101350001-FamilyNameJp = "Tendou"
101350001-FullNameJp = "Tendou Kei"
101350001-HobbyJp = "Taking care of Arisu, fashion, games (she denies it)"
101350001-PersonalNameJp = "Kei"
101350001-ProfileIntroductionJp = "Kei defined herself as herself. \n\nFrom AI to AMAS, from defected sacrificial ritual to this very body. She arrived here through twists and turns. \n\nMillennium Science School allows students to join multiple clubs, so while she belongs to the Super Phenomenon Task Force, she also spends most of her time in the Game Development Department. \n\nShe's effectively the new producer for the Game Development Department... though she seems to deny it."
101350001-SchoolYearJp = "1st Year"
101350001-StatusMessageJp = "I'm Kei. Nice to meet you."
101350001-WeaponDescJp = "A railgun exclusively for Kei.\n\nIt's a perfect item for her as she takes a new step forward."
101350001-WeaponNameJp = "Luminousãƒ»Nova"