[translation]
10133-BirthdayJp = "June 6th"
10133-CharacterAgeJp = "17 years old"
10133-CharacterSSRNewJp = "Leave the electronic warfare to me.\nI shall show you the most rational solution."
10133-FamilyNameJp = "Tsukatsuki"
10133-FullNameJp = "Rio Tsukatsuki"
10133-HobbyJp = "Designing"
10133-PersonalNameJp = "Rio"
10133-ProfileIntroductionJp = "The President of the Student Council 'Seminar' at Millennium Science School.\n\nShe has donned a specialized suit in order to respond to unprecedented crises. The suit is a pursuit of pure rationality, capable of handling everything from rear-guard support to front-line response."
10133-SchoolYearJp = "3rd Year"
10133-StatusMessageJp = "Tasklist /S"
10133-WeaponDescJp = "Rio's self-defense handgun.\n\nIt appears that the support capabilities of her specialized suit have enabled even more precise marksmanship."
10133-WeaponNameJp = "Planner"