[translation]
10135-BirthdayJp = "March 25th"
10135-CharacterAgeJp = "??"
10135-CharacterSSRNewJp = "Wh-What is it...? \nIf you have something to say, just say it!"
10135-FullNameJp = "Kei"
10135-HobbyJp = "Taking care of Arisu, fashion, games (she denies it)"
10135-PersonalNameJp = "Kei"
10135-ProfileIntroductionJp = "Kei has a new body. \n\nShe doesn't realize it, but she is a little more excited than usual."
10135-SchoolYearJp = "1st Year"
10135-StatusMessageJp = "I'm Kei. Nice to meet you."
10135-WeaponDescJp = "A railgun exclusively for Kei.\n\nIt's a perfect item for her as she takes a new step forward."
10135-WeaponNameJp = "Luminousãƒ»Nova"
