[translation]
101350001-BirthdayJp = "March 25th"
101350001-CharacterAgeJp = "??"
101350001-CharacterSSRNewJp = "Wh-What is it...? \nIf there's something, please tell me!"
101350001-FamilyNameJp = "Tendou"
101350001-FullNameJp = "Tendou Kei"
101350001-HobbyJp = "Taking care of Arisu, fashion, games (she denies it)"
101350001-PersonalNameJp = "Kei"
101350001-ProfileIntroductionJp = "Kei defined himself as himself. \n\nFrom AI to AMAS, from a defective sacrifice to his current body. He has come a long way through many twists and turns to get here. \n\nMillennium Science School is a school where students can join multiple clubs, so although he belongs to the Super Phenomenon Task Force, he is often in the Game Development Department. \n\nHe is effectively the new producer of the Game Development Department... but he seems to deny it."
101350001-SchoolYearJp = "1st Year"
101350001-StatusMessageJp = "I'm Kei. Nice to meet you."
101350001-WeaponDescJp = "A railgun exclusively for Kei.\n\nIt's a perfect item for her as she takes a new step forward."
101350001-WeaponNameJp = "Luminous Nova"
