[translation]
10131-BirthdayJp = "June 18th"
10131-CharacterAgeJp = "16 years old"
10131-CharacterSSRNewJp = "Good day to you.\nI have a work I'd like to recommend; would you care to read it?"
10131-FamilyNameJp = "Miyoshi"
10131-FullNameJp = "Takane Miyoshi"
10131-HobbyJp = "Reading, Photography, Watching ice hockey"
10131-PersonalNameJp = "Takane"
10131-ProfileIntroductionJp = "A member of the Publishing Club at Red Winter Federal Academy.\n\nA refined and elegant young lady who places great importance on etiquette. While her skills as a critic are genuine, her opinions are often so subjective that they frequently lead to trouble. She appears to have a rivalry with the 'Knowledge Liberation Front.'"
10131-SchoolYearJp = "2nd Year"
10131-StatusMessageJp = "★★★★☆"
10131-WeaponDescJp = "A handgun decorated by Takane.\n\nIt is said that it's not only used for combat, but also occasionally as a means for Takane to express her anger..."
10131-WeaponNameJp = "Shvibzik"