[translation]
10132-BirthdayJp = "April 5th"
10132-CharacterAgeJp = "15 years old"
10132-CharacterSSRNewJp = "A-Am I really going to be a... model...?"
10132-FamilyNameJp = "Ono"
10132-FullNameJp = "Tsukuyo Ono"
10132-HobbyJp = "Substitute Technique, Staying Breathless"
10132-PersonalNameJp = "Tsukuyo"
10132-ProfileIntroductionJp = "A member of the Ninjutsu Research Club at Hyakkiyako Alliance Academy.\n\nOriginally hired as a security guard for a fashion show, she ended up making her debut as a model. Her height, which used to be an insecurity, became a major strength in the modeling world. She appears to be struggling with how to balance her modeling work and club activities."
10132-SchoolYearJp = "1st Year"
10132-StatusMessageJp = "Currently training to become a grand ninja...!"
10132-WeaponDescJp = "The submachine gun that Tsukuyo treasures.\n\nShe hasn't added any special decorations to it, even when taking it onto the stage. This is likely because the way Michiru and Izuna decorated it for her in the past remains its perfect state in Tsukuyo's eyes."
10132-WeaponNameJp = "Tsukuyo-Style Submachine Gun"