[translation]
10136-BirthdayJp = "May 1st"
10136-CharacterAgeJp = "15 years old"
10136-CharacterSSRNewJp = "Eimi Izumimoto, reporting from the field."
10136-FamilyNameJp = "Izumimoto"
10136-FullNameJp = "Eimi Izumimoto"
10136-HobbyJp = "Spacing out, listening to music"
10136-PersonalNameJp = "Eimi"
10136-ProfileIntroductionJp = "A specialist of the Special Phenomenon Task Force at Millennium Science School.\n\nShe has changed her attire to provide rear-guard support as a marksman. Although she initially thought minimizing skin exposure would be more suitable for support... she seemingly couldn't withstand the heat and has taken off her cape to wrap it around her waist.\n\nLike Toki, she has switched her primary weapon to an energy rifle. Because she is equipped with a visor for sniping support, it's said that her backpack is significantly larger than Toki's."
10136-SchoolYearJp = "1st Year"
10136-StatusMessageJp = "Currently responding."
10136-WeaponDescJp = "Eimi's newly constructed energy rifle.\n\nA specialist's weapon prepared specifically for rear-guard support."
10136-WeaponNameJp = "Multi-Support"