[translation]
10134-BirthdayJp = "March 25th"
10134-CharacterAgeJp = "??"
10134-CharacterSSRNewJp = "Aris wants to see more of the world!"
10134-FamilyNameJp = "Tendou"
10134-FullNameJp = "Tendou Aris"
10134-HobbyJp = "Video games (RPGs)"
10134-PersonalNameJp = "Aris"
10134-ProfileIntroductionJp = "A member of the Game Development Department at Millennium Science School.\n\nA girl who loves games and is a bit eccentric. Now, she carries the fate of the world on her shoulders."
10134-SchoolYearJp = "1st Year"
10134-StatusMessageJp = "Hello! This is Aris!"
10134-WeaponDescJp = "An assault rifle customized from a lightened railgun to allow for continuous fire.\n\nBy taking up the legendary sword, the girl became a Hero. Yes, this is where Aris's adventure truly began."
10134-WeaponNameJp = "Sword of Light: Supernova for Abi-Eshuh"