[translation]
16019-BirthdayJp = "August 16th"
16019-CharacterAgeJp = "16 years old"
16019-FamilyNameJp = "Asuma"
16019-FullNameJp = "Toki Asuma"
16019-HobbyJp = "Watching streams (tentative), Games (tentative), Manga (tentative)"
16019-PersonalNameJp = "Toki"
16019-ProfileIntroductionJp = "An agent of C&C and field operative for the Special Phenomenon Task Force at Millennium Science School.\n\nThis is her attire for reconnaissance missions. According to her, she is now the 'New Toki Asuma, specialized in mobility.' Additionally, it seems she has—at least tentatively—managed to find some hobbies."
16019-SchoolYearJp = "1st Year"
16019-StatusMessageJp = "Ready for mission execution."
16019-WeaponDescJp = "An energy pistol designed specifically for Toki.\n\nShe claims that the concept and atmosphere have been completely refreshed. This, too, is likely an essential item for the 'New Toki Asuma.'"
16019-WeaponNameJp = "Search & Recon"