[translation]
16018-BirthdayJp = "May 6th"
16018-CharacterAgeJp = "16 years old"
16018-FamilyNameJp = "Kakomaze"
16018-FullNameJp = "Rabu Kakomaze"
16018-HobbyJp = "Polishing helmets, scrounging under vending machines"
16018-PersonalNameJp = "Rabu"
16018-ProfileIntroductionJp = "The leader of the Splash Helmet Gang.\n\nShe is a reliable, big-sister type who is deeply trusted by her subordinates. However, it seems her luck isn't particularly good."
16018-SchoolYearJp = "Dropout"
16018-StatusMessageJp = "The Splash Helmet Gang is recruiting members!"
16018-WeaponDescJp = "Rabu's shotgun.\n\nThough it is often used like a baseball bat, it is meticulously maintained."
16018-WeaponNameJp = "Pinch Hitter"