[translation]
20054-BirthdayJp = "December 10th"
20054-CharacterAgeJp = "17 years old"
20054-CharacterSSRNewJp = "The actions of a super-genius, elegant, sickly, and beautiful girl remain unchanged. \nShall we handle things one by one, with grace and composure?"
20054-FamilyNameJp = "Akeboshi"
20054-FullNameJp = "Himari Akeboshi"
20054-HobbyJp = "Checking daily fortunes, all things occult"
20054-PersonalNameJp = "Himari"
20054-ProfileIntroductionJp = "The former head of the hacker group 'Veritas' and current head of the Special Phenomenon Task Force at Millennium Science School.\n\nShe has donned a specialized suit to respond to unprecedented crises. Furthermore, thanks to her new 'wheelchair,' it seems she is now capable of racing around freely in every direction.\n\nWhile she insists it is a wheelchair, to any observer, it is clearly a motorcycle."
20054-SchoolYearJp = "3rd Year"
20054-StatusMessageJp = "Look forward to the brilliant performance of\nthis super-genius, elegant, and beautiful girl."
20054-WeaponDescJp = "The handgun in Himari's possession.\n\nNow that she has begun riding her wheelchair—or rather, her motorcycle—we may see her using her gun more often than usual."
20054-WeaponNameJp = "Clifftop Flower"