[translation]
20053-BirthdayJp = "February 22nd"
20053-CharacterAgeJp = "17 years old"
20053-CharacterSSRNewJp = "Infiltration missions are a ninja's time to shine! \nClad in this dress, I make my entrance!"
20053-FamilyNameJp = "Chidori"
20053-FullNameJp = "Michiru Chidori"
20053-HobbyJp = "Devising new ninjutsu, making videos"
20053-PersonalNameJp = "Michiru"
20053-ProfileIntroductionJp = "The President of the Ninjutsu Research Club at Hyakkiyako Alliance Academy.\n\nShe ended up wearing a dress after being hired as an undercover security guard for a fashion show. While facing many first-time experiences, she appears to be contemplating how a true ninja should carry themselves in such a situation."
20053-SchoolYearJp = "3rd Year"
20053-StatusMessageJp = "I've uploaded the dress special of 'Michiru-chi's Girl Ninja Chronicles!'"
20053-WeaponDescJp = "The shotgun Michiru loves to use.\n\nThis time, it seems to have become a bit more elegant, much like its owner."
20053-WeaponNameJp = "Michiru-Style Overflow Shotgun"