[translation]
20052-BirthdayJp = "May 18th"
20052-CharacterAgeJp = "17 years old"
20052-CharacterSSRNewJp = "Are you... interested in books? \nNow, now, don't say that; at least let's start with a chat."
20052-FamilyNameJp = "Aramaki"
20052-FullNameJp = "Yakumo Aramaki"
20052-HobbyJp = "Creating business proposals, analyzing railway lines"
20052-PersonalNameJp = "Yakumo"
20052-ProfileIntroductionJp = "The President of the Publishing Club at Red Winter Federal Academy.\n\nShe also serves as the Editor-in-Chief of 'Red Bear.' She has a stubborn streak and won't budge once she's made up her mind; for the sake of the Publishing Club's profits, she will use any means necessary and display invincible initiative. However, even she seems to have a more devoted, single-minded side...?"
20052-SchoolYearJp = "3rd Year"
20052-StatusMessageJp = "Publishing, Reprinting, Distribution"
20052-WeaponDescJp = "The handgun Yakumo always keeps on hand.\n\nShe often says that 'guns have many uses.' It's said that one of those uses is 'making lazy writers meet their deadlines.'"
20052-WeaponNameJp = "Pravda"