[translation]
20055-BirthdayJp = "August 12th"
20055-CharacterAgeJp = "16 years old"
20055-CharacterSSRNewJp = "I... I mustn't run away...!"
20055-FamilyNameJp = "Hanaoka"
20055-FullNameJp = "Yuzu Hanaoka"
20055-HobbyJp = "Making video games"
20055-PersonalNameJp = "Yuzu"
20055-ProfileIntroductionJp = "The President of the Game Development Department at Millennium Science School.\n\nShe has donned a specialized suit to prepare for unprecedented circumstances. It is said that the suit's specifications were decided based on Rio's strong demands. As for Yuzu herself, she seems so embarrassed that she wants to crawl into a hole and stay there."
20055-SchoolYearJp = "1st Year"
20055-StatusMessageJp = "500 Internal Server Error"
20055-WeaponDescJp = "The grenade launcher that Yuzu always carries with her.\n\nEven though many things have changed, this is the one thing that remains exactly the same."
20055-WeaponNameJp = "Nyan's Dash"