[translation]
20051-BirthdayJp = "May 31st"
20051-CharacterAgeJp = "15 years old"
20051-CharacterSSRNewJp = "The Magical Vigilante has arrived!"
20051-FamilyNameJp = "Uzawa"
20051-FullNameJp = "Reisa Uzawa"
20051-HobbyJp = "Challenging others to duels, self-introductions"
20051-PersonalNameJp = "Reisa"
20051-ProfileIntroductionJp = "A student of Trinity General School who ended up wearing a magical girl costume to carry out an infiltration mission for the Vigilante Crew.\n\nPerhaps because she has loved magical girl media since she was a young child, she appears to be in incredibly high spirits."
20051-SchoolYearJp = "1st Year"
20051-StatusMessageJp = "\"The ♡ of the Magical Girl\""
20051-WeaponDescJp = "Reisa's precious shotgun.\n\nShe insists that because it has sound, light, and firepower, it is indeed a magical wand."
20051-WeaponNameJp = "Shooting☆Star"