[translation]
20050-BirthdayJp = "March 6th"
20050-CharacterAgeJp = "15 years old"
20050-CharacterSSRNewJp = "I've come to play!"
20050-FamilyNameJp = "Usuba"
20050-FullNameJp = "Ritsu Usuba"
20050-HobbyJp = "Smuggling, Quarrying"
20050-PersonalNameJp = "Ritsu"
20050-ProfileIntroductionJp = "The operations manager of the unofficial 'Free Trade Club' at Wild Hunt Academy of the Arts.\n\nShe is the student who founded the current Special Trade Club, and she handles the club's heavy lifting by utilizing her superhuman strength. Because she is optimistic and pure-hearted, she genuinely enjoys the club activities themselves."
20050-SchoolYearJp = "1st Year"
20050-StatusMessageJp = "Where is the striped marble?!"
20050-WeaponDescJp = "The submachine gun that Ritsu always carries with her.\n\nIt's said that she often uses it to pull the trigger against stone materials to drill holes."
20050-WeaponNameJp = "Portable Boring Machine"