[translation]
1803503960 = "This user does not allow layout copying."
1145119466 = "You cannot purchase this because the same item is already in your mailbox. Please try again after claiming it."
2938963751 = "This item has already been purchased."
3696114145 = "Daily report information not found."
1552023844 = "The daily report has ended."
3447961601 = "There are no daily report rewards to claim."
3146430479 = "Abnormal logs have been detected; access to content will be restricted for {0} days. Restriction period: {1} to {2}"