[translation]
2552765017-NameJP = "Kanoe"
2552765017-NicknameJP = "Occult Research Society"
952072385-NameJP = "Yakumo & Takane"
952072385-NicknameJP = "Publishing Department"
1568486361-NameJP = "Izuna"
1568486361-NicknameJP = "Ninjutsu Research Club"
2236098080-NameJP = "Izuna"
2236098080-NicknameJP = "Ninjutsu Research Club"
4056509762-NameJP = "Michiru"
4056509762-NicknameJP = "Ninjutsu Research Club"
3091219447-NameJP = "Michiru"
3091219447-NicknameJP = "Ninjutsu Research Club"
2783063589-NameJP = "Tsukuyo"
2783063589-NicknameJP = "Ninjutsu Research Club"
3718160358-NameJP = "Tsukuyo"
1339731053-NameJP = "Tsukuyo"
1339731053-NicknameJP = "Shine Cat Agency"
1216244885-NameJP = "Michiru & Izuna"
1216244885-NicknameJP = "Ninjutsu Research Club"
234734809-NameJP = "Izuna & Tsukuyo"
234734809-NicknameJP = "Ninjutsu Research Club"
2272647969-NameJP = "Rio"
2272647969-NicknameJP = "Seminar"
74548664-NameJP = "Rio"
74548664-NicknameJP = "Seminar"
1423982009-NameJP = "Toki"
1423982009-NicknameJP = "C&C"
3614138862-NameJP = "Toki"
3614138862-NicknameJP = "C&C"
2714160656-NameJP = "Aris"
2714160656-NicknameJP = "Game Development Department"
1875765686-NameJP = "Aris"
1875765686-NicknameJP = "Game Development Department"
2286957398-NameJP = "Yuzu"
2286957398-NicknameJP = "Game Development Department"
2716558319-NameJP = "Yuzu"
2716558319-NicknameJP = "Game Development Department"
1451921119-NameJP = "Eimi"
1451921119-NicknameJP = "Super Phenomenon Task Force"
999629596-NameJP = "Eimi"
999629596-NicknameJP = "Super Phenomenon Task Force"
520975289-NameJP = "Himari"
520975289-NicknameJP = "Super Phenomenon Task Force"
173973871-NameJP = "Kei"
1647715460-NameJP = "Kei"
1647715460-NicknameJP = "Super Phenomenon Task Force"
830237550-NameJP = "Kei"
2064008127-NameJP = "Kei"
2064008127-NicknameJP = "Super Phenomenon Task Force"
271391397-NameJP = "Aris & Kei"
3050021557-NameJP = "Momoi"
3050021557-NicknameJP = "Game Development Department"
588403976-NameJP = "Momoi"
588403976-NicknameJP = "Game Development Department"
3621431876-NameJP = "Midori"
3621431876-NicknameJP = "Game Development Department"
3179475860-NameJP = "Midori"
3179475860-NicknameJP = "Game Development Department"
3721379331-NameJP = "Kei"
3700647472-NameJP = "Himari"
3700647472-NicknameJP = "Super Phenomenon Task Force"
510608759-NameJP = "Himari"
510608759-NicknameJP = "Super Phenomenon Task Force"
1162219369-NameJP = "Himari"
1162219369-NicknameJP = "Super Phenomenon Task Force"
3287782288-NameJP = "Aris"
3287782288-NicknameJP = "Game Development Department"
4138490498-NameJP = "Malkuth"
48056105-NameJP = "Decagrammaton"
1806943221-NameJP = "Ein"
854279058-NameJP = "Sof"
3946031200-NameJP = "Ohr"
542354905-NameJP = "Decagrammaton"
543508239-NameJP = "Timid Voice"
1820392486-NameJP = "Calm Voice"
2103316679-NameJP = "Energetic Voice"
1319864298-NameJP = "Ein"
2879153603-NameJP = "Sof"
3975097123-NameJP = "Ohr"
4152021873-NicknameJP = "Black Tortoise Promenade"
4262917580-NameJP = "Trinity Student A"
1268023238-NameJP = "Trinity Student B"
255403252-NameJP = "Trinity Student C"
1075528254-NameJP = "Trinity Student D"
3531421350-NameJP = "Student Visiting Secretly"
834761151-NameJP = "Assertive Student"
75094637-NameJP = "Justice Task Force Members A & B"
75094637-NicknameJP = "Justice Task Force"
3315771075-NameJP = "Tea Party Administrative Official"
3315771075-NicknameJP = "Tea Party"
4262440800-NameJP = "Angry Spectator"
77123755-NameJP = "Office Announcement"
405691509-NameJP = "Computational Science Club President"
1559217225-NameJP = "SEN9000"
3617955346-NameJP = "RFC9001"
1237736635-NameJP = "Spectator A"
1249383929-NameJP = "Spectator B"
2853596581-NameJP = "Imperial Guard Member"
1803045768-NameJP = "Repair Shop Owner"
1915808128-NameJP = "Suspicious Host"
2889318663-NameJP = "Suspicious Staff"
1502579790-NameJP = "Staff"
1100690660-NameJP = "Show Organizer"
4016371047-NameJP = "Instructor"
4209303481-NameJP = "Cram School Student A"
911640099-NameJP = "Cram School Student B"
3718627969-NameJP = "Cram School Student C"
3723494323-NameJP = "Cram School Student D"
2670890413-NameJP = "Girl A"
3995044760-NameJP = "Girl B"
4167289789-NameJP = "Trinity Student B"
2485195942-NameJP = "Millennium Student B"
2808619144-NameJP = "Shine Cat"
3922698421-NameJP = "Staff"
1038489227-NameJP = "Manager"
1038489227-NicknameJP = "Shine Cat Agency"
4103239362-NameJP = "Shop Manager"
3572457962-NameJP = "Ramen Lovers Club Member A"
4281966476-NameJP = "Ramen Lovers Club Member B"
2766602551-NameJP = "Helmet Gang Executive"
2766602551-NicknameJP = "Helmet Gang"
37543489-NameJP = "Helmet Gang"
37543489-NicknameJP = "Helmet Gang"
652069197-NameJP = "Unknown Student"
1026912369-NameJP = "Fallen Model"
4222435212-NameJP = "Chimengumi A"
2872911327-NameJP = "Chimengumi B"
1563436442-NameJP = "Kimono Shop Owner"
3199008718-NameJP = "Rescue Worker"
2098162414-NameJP = "Radio"
2510180498-NameJP = "Millennium Security System"
1740254648-NameJP = "Photo Studio Owner"
3871158668-NameJP = "Staff Member"
864566838-NameJP = "Material Development Club Member Member A"
864566838-NicknameJP = "Material Development Club Member"
3503339198-NameJP = "Material Development Club Member Member B"
3503339198-NicknameJP = "Material Development Club Member"
3145778661-NameJP = "Pseudoscience Club Member"
3145778661-NicknameJP = "Pseudoscience Club"
1538867974-NameJP = "Laborer"
3081901788-NameJP = "Social Studies Instructor"
2900052986-NameJP = "Math Instructor"
263915734-NameJP = "Millennium Student C"
1965217876-NameJP = "Sof & Ohr"
2591057778-NameJP = "Millennium Students A & B"
2160871802-NameJP = "Excited Spectator"
265913969-NameJP = "Research-loving Spectator"
2787578992-NameJP = "Game Maniac Spectator"
174228875-NameJP = "Thrilled Spectator"
164561377-NameJP = "Sci-Fi Enthusiast Spectator"
409601636-NameJP = "Tournament Host"
2014783175-NameJP = "Spectator A"
3747013299-NameJP = "Spectator B"
2764576644-NameJP = "Spectator C"
8489425-NameJP = "Opponent A"
4047789016-NameJP = "Opponent B"
3187236889-NameJP = "Millennium Student A"
629383206-NameJP = "Millennium Student B"
3441854897-NameJP = "Voice"
3374254957-NameJP = "Nameless Priests"