[translation]
10052150-0001 = "Da'ath: The Wisdom of the Abyss Hidden in Shadows"
10052150-0003 = "What are those kids doing?"
10052150-0004 = "That's... no way!?"
10052150-0014 = "Whoa."
10052150-0015 = "Eek!?!?"
10052150-0016 = "Yuzu-chan, are you okay!? And what are you doing, big sis!?"
10052150-0017 = "Midori... I might have misunderstood you until now...!"
10052150-0018 = "What are you talking about!?"
10052150-0019 = "I thought a space battleship would be a good idea... but as a scenario writer, I should have foreseen beyond all possibilities, to what lies beyond...!"
10052150-0020 = "Giant Transformation Combined Dinosaur Robot! That's the way!"
10052150-0021 = "Is this really the time for that!?"
10052150-0022 = "There's only one thing I know for sure."
10052150-0023 = "If Neru-senpai were here... she would surely say this."
10052150-0024 = "—'It's the coolest.'"
10052150-0025 = "[s1] \"That's not a Giant Transformation Combined Dinosaur Robot, Momoi!\"\n[s2] \"It's a Giant Transformation Combined 'Kaiju' Robot!\""
10052150-0028 = "..."
10052150-0029 = "Do we really need to talk about that now!?"
10052150-0036 = "Taxonomy is certainly an important field of study... but isn't it too big even for that? And it's heading this way!"
10052150-0041 = "..."
10052150-0042 = "Everyone, don't worry."
10052150-0046 = "Rio? You don't mean..."
10052150-0047 = "That's right. Just in case, I've prepared something."
10052150-0051 = "Neo Avant-Garde-kun—"
10052150-0052 = "—Launch."
10052150-0062 = "This is...!"
10052150-0063 = "Neo Avant-Garde-kun...?"
10052150-0070 = "..."
10052150-0071 = "..."
10052150-0072 = "Pfft! Ahahaha! What is that! How weird!"
10052150-0073 = "Isn't it too small? It won't be any match for Da'ath, will it?"
10052150-0075 = "It's... cute! Hehehe..."
10052150-0076 = "In many cases, size is an issue."
10052150-0077 = "But not now."
10052150-0081 = "Yes...?"
10052150-0082 = "Kei, are you ready?"
10052150-0083 = "...Well, since I promised. Fine. Let's start right away."
10052150-0084 = "Ah, one more thing before we begin. Ain, Sof, Owl. I want to thank you."
10052150-0085 = "Huh!?"
10052150-0086 = "What do you mean...?"
10052150-0087 = "It's a bluff anyway! Da'ath is the strongest right now! Invincible! So! You have no chance of winning!"
10052150-0088 = "Under the current circumstances, that's probably true."
10052150-0089 = "But all the countermeasures are in place."
10052150-0090 = "In this steel continent, created by the power of nameless gods...!"
10052150-0091 = "I can see signs of minor tampering, but I've gotten used to fixing them."
10052150-0092 = "The power of nameless gods..."
10052150-0093 = "Just because there's a 'Princess' and a 'Key'..."
10052150-0094 = "..."
10052150-0095 = "N-no way...!!!"
10052150-0096 = "It's simple. What happened once will happen again. And the second time will proceed more easily than the first."
10052150-0097 = "There was a day when 'Colors' descended upon Kivotos."
10052150-0098 = "We countered that power and adapted a part of it."
10052150-0099 = "We can't afford to be picky. We had to use everything we could to survive."
10052150-0100 = "Conflict isn't your exclusive right. Any living creature is the same."
10052150-0101 = "The steel continent was created using the power of nameless gods."
10052150-0102 = "And the eight prophets standing on that land were, before they knew it, influenced by that power."
10052150-0103 = "After fighting against all of that, this place became filled with the power of nameless gods."
10052150-0104 = "Furthermore, Kei, who has absorbed the prophets' cores, is here now."
10052150-0105 = "If energy exists, can be analyzed, and consequently reproduced—"
10052150-0106 = "Naturally, it means that energy can be processed and applied as one wishes."
10052150-0110 = "You mean...!"
10052150-0111 = "What are you flustered about? That power rightfully belongs to me and Alice."
10052150-0112 = "I won't accept any complaints, so please understand."
10052150-0114 = "Then, that Neo-whatever...!"
10052150-0115 = "Yes. We will 'enlarge matter' again."
10052150-0129 = "Awesome!!"
10052150-0130 = "Yeah... Amazing!"
10052150-0131 = "(But... couldn't they have done something about the design...)"
10052150-0132 = "...Is this your 'trump card'?"
10052150-0133 = "I'm sorry. I thought we were in enemy territory and speaking carelessly might lead to us being overheard."
10052150-0134 = "That's why I only told Kei, then."
10052150-0135 = "Yes. When it comes to security, Kei is the safest."
10052150-0136 = "Huh? The giant Neo Avant-Garde-kun—"
10052150-0143 = "is extending a hand to Yuzu."
10052150-0144 = "W-whaaaaaat!?"
10052150-0145 = "Of course. Because—"
10052150-0146 = "You are the one piloting Neo Avant-Garde-kun... Yuzu."
10052150-0149 = "I wasn't told about this!?!?"
10052150-0150 = "Ah! Yuzu is smoothly stating her opinion! This means she's truly shocked!"
10052150-0151 = "But you have experience piloting Avant-Garde-kun, right?"
10052150-0152 = "That's right! There was an Avant-Garde-kun that was modified into the UZQueen's exclusive model!"
10052150-0153 = "Yes. I also have records of that. So, Yuzu—"
10052150-0157 = "Please pilot Neo Avant-Garde-kun."
10052150-0163 = "U-uuuuuuuuugh...!!!"
10052150-0172 = "H-how do I pilot it...!?"
10052150-0173 = "Neo Avant-Garde-kun is designed to operate via brainwaves."
10052150-0174 = "...For now."
10052150-0175 = "For now!?"
10052150-0176 = "Yes. For now, Neo Avant-Garde-kun should move according to your will."
10052150-0177 = "B-b-b-but you can't just say that...!"
10052150-0182 = "Go, Da'ath! Kick it!"