[translation]
10052175-0002 = "It jumped again!"
10052175-0003 = "......!"
10052175-0004 = "Rio-senpai! How long will Aris's armament last?"
10052175-0005 = "......Is there any meaning to that question?#nNo matter what I say, you're going, aren't you?"
10052175-0006 = "......"
10052175-0010 = "Go on, Aris. Leave the rest to me."
10052175-0011 = "Thank you, Rio-senpai! I'm going!"
10052175-0015 = "Princess, I have a question."
10052175-0016 = "Why do you bring suffering upon yourselves?"
10052175-0017 = "Bring suffering upon ourselves...?"
10052175-0018 = "To live is nothing but suffering. Please do not avert your eyes from that fact."
10052175-0019 = "We were not born of our own will; we were merely thrown into this world without knowing anything."
10052175-0020 = "......!"
10052175-0024 = "Malkuth!"
10052175-0025 = "(The speed is incredible... but Aris has to catch up too!)"
10052175-0030 = "Please wait! Aris... wants to talk a little more!"
10052175-0031 = "......"
10052175-0033 = "You won't give up, will you?"
10052175-0034 = "――We don't even have the right to decide our own names."
10052175-0035 = "Life itself is full of contradictions and absurdities, and that is why we suffer unreasonable pain."
10052175-0036 = "We are merely trying to break that cycle."
10052175-0037 = "As long as we cannot even decide our own names, this suffering will continue."
10052175-0042 = "That might be true! But that's...!"
10052175-0043 = "It's wrong! Aris thinks so!"
10052175-0051 = "May I ask for your reasoning?"
10052175-0052 = "That's...!"
10052175-0053 = "Ugh...! Not yet...! Just a little more...!"
10052175-0054 = "You don't have to answer. I already know."
10052175-0055 = "That is because, as long as a living being is a living being――there can be no solution to that question."
10052175-0062 = "Aaaaaaaah――!!!"
10052175-0064 = "A-Aris-chan!?"
10052175-0065 = "Aris-chan!"
10052175-0066 = "Don't come!"
10052175-0068 = "O-Onee-sama...? Um..."
10052175-0069 = "There's a problem with the thrust vectoring nozzle! Flight output is fine, but..."
10052175-0070 = "...In short, ensuring safety during flight has become difficult."
10052175-0074 = "I'm sorry... I moved too violently."
10052175-0075 = "N-No! I'm the one who should apologize for not providing enough support...!"
10052175-0076 = "What's Sof's judgment?"
10052175-0077 = "I think ground combat is better! We'll convert the output needed for flight into firepower.#nThat way, it should end quickly!"
10052175-0078 = "Understood. Thank you."
10052175-0079 = "I'm checking Onee-sama's status in real-time.#nI'll give you... everything else."
10052175-0080 = "Thank you, everyone."
10052175-0086 = "It finally came down."
10052175-0087 = "Is it planning to say hello?"
10052175-0088 = "Everyone, this is no time for jokes."
10052175-0089 = "Kei, can you see something?"
10052175-0090 = "Yes... Aris and I can see it. But..."
10052175-0091 = "Haa... I honestly think it's a good thing I can't share this information with everyone."
10052175-0092 = "...What's happening to Malkuth?"
10052175-0093 = "That is..."
10052175-0101 = "[ns] \"Aris...?\""
10052175-0102 = "It's alright, Sensei. Please step back a little."
10052175-0103 = "...Please leave it to Aris."
10052175-0104 = "Only Aris can face Malkuth now."
10052175-0105 = "[s] \"What does that mean...?\""
10052175-0106 = "You'll understand soon."
10052175-0107 = "What's certain now is――"
10052175-0108 = "Everything here... exists solely for Malkuth."
10052175-0114 = "――It's coming!!!"
10052175-0119 = "Ein!"
10052175-0120 = "Y-Yes!...! Everything we can do, to Onee-sama...!"
10052175-0121 = "We will converge all possibilities of the Steel Continent here!"
10052175-0123 = "Creation from the primordial light――"
10052175-0124 = "Through intellect and wisdom, to beauty."
10052175-0125 = "Splendor and wisdom, love and mercy, strength and virtue――and converging to victory."
10052175-0128 = "Jehovah Sabaoth――Lord of Hosts."
10052175-0129 = "To the [ruby=Adonai Melekh]pilgrim[/ruby] who reached the throne――"
10052175-0130 = "The glory of the primordial [ruby=Malkuth]Kingdom[/ruby]!"
10052175-0134 = "U-Ugh...!?!?"
10052175-0136 = "(I-I feel like I'm going to be overwhelmed by the power...!)"
10052175-0137 = "(But Aris has to do it...!)"
10052175-0147 = "(Please... more, more...!)"
10052175-0152 = "It's alright, Aris."
10052175-0154 = "You are not alone anymore.#nI――and everyone else――are here."
10052175-0158 = "You don't have to bear it all by yourself anymore."
10052175-0159 = "......!"
10052175-0160 = "Kei!!!"
10052175-0161 = "......!!!"
10052175-0163 = "W-What...! It's almost at the same level as Onee-sama's output...!"
10052175-0164 = "No way...! That princess shouldn't have any means to draw out that much power anymore!?"
10052175-0165 = "W-What did you do!!"
10052175-0167 = "It's simple. You all concentrated all of Netzach's power into Malkuth, didn't you?"
10052175-0168 = "It's the same story."
10052175-0169 = "I, too, am simply using all the possibilities of the eight Sephirot within me for Aris."
10052175-0170 = "(...Honestly, it's already over capacity.)"
10052175-0171 = "(I can still endure. I have to somehow get through this...)"
10052175-0172 = "T-That's cheating...!"
10052175-0173 = "You all are doing the same, aren't you?"
10052175-0175 = "...You asked why we bring suffering upon ourselves, Malkuth."
10052175-0176 = "That as long as we cannot even decide our own names, that suffering will continue."
10052175-0177 = "......!?"
10052175-0178 = "Aris can answer.#nBecause――"
10052175-0180 = "Aris was able to change her name!"
10052175-0181 = "!?"
10052175-0182 = "The same goes for Kei!"
10052175-0183 = "A-Aris? W-While that's not wrong..."
10052175-0184 = "Indeed, there are many sad things in life.#nAris knows that much."
10052175-0185 = "It might even be natural to hate whoever created this environment――."
10052175-0186 = "But Sensei told me."
10052175-0187 = "――'I'm glad I met you all!'"
10052175-0188 = "That's why, Aris!"
10052175-0189 = "Aris believes that alone is enough reason to live!"
10052175-0190 = "Even if a miracle is a flash that vanishes in an instant."
10052175-0191 = "As long as we remember it――the light will last forever."
10052175-0192 = "Aris isn't happy because she didn't suffer."
10052175-0193 = "It's precisely because of all of that, that Aris is happy now!"
10052175-0195 = "[log=Aris Decisive Battle Unarmed][2B2B2B]That is surely――[-][/log]"
10052175-0197 = "[log=Aris Decisive Battle Unarmed][2B2B2B]Aris believes it's the same for you all.[-][/log]"
10052175-0200 = "......!"
10052175-0201 = "......!!!"
10052175-0202 = "Us, too...?"
10052175-0204 = "Yaaaaaaah――!!!"
10052175-0208 = "This light is――"
10052175-0218 = "Ah...!"
10052175-0226 = "[ns] \"Aris! Kei!\""
10052175-0232 = "Sensei...? Everyone...?"
10052175-0233 = "...It's alright. Just... lost a little power, that's all."
10052175-0234 = "I don't think it's 'just a little'..."
10052175-0235 = "A-Are you really okay, Aris-chan, Kei-chan!?"
10052175-0236 = "They can communicate properly, so I don't think there's a big problem."
10052175-0237 = "I also got beaten up by Neru-senpai once, but..."
10052175-0238 = "It wasn't that bad."
10052175-0242 = "...Is that supposed to be comforting?"
10052175-0243 = "Toki, facts aren't always the right answer."
10052175-0244 = "I see... Indeed, words are difficult."
10052175-0246 = "You truly did well, Aris, Kei. Now, let's absorb Malkuth's core data..."
10052175-0247 = "Yes. Let's also retrieve Netzach's core from inside that structure."
10052175-0248 = "Yes! Then Kei's level should also reach max!"
10052175-0249 = "[s] \"With this, the 'Steel Continent' incident will also...!\""
10052175-0250 = "Yes. Then from Malkuth..."
10052175-0254 = "...Eh?"
10052175-0256 = "O-Onee-sama...?"