[translation]
10052070-0001 = "Kased: The Arbiter who judges with merciful pain"
10052070-0002 = "Sooo bored!!"
10052070-0003 = "Here we go again. Big sis, isn't this the time to be doing something else?"
10052070-0004 = "But we're the only ones staying behind, right? Even the teacher left!"
10052070-0005 = "We're not here to play. Don't you remember we're in the middle of enemy territory?"
10052070-0006 = "...What was the name of the prophet here again? Kased?"
10052070-0007 = "Yeah."
10052070-0008 = "I wonder what kind of kid Kased is..."
10052070-0009 = "Calling them by name like they're a friend... #nI think they said it was some kind of factory."
10052070-0010 = "Was it in the Millennium ruins? #nThat place brings back memories..."
10052070-0011 = "Yeah, we went to the ruins to find the G.Bible and—"
10052070-0013 = "We found Aris."
10052070-0016 = "Kased was originally a [ruby=Divi:Sion]Division[/ruby]... right? #nIt's an AI that produces them, isn't it?"
10052070-0017 = "I don't have good memories of that name... #nIt's that octopus or squid-like machine, right?"
10052070-0019 = "And it was related to Kei... wait. #nDoes that mean Kased has a really strong connection to us!?"
10052070-0020 = "And yet we're just waiting on the transport ship! This is terrible!"
10052070-0021 = "It can't be helped. Kased is a factory, and it produces a tremendous amount of military power."
10052070-0022 = "They said we couldn't hold back our own forces to counter that."
10052070-0023 = "So we're considered out of the fight!?"
10052070-0024 = "It's because Big sis drew the short straw for the ones staying behind..."
10052070-0025 = "Gah, well, that's..."
10052070-0026 = "Well, it's good to get a little rest, isn't it?"
10052070-0030 = "...You know."
10052070-0031 = "Yeah?"
10052070-0032 = "We've really experienced a lot, haven't we?"
10052070-0033 = "Ruins, space, and now a steel continent..."
10052070-0034 = "We were just trying to make a game..."
10052070-0035 = "What are you talking about? This is all material for our game!"
10052070-0036 = "You said that when we went to space too, but we never actually used it, did we...?"
10052070-0047 = "Wh-what's happening!?"
10052070-0051 = "Big sis, over there!"
10052070-0058 = "Huh!? Is that... a Labor?"
10052070-0060 = "More forces are attacking!"
10052070-0065 = "Transport ship, can you hear me?"
10052070-0066 = "I'm sorry. We lost track of the Labor and some of the forces. #nThey're heading your way!"
10052070-0067 = "The transport ship's defense system is weak... but somehow, we'll activate it from here. #nSo—!"
10052070-0071 = "..."
10052070-0072 = "Don't worry, Himari-senpai. We'll protect you."
10052070-0073 = "B-Big sis!?"
10052070-0074 = "We can't just sit here doing nothing, can we? #nOur suits are designed for safety, so we'll be fine!"
10052070-0075 = "Everyone else is working hard, we can't just play around!"
10052070-0076 = "Momoi and Midori were doing more than enough in their respective areas, weren't they?"
10052070-0077 = "Right now, your role is simply to remain on the transport ship..."
10052070-0078 = "That doesn't matter!"
10052070-0082 = "..."
10052070-0083 = "Yeah. I understand."
10052070-0084 = "Himari-senpai. We'll handle this."
10052070-0098 = "Wh-what should we do!?"
10052070-0099 = "Should we go back to Momoi and Midori now?"
10052070-0100 = "..."
10052070-0101 = "That's an option, but I think it would be better to secure this area first."
10052070-0102 = "I agree."
10052070-0103 = "If we turn back now, there's a possibility the front line will be split in two."
10052070-0104 = "Let's trust Momoi and Midori here."
10052070-0105 = "If it were anywhere else, maybe, but this is Kased's territory."
10052070-0106 = "Some attrition warfare is unavoidable."
10052070-0107 = "However, just in case, Himari and Aris, prepare to leave this area."
10052070-0108 = "Why me and Aris?"
10052070-0109 = "Because among us, you two have the highest mobility."
10052070-0110 = "That's logical. Understood."
10052070-0112 = "[ns1] \"...Let's conquer Kased as quickly as possible.\"\n[ns2] \"And then, let's go back to Momoi and Midori.\""
10052070-0115 = "Yes. Then, Teacher—please."