[translation]
10052050-0001 = "HOD: Glory Proven by Radiance"
10052050-0002 = "For the Special Operations Division, it seems that while Binah was the first enemy encountered, HOD was the beginning of everything."
10052050-0003 = "[s] \"Huh, was that right?\""
10052050-0004 = "If I recall, the beginning was--"
10052050-0008 = "The communication unit AI of the Millennium district, '[ruby=hub]Hub[/ruby]'."
10052050-0009 = "It was hacked... influenced by Decagrammaton, and then disappeared after leaving behind a mysterious text."
10052050-0010 = "Come to think of it... the prophets of Decagrammaton are all related to Millennium, aren't they?"
10052050-0011 = "Chesed was a munitions factory located in the suburbs of Millennium."
10052050-0012 = "The prototype of Gebura, the polar unmanned probe, can also be said to be related to Millennium in a broad sense..."
10052050-0013 = "And HOD, needless to say..."
10052050-0014 = "That's the big problem!"
10052050-0015 = "The time to install communication infrastructure has increased by an average of 68%!#nBecause Hub was stolen!"
10052050-0016 = "[s] \"It's quite a nuisance for Millennium, isn't it...\""
10052050-0023 = "Right?#nClaiming to become the god of machinery... @#$%^..."
10052050-0024 = "...Sensei#$^@*#... can you hear#%*..."
10052050-0030 = "...!"
10052050-0031 = "Oh, it's you, Key. And Sensei too. Well, this is convenient."
10052050-0032 = "Every time we meet, it's Key, Key... My name is Kei!"
10052050-0033 = "Yes, yes, I understand.#n...Kei. Is that good enough?"
10052050-0034 = "However, I don't understand. You should know many things...#nAre you saying that knowing that?"
10052050-0035 = "What are you talking about?#nThere are so many things I don't know. Especially about this world."
10052050-0036 = "Things that Sensei doesn't know, but you do. I'm sure there are such things, right?#nFor example--"
10052050-0037 = "About the gods who have now vanished... or something like that."
10052050-0038 = "!? "
10052050-0039 = "In other words... the nameless gods, wasn't it?#nAnd about the priests of those nameless gods."
10052050-0040 = "..."
10052050-0041 = "That expression is the answer. It's very easy to understand.#nWell then, proceeding with the conversation on the premise of that 'knowledge'..."
10052050-0042 = "Are the actions of you and the princess... Aris, justifiable?"
10052050-0043 = "A tool created for a purpose deviates from that purpose.#nIs there really any value in that?"
10052050-0044 = "...So? Are you saying we should follow those ignorant fools?"
10052050-0045 = "Ignorant!? How can you say that!?"
10052050-0046 = "It's not a matter of good or bad, I'm just stating the facts."
10052050-0047 = "After denying the current texture and using Aris as a keystone..."
10052050-0048 = "Deconstruct all differentiated divinity and return to the world before it began.#nThat's what you mean, isn't it?"
10052050-0049 = "Whatever the purpose, aren't you originally such a being?#nAren't the remnants of the nameless gods' power meant for that?"
10052050-0050 = "I don't want to hear that from you.#nYou, who shamelessly stole that power."
10052050-0051 = "We are just using what we can use!"
10052050-0052 = "Is that so."
10052050-0053 = "I am also just doing what I can do."
10052050-0054 = "Memories."
10052050-0055 = "Principles."
10052050-0056 = "And foolish delusions, calling them duties--"
10052050-0057 = "I want to gather them all and throw them into some sea!"
10052050-0058 = "Everyone except Aris is an enemy!"
10052050-0059 = "[ns] \"M-me too...?\""
10052050-0060 = "...Well, Sensei might consider you."
10052050-0061 = "W-what are you grinning about!"
10052050-0062 = "Anyway!#nThose fools obsessed with the past should be eliminated by the flow of time!#n...That's what I mean."
10052050-0063 = "I have a lot to say to you who are barging in and doing as you please..."
10052050-0064 = "But, it's fine. I'll overlook it for now as a mistake of youth."
10052050-0065 = "So, why don't you just surrender?"
10052050-0066 = "...Let her talk!!"
10052050-0067 = "That's what I should say."
10052050-0068 = "Even the Sensei you admire is using the Ark of the Covenant, aren't they?"
10052050-0069 = "And you know that it originates from traces before the beginning, don't you?"
10052050-0071 = "W-w-w-who is admiring whom!?"
10052050-0072 = "Take it back right now!#nOtherwise... I'll sue you for factual display!"
10052050-0073 = "Sigh... you're really easy to understand."
10052050-0074 = "Shut up!!!!"
10052050-0075 = "...Ahem."
10052050-0076 = "So, what does that matter?#nDo you think Sensei will use the Ark of the Covenant to re-texture?"
10052050-0077 = "Either way, I will prevent it."
10052050-0078 = "Besides, they are not the type of person to do such a thing."
10052050-0079 = "Then, do you think it's okay for the world to remain as it is?"
10052050-0080 = "Even if it's not perfect, it's reasonably good."
10052050-0081 = "Even if it's not eternal, the world will continue without incident.#n...Do you really think so?"
10052050-0082 = "...That's not right."
10052050-0083 = "Yes, that's right. That's the important part."
10052050-0084 = "So, let's cooperate."
10052050-0085 = "Isn't it much better than watching this ugly world continue endlessly?"
10052050-0086 = "Quarreling is just tiring."
10052050-0087 = "It's not bad."
10052050-0088 = "Oh?"
10052050-0089 = "However, I refuse."
10052050-0090 = "Why!?"
10052050-0091 = "Because Aris would be sad."
10052050-0092 = "And it's troublesome."
10052050-0093 = "Troublesome...? For such a reason?"
10052050-0094 = "It's the most important thing."
10052050-0095 = "'Troublesome' is the driving force of progress!"
10052050-0096 = "Invention is--"
10052050-0097 = "Achieved after thinking hard about how to slack off!"
10052050-0098 = "...You speak as if you've become human."
10052050-0099 = "Shut up."
10052050-0100 = "You are lowering your own value right now."
10052050-0101 = "Aris is the same.#nShe could have become a greater being, and she still can become one anytime."
10052050-0102 = "I really can't understand. Why would you do such a thing?"
10052050-0103 = "It's my prerogative, isn't it?"
10052050-0104 = "Claiming to be great. Saying you live for self-realization.#nThose kinds of people are the most dangerous."
10052050-0105 = "Besides, it's not good to meddle in other people's lives."
10052050-0106 = "It's something that idle people with too much time or people with not-so-good personalities do."
10052050-0107 = "In this case, don't you fall into both categories, the former and the latter?"
10052050-0108 = "...I don't know about the latter, but being called idle is irritating.#nWe are busy too!"
10052050-0109 = "You really don't understand anything."
10052050-0110 = "The idle are the busiest in this world!"
10052050-0111 = "Huh!?"
10052050-0112 = "Don't misunderstand. God did not create humans."
10052050-0113 = "Humans define God."
10052050-0114 = "I've had enough of seeking the one absolute being now."
10052050-0115 = "It's not necessarily like that.#nWe can also take the place of that absolute being."
10052050-0116 = "And, compared to the absolute being you speak of--"
10052050-0117 = "We can create a better world, one that is more fair and rational?"
10052050-0118 = "So, no thank you."
10052050-0119 = "A world that cannot exist without an absolute being should just perish."
10052050-0120 = "You're saying the same thing as Sensei!!"
10052050-0124 = "T-that's true..."
10052050-0125 = "But, it's not wrong, is it?"
10052050-0126 = "I will watch over it. Together with Aris."
10052050-0127 = "Well... including Sensei, by the way."
10052050-0128 = "In a sense, you might be right.#nLife forms are indeed foolish."
10052050-0129 = "However, they are too wise to perish."
10052050-0130 = "...Well, they are too foolish to create paradise."
10052050-0131 = "Therefore, I believe they will continue to shuttle between those extremes, fall and rise again many times..."
10052050-0132 = "And eventually, find their way."
10052050-0133 = "...That's what you call baseless confidence."
10052050-0134 = "...What I just said was something Sensei taught me. I don't know."
10052050-0135 = "Shifting the blame!!"
10052050-0139 = "[ns1] \"That's right! In times of need, Sensei will take responsibility!\"\n[ns2] \"Adults bear the mistakes of children!\""
10052050-0142 = "Honestly... if Sof were here, she would have said, 'Don't spoil them.'"
10052050-0143 = "Anyway, I don't want you to meddle."
10052050-0144 = "Just because a new sprout looks like it's growing slowly, you shouldn't forcibly pull it."
10052050-0145 = "Stretched plants will eventually wither from the roots."
10052050-0146 = "...The analogy doesn't make much sense."
10052050-0147 = "Study a little!"
10052050-0148 = "Unnecessary! I'm not a student!"
10052050-0149 = "Sensei! Can't we somehow enroll those children?"
10052050-0150 = "[s] \"The enrollment forms are ready, so contact me anytime.\" "
10052050-0151 = "No thank you. Shoo, shoo."
10052050-0152 = "Now, HOD! Preparations are complete!"
10052050-0158 = "Your choiceâ€”I'll make you regret it!"