[translation]
10052105-0002 = "I've come to retrieve the core data."
10052105-0003 = "Hm? Oh, the department head said, \"This was a poor choice of personnel,\" and quickly returned to the transport ship."
10052105-0004 = "[s] \"How's Eimi?\""
10052105-0005 = "She's doing well, but... it's still not enough. I wish it were a real glacier."
10052105-0006 = "Can't an artificial environment beat real nature...?"
10052105-0012 = "From my perspective, you are more unnatural..."