[translation]
10052135-0003 = "Yesod--Destroyed!"
10052135-0004 = "...So that's what collapses."
10052135-0005 = "Did you see that, Sensei? Aris did it! The rematch was a success!"
10052135-0006 = "I-It's still scary to descend... Ugh..."
10052135-0008 = "Everyone's safe, and it's a big victory, right! Hehe!"
10052135-0009 = "Kei-chan, Sensei. I'm counting on you."
10052135-0015 = "[ns] \"Shall we descend too?\""
10052135-0019 = "[ns] \"...Kei-chan? You look a bit conflicted?\""
10052135-0020 = "No, it's just... I thought it was a bit cheeky. #nTo only achieve this much despite using the power of nameless gods..."
10052135-0021 = "Back in my day...!"
10052135-0022 = "[s] \"There it is. The 'back when I was young' story.\" "
10052135-0026 = "...Sensei."
10052135-0027 = "Are you trying to disparage me as an annoying person who lectures by recounting their own heroic tales!?"
10052135-0028 = "[s] \"I didn't say that much...\""