[translation]
10052100-0001 = "Gebura: A Valiant Arbitrator Beyond Reason"
10052100-0003 = "..."
10052100-0004 = "Why again... an environment like an ice sea!?"
10052100-0005 = "[s] \"It must be just this area...\""
10052100-0006 = "I know that! I'm angry at Gebura! #nWhy are you so insistent on such a cold environment!"
10052100-0007 = "It was the same with Kokuma... perhaps prophets each have their preferred terrain or environment...?"
10052100-0008 = "I see. It's the same as when Himari-buchou argues with Eimi about the air conditioner temperature."
10052100-0009 = "As I always say, Eimi just doesn't feel the cold extremely, right?"
10052100-0010 = "I'm sorry, Himari-buchou... but for me, this is also a nostalgic environment."
10052100-0011 = "We pursued the signal of a Decagrammaton suddenly detected in the ice sea... and ended up fighting Gebura."
10052100-0012 = "[s] \"It was Toki's first mission, wasn't it?\""
10052100-0013 = "Yes. It was the first mission I carried out with you, Sensei, as a member of the Special Phenomena Investigation Department."
10052100-0014 = "In addition, I was freezing from the cold back then. #nI endured it with sheer willpower, seeing Eimi."
10052100-0015 = "How about it, Sensei? Seeing me try so hard, don't you feel like praising me?"
10052100-0016 = "[s] \"Toki always works hard for us.\""
10052100-0017 = "Thank you. But it's still not enough. #nI am Asukama Toki, so I will demand more from you, Sensei."
10052100-0018 = "...Sensei. Spoiling me too much isn't good, you know?"
10052100-0019 = "[s] \"...Is that so?\""
10052100-0020 = "Is that so? It can't be helped. Then I will sadly sulk alone, a little distance away."
10052100-0021 = "Ah, um! Aren't you cold now...?"
10052100-0022 = "Yes. This suit has excellent cold-weather functions, so the cold is not a problem. #nThank you for your concern, Yuzu."
10052100-0023 = "...Hah! If I didn't have cold-weather functions, couldn't I have used that as an excuse to stick close to Sensei...? What a blunder on my part..."
10052100-0025 = "Toki. We'll be resuming our field investigation soon."
10052100-0026 = "Gebura's origin is believed to be an unmanned probe that was housed at a polar research base. #nAs usual, its AI was hacked by a Decagrammaton."
10052100-0027 = "In Decagrammaton's terms, they call it 'inspiration' rather than hacking... but let's put that aside for now."
10052100-0028 = "What concerns me is how it was able to transform to that extentâ€”"
10052100-0034 = "H-Hii...!?"
10052100-0035 = "It has appeared."
10052100-0039 = "Then Sensei, please take command."