[translation]
10052075-0009 = "Moooh! There's no end to it!"
10052075-0013 = "Midori! Do you still have ammo?"
10052075-0028 = "I'm running out soon, but—"
10052075-0029 = "Here! This is my last magazine... Use it wisely, okay?"
10052075-0031 = "What about Midori's!?"
10052075-0032 = "I... still have half left!"
10052075-0033 = "Even if you tell me to use it wisely, the number of enemies..."
10052075-0034 = "Just... buying time—"
10052075-0038 = "[log]Light—!!![/log]"
10052075-0044 = "Aris!!!"
10052075-0045 = "Momoi, Midori! Are you alright? Aris, did you make it in time?"
10052075-0046 = "Yeah! Perfect!"
10052075-0047 = "Hehe, Sensei. How was my wheelchair driving?"
10052075-0048 = "Himari-senpai, that was a motorcycle..."
10052075-0049 = "It's a wheelchair."
10052075-0050 = "Yes..."
10052075-0054 = "W-Wait, Sensei, are you okay!? Your complexion...!"
10052075-0055 = "[s] \"I... I'm... fine...\""
10052075-0056 = "Next time, I'll bring motion sickness medicine..."