[translation]
10052015-0003 = "......"
10052015-0004 = "......"
10052015-0005 = "Huh? This isn't a dream, is it...?"
10052015-0006 = "Yeah, I think it's real. It was moving so strangely... it was amazing..."
10052015-0007 = "Will we be able to return safely...?"
10052015-0008 = "Don't worry. We have the professor."
10052015-0009 = "It'll surely be alright."
10052015-0010 = "Wh-why are you so calm...?"
10052015-0011 = "Hmm, there are various reasons..."
10052015-0012 = "Maybe it's because I've encountered something like this before."
10052015-0014 = "[ns] \"By the way, where is Binah's core?\""
10052015-0015 = "About that..."
10052015-0016 = "To get straight to the point, we need to descend into the hole. #n Judging by the reaction, the core seems to be at the bottom."
10052015-0017 = "Whaaat!? Descend!?"
10052015-0018 = "Does this mean... we'll have to do this every time from now on...?"
10052015-0019 = "No, as I mentioned earlier, I believe Binah is special. #n It's likely some kind of security measure."
10052015-0020 = "A... physical measure, huh..."
10052015-0021 = "But it's too inefficient to just keep descending without seeing the bottom..."
10052015-0022 = "President, could you send the small support craft from the transport ship?"
10052015-0023 = "It's already on its way."
10052015-0024 = "...By the way, Rio is coming along too. I couldn't stop her."
10052015-0025 = "The President is coming too?"
10052015-0026 = "Yes. Further investigation revealed that we couldn't breach the firewall via the network..."
10052015-0027 = "So, it was deemed most logical to come to the site in person..."
10052015-0028 = "...That sounds like Rio."
10052015-0031 = "(Soon, a small support craft arrived, and Rio appeared.)"
10052015-0032 = "(Rio tilted her head at everyone's indescribable expressions.)"