[translation]
10052190-0003 = "...Why?"
10052190-0004 = "Why do you continue this futile resistance?"
10052190-0005 = "The more you struggle, the more your suffering will increase."
10052190-0009 = "[ns] \"Huh...?\""
10052190-0010 = "Th-The surroundings...? The Steel Continent...?"
10052190-0011 = "Don't panic!"
10052190-0012 = "This is like a 'virtual domain' created by Decagrammaton expanding its energy!"
10052190-0013 = "If we just defeat it, everything will return to normal!"
10052190-0014 = "In other words, this 'domain' can be said to be a space constructed for Decagrammaton."
10052190-0015 = "Th-That's true, but... how did you know?"
10052190-0016 = "You saw it in a manga or a game, didn't you?"
10052190-0017 = "That's right. I am a perfect maid and agent, after all."
10052190-0018 = "Please take this seriously from now on, okay!?"
10052190-0025 = "...S-Sensei!"
10052190-0026 = "[s] \"What's wrong?\""
10052190-0027 = "Communication with the transport ship has been cut off!"
10052190-0028 = "What!?"
10052190-0029 = "Absolute Domination Device 'Atziluth's Belt' -- activating."
10052190-0034 = "The mechanical structures floating in the air...?"
10052190-0036 = "[ns] \"What is that...?\""
10052190-0039 = "I will not take your lives."
10052190-0040 = "I promise you that much, in consideration of you having knelt and shown your unsightly forms."
10052190-0041 = "Through the Key's body, the power of the eight Sephirot has gathered."
10052190-0042 = "From this moment -- I shall extend the 'conversion,' which was limited to inorganic matter, to all elements."
10052190-0043 = "Under this Atziluth's Belt, you shall become a part of the Steel Continent."
10052190-0044 = "You shall be granted new bodies and souls, and be reborn as my apostles."