[translation]
10052040-0001 = "Uniform"
10052040-0002 = "Ugh..."
10052040-0003 = "[s] \"Are you okay?\""
10052040-0004 = "I'm feeling more dizzy than I expected. Especially the left side of my head..."
10052040-0005 = "[s] \"Are you really okay?\""
10052040-0006 = "The cause is definitely bringing back and activating the Binah's core..."
10052040-0007 = "..."
10052040-0008 = "I'm fine. It's just a matter of this body getting used to the energy flow."
10052040-0009 = "[s] \"You're really... really okay, right...?\""
10052040-0010 = "You worry too much. The symptoms are gradually calming down. #nHowever, if I have to go through this every time I retrieve a core, it's quite disheartening..."
10052040-0011 = "Perhaps the reason this body was described as \"Defected\" is because of this..."
10052040-0012 = "In any case, each time I activate the core, I should be able to redesign the transport ship's output and functions."
10052040-0013 = "And that energy flow is connected to my body... #nWell, to get straight to the point, I believe I can control it."
10052040-0014 = "[s] \"Don't push yourself too hard, Kei-chan.\""
10052040-0015 = "Who are you calling Kei-chan, already."
10052040-0024 = "Aris...? #nWhat is this...?"
10052040-0025 = "It's a uniform!"
10052040-0026 = "I can see that, but why this..."
10052040-0027 = "This is the first outfit Aris was ever allowed to wear!"
10052040-0028 = "Aris... was really happy about that. So, I want to share it with Kei too!"
10052040-0032 = "Could it be... you didn't like it...?"
10052040-0033 = "Of course not! It's more like... really..."
10052040-0037 = "Hehehe..."
10052040-0038 = "Naturally. Millennium's uniform is the most rational choice."
10052040-0039 = "...It's very like you to add a comment here."
10052040-0041 = "[ns] \"When you think about student combat uniforms, it's gotta be the school uniform, right!\""
10052040-0042 = "What are you talking about all of a sudden...?"
10052040-0043 = "Huh? If you think of studying as an enemy, the classroom is the battlefield to defeat it, and the combat uniform is the school uniform...?"
10052040-0044 = "..."
10052040-0045 = "For now, I'll accept that..."
10052040-0046 = "Th-then, I'll... wear this..."
10052040-0047 = "..."
10052040-0048 = "Yes! Please try it on! #nAris wants to see Kei in her uniform soon!"
10052040-0049 = "...!"
10052040-0055 = "H-how is it...?"
10052040-0056 = "Wow!"
10052040-0057 = "[ns] \"Ooh...\""
10052040-0058 = "Wh-what's with that reaction...!"
10052040-0059 = "You look really good in it, Kei-chan."
10052040-0060 = "Yeah, really cute."
10052040-0061 = "...!!!"
10052040-0062 = "Th-thank you... Yuzu, Midori."
10052040-0066 = "Are you okay? Aren't you hot?"
10052040-0067 = "I'm not you..."
10052040-0068 = "Kei, it suits you very well."
10052040-0069 = "For a moment, I thought the throne of the perfect cute cool beautiful girl might be threatened."
10052040-0070 = "...I'm not aiming for something like that."
10052040-0071 = "The throne of the perfect cute cool beautiful girl has been secured. #nWith this, I can live on without being discouraged."
10052040-0072 = "Are you listening...?"
10052040-0082 = "Ahem. Well..."
10052040-0083 = "Thank you."
10052040-0084 = "Hmm? I couldn't quite hear you~?"
10052040-0085 = "Grrr...!"
10052040-0089 = "Ah, thank you! Is this good enough!?"
10052040-0090 = "That's more like it! Expressing gratitude is important!"
10052040-0091 = "[ns] \"Exactly!\""
10052040-0092 = "Of all people, these two are having a sensible conversation...!"
10052040-0093 = "A-anyway!"
10052040-0094 = "This uniform... I'll wear it only when necessary."
10052040-0095 = "Why?"
10052040-0096 = "That's because, well..."
10052040-0097 = "..."
10052040-0098 = "I want to cherish the clothes that hold everyone's feelings..."
10052040-0099 = "Kei-chan... Thank you."
10052040-0100 = "N-no... thank *you*..."
10052040-0101 = "Can't be helped! Kei is a shy one!"
10052040-0102 = "MOMOI--!!!"