[translation]
10052130-0001 = "Yesod: Purifier of the Foundation-Governing Power"
10052130-0004 = "I'm in position."
10052130-0005 = "So we're climbing up there."
10052130-0006 = "..."
10052130-0007 = "What should we call that?"
10052130-0008 = "Hmm... a wall?"
10052130-0009 = "Yes. I think that's the most fitting name."
10052130-0010 = "That Prophet, Yesod, was it?"
10052130-0013 = "It gave us quite the welcome as soon as we arrived."
10052130-0014 = "We managed to defeat it once, but..."
10052130-0017 = "...It was literally like an ironclad guardian, wasn't it?"
10052130-0018 = "Its epithet is completely different from [ruby=Path]Path[/ruby], though."
10052130-0019 = "What was it again?"
10052130-0020 = "Path is 'The Truth that Advances Towards Completion'."
10052130-0021 = "Its epithet is 'Purifier of the Foundation-Governing Power'."
10052130-0022 = "...You remember all of that?"
10052130-0023 = "Because I had nothing else to do."
10052130-0024 = "Huh...?"
10052130-0025 = "...My apologies, that was a slip of the tongue.#nEveryone else has so much to do."
10052130-0026 = "You said that reflexively again, didn't you?#nToki, you might want to learn to read the room a bit better."
10052130-0027 = "Is that so? I'll be more careful from now on.#nAlso, it's true that I made that joke reflexively."
10052130-0028 = "...Because I'm scared."
10052130-0029 = "...Toki, do you feel scared too?"
10052130-0030 = "Eimi?"
10052130-0034 = "I'm scared too."
10052130-0035 = "Everyone might think I'm—"
10052130-0036 = "—that we're—"
10052130-0037 = "—a bit strange as students, but..."
10052130-0038 = "Our feelings are the same."
10052130-0039 = "I hate troublesome things, and I want to be lazy."
10052130-0040 = "If possible, I'd like to eat potato chips with Sensei and watch gameplay videos."
10052130-0041 = "Gameplay videos?"
10052130-0042 = "I'm currently in the process of finding a hobby."
10052130-0043 = "It's what you'd call a 'temporary hobby'. V."
10052130-0044 = "...Temporary?"
10052130-0045 = "Yes. I'm a little interested in gameplay videos right now, but that might change again soon."
10052130-0046 = "Do you have other 'temporary hobbies'?"
10052130-0047 = "Hmm, I suppose games. Playing with Aris is fun.#nAlso, manga is decent."
10052130-0048 = "After trying various things, I realized something.#nThat enjoyment includes a certain degree of irrationality and inefficiency."
10052130-0049 = "Manga, games... I see."
10052130-0050 = "It's not like I particularly like fighting either.#nIf there's a more efficient way to solve things, that would be better."
10052130-0051 = "I wish everyone could just get along."
10052130-0052 = "I wish this situation could have been like that too, but..."
10052130-0053 = "I'm scared right now.#nThe thought that something might happen and Sensei or I won't see tomorrow..."
10052130-0054 = "Just that thought makes my chest ache."
10052130-0055 = "What about me?"
10052130-0056 = "I'm worried about you, perhaps second only to myself and Sensei."
10052130-0057 = "...Are you serious?"
10052130-0058 = "It's a joke. There's no hierarchy in human lives."
10052130-0059 = "...Thank you."
10052130-0060 = "I don't want anyone to get hurt."
10052130-0061 = "I want all suffering to disappear from everyone living in the present."
10052130-0062 = "That... might be a bit difficult."
10052130-0063 = "That's why everyone prays for the safety of at least those within their reach.#nThis world is full of scary things, after all."
10052130-0064 = "The Department Head alone is a handful, but recently even the President..."
10052130-0065 = "...And I'm really... worried about Sensei too."
10052130-0066 = "I see. Maybe we should just lock Sensei in a Millennium-made shelter?"
10052130-0067 = "If it's to guarantee Sensei's safety, that might be the most efficient method."
10052130-0068 = "Are you planning to wage war against Kivotos?"
10052130-0069 = "Very well. If that's your intention, I will proudly stand on the front lines."
10052130-0070 = "...It was a joke."
10052130-0071 = "I was joking too."
10052130-0072 = "With Toki, you never know if she's joking or serious..."
10052130-0073 = "Is that so? But thanks to that, I learned something."
10052130-0074 = "Precisely because the situation is dangerous and difficult."
10052130-0075 = "We should actively make jokes and laugh at trivial things."
10052130-0076 = "...Otherwise, I won't be able to bear it."
10052130-0077 = "So, is Toki's usual behavior an extension of that too?"
10052130-0078 = "No, that's just me saying whatever comes to mind."
10052130-0079 = "...That's so Toki, really."
10052130-0088 = "Toki, Eimi, can you hear me? Our preparations are complete.#nWe'll match your movements, so you decide the timing for the assault."
10052130-0089 = "We can finally see the end, can't we? It's been quite a long journey, but..."
10052130-0090 = "This is the last Prophet, right?"
10052130-0091 = "Technically, there are still two left. Netzach, who is the Steel Continent itself, and—"
10052130-0092 = "Malkuth..."
10052130-0093 = "Ugh... C-can we really defeat them...?"
10052130-0094 = "It's alright, Yuzu! We all got new weapons and armor!#nKei has also leveled up a lot!"
10052130-0095 = "Yes... I think we're better than before.#nWe can now utilize the Prophet's power to some extent, after all."
10052130-0098 = "It feels like the time has come."
10052130-0099 = "Yes."
10052130-0104 = "I'll go first. I'll be leading the vanguard this time."
10052130-0105 = "My armament is lighter than usual, and it feels good."
10052130-0108 = "[ruby=Operation Steel Rain]Operation Steel Rain[/ruby]—"
10052130-0109 = "Keep Yesod's attention firmly until everyone else descends."
10052130-0112 = "Eimi, you were providing fire support from the rear, right?"
10052130-0113 = "They said that's the most efficient way to use me in this operation."
10052130-0114 = "Alright then, I'll leave it to you. Stay safe."
10052130-0115 = "Good luck."
10052130-0118 = "You too."