[translation]
10052140-0001 = "Mercy"
10052140-0010 = "Ah, ah, ahwahwahwah...!!!"
10052140-0011 = "N-No way...!? That can't be...!"
10052140-0016 = "..."
10052140-0017 = "Turn off the alarm."
10052140-0019 = "Alarm output, cancelled."
10052140-0024 = "S-Sof...?"
10052140-0025 = "Are you sure!?"
10052140-0027 = "This much won't have any effect."
10052140-0028 = "Right?"
10052140-0030 = "..."
10052140-0031 = "W-Well..."
10052140-0032 = "Ein, how's the preparation progress?"
10052140-0033 = "I-It'll be done soon!"
10052140-0034 = "Oh, both of them?"
10052140-0035 = "Yes!"
10052140-0037 = "I see. Then..."
10052140-0038 = "What are you going to do?"
10052140-0039 = "What do you mean, 'what'? They're already right here."
10052140-0040 = "We should at least give them a welcoming greeting, shouldn't we?"
10052140-0041 = "..."
10052140-0042 = "Indeed. We still have two cores on our side."
10052140-0043 = "We can even get back the cores that were stolen."
10052140-0044 = "Exactly."
10052140-0045 = "Then, Sof... you're going?"
10052140-0046 = "I'm going to go see their faces directly."
10052140-0048 = "S-Should I go too...?"
10052140-0049 = "Ein, you stay here."
10052140-0050 = "Your work is more important than us."
10052140-0054 = "Y-Yes...!"
10052140-0056 = "We have successfully captured all areas of the Steel Continent, excluding the central Netzach area."
10052140-0057 = "No way... We actually did it..."
10052140-0058 = "If you follow the correct procedures, you'll generally reach the final goal.\nIt's not that surprising."
10052140-0059 = "So, what if things didn't go in order...?"
10052140-0060 = "In that case..."
10052140-0061 = "We might have been wondering how to live in Kivotos, covered by the Steel Continent?"
10052140-0062 = "Y-Yes...!?"
10052140-0063 = "There's also the saying, 'All's well that ends well.'\nSince it went well now, all is well."
10052140-0064 = "That's so rough..."
10052140-0065 = "You've accomplished something almost impossible, you know?"
10052140-0066 = "As long as it's not zero, the possibilities aren't closed off."
10052140-0067 = "Aris wasn't worried!\nSensei and everyone were here! And President Rio too!"
10052140-0068 = "M-Me...?"
10052140-0069 = "Yes! It's a 'fall to light'!"
10052140-0070 = "Huh? But then... that would mean Rio-senpai was originally an enemy...!"
10052140-0071 = "I'm sorry, Rio-senpai! I didn't mean it like that...!"
10052140-0072 = "I don't mind. Besides, at that time, I... did have that side to me..."
10052140-0076 = "Thank you, Rio-senpai!"
10052140-0081 = "Have you ever thought about the beginning of everything?"
10052140-0082 = "!?"
10052140-0084 = "For example, let's say there's a question like this."
10052140-0085 = "...!"
10052140-0090 = "Where do we come from?"
10052140-0091 = "What is our purpose?"
10052140-0092 = "Where are we going?"
10052140-0094 = "Kei...!"
10052140-0095 = "Yes, I hear it too."
10052140-0097 = "Perhaps God is a discipline for those who follow."
10052140-0101 = "Aris? Kei? Is something wrong?"
10052140-0105 = "Huh? Oh, w-well...!"
10052140-0106 = "No, it's nothing. I'm fine."
10052140-0107 = "Oh, thank you, Kei..."
10052140-0108 = "That's what I'm here for."
10052140-0109 = "But... what did that mean?\nKei, do you know anything?"
10052140-0110 = "I don't know the details..."
10052140-0111 = "It's probably related to our beginning..."
10052140-0113 = "Everyone, be careful. Something is approaching."
10052140-0120 = "..."
10052140-0121 = "..."
10052140-0122 = "[s1] \"Sof-chan! Ohr-chan!\"\n[s2] \"Isn't Ein-chan with you?\""
10052140-0125 = "...Unbelievable."
10052140-0126 = "Ugh..."
10052140-0128 = "No, no. You have to return a greeting with a greeting."
10052140-0129 = "I don't recall us becoming close enough to exchange casual greetings, Izumimoto Eimi."
10052140-0130 = "That name is too long and inefficient. Call me Eimi from now on."
10052140-0131 = "...Huh?"
10052140-0132 = "Eimi."
10052140-0133 = "No, I mean..."
10052140-0134 = "Eimi."
10052140-0135 = "...Fine, Eimi."
10052140-0136 = "Good, well done."
10052140-0137 = "..."
10052140-0138 = "Defeating the eight prophets and taking almost all control of Netzach... \nHonestly, I think that's amazing."
10052140-0140 = "...Tch."
10052140-0141 = "I have a suggestion: why don't we let bygones be bygones and have you transfer in?"
10052140-0142 = "I reconfirmed with Sensei, and apparently, you can take your pick now."
10052140-0143 = "Of course, where you choose is up to you all.\nKivotos is a massive academy city, home to thousands of schools—"
10052140-0144 = "You could say you all have thousands of possibilities."
10052140-0145 = "But still, I recommend Millennium Science School."
10052140-0146 = "How many times do I have to tell you? We don't need it."
10052140-0147 = "And now, as a special offer, you can even get a commemorative item personally designed by Lady Rio."
10052140-0148 = "Huh...? I don't recall preparing anything like that..."
10052140-0149 = "Play along!"
10052140-0150 = "O-Okay..."
10052140-0151 = "Anyway, Kivotos—especially Millennium—welcomes any student, you know?"
10052140-0152 = "No, seriously, we don't need it."
10052140-0153 = "(Having this kind of conversation makes me feel pathetic, but I have to buy time for Ein...)"
10052140-0154 = "[s] \"I won't give up on any of you.\""
10052140-0155 = "Our minds haven't changed either.\nBesides, isn't that the same topic every time? Don't you have a very limited repertoire of conversation topics?\nThough, I suppose neither of us has anything particular we want to talk about."
10052140-0157 = "Huh? Then what did you come here for?"
10052140-0158 = "If anything, it always seems like you're the ones who come to talk..."
10052140-0160 = "Ugh."
10052140-0162 = "W-Well, that, um...!"
10052140-0163 = "Well, since we came all this way, right?\nSo I thought I'd at least see your faces. That's all!"
10052140-0164 = "[s] \"I see, you're good kids. Very good.\""
10052140-0165 = "Well, since we're here, let's deepen our exchange a little more."
10052140-0166 = "What more do you intend to make us do?\nIf you do something clumsy and we develop feelings, wouldn't you be the ones in trouble?"
10052140-0167 = "Oh, I've already developed them, you know?"
10052140-0168 = "Are you serious? To you, we're unknown villains trying to cover the world in metal—\nRight?"
10052140-0169 = "It's like a child's prank.\nYou can still go to school and study, even now."
10052140-0170 = "Yes, that's right. You're probably still in a very immature phase."
10052140-0171 = "...Well, some people remain immature even as they get older."
10052140-0172 = "H-Himari-senpai...!"
10052140-0173 = "It's alright."
10052140-0179 = "Whose story is that? It doesn't seem to be about those girls..."
10052140-0180 = "...See, as you can tell."
10052140-0181 = "Y-Yes..."
10052140-0182 = "[s] \"Anyway, people should study, you know.\""
10052140-0183 = "We aren't even human to begin with."
10052140-0184 = "[s] \"You are people. If you understand discretion and know manners, there's no difference.\""
10052140-0185 = "You seem to be misunderstanding something, so let me tell you: all our knowledge is programmed into us from the start, you know?"
10052140-0186 = "...We're not human anyway."
10052140-0187 = "[s3] \"Thinking you know everything—\"\n[s4] \"is proof that there's still a lot you don't know!\""
10052140-0191 = "Sensei is right. There's also the saying that learning has no end."
10052140-0192 = "Therefore, Sensei.\nWhen we return to the academy, I request individual tutoring for the amount of time we spent here."
10052140-0193 = "Isn't that your duty as a Sensei?"
10052140-0194 = "Is that... really for studying?"
10052140-0195 = "Aris wants to study together too!"
10052140-0196 = "W-Well, that's..."
10052140-0197 = "Alright. If it's a request from cute Aris, I can't refuse."
10052140-0198 = "What is this? This farce..."
10052140-0199 = "..."
10052140-0200 = "Anyway, that's why you always end up regretting things."
10052140-0201 = "You change everything to suit yourselves, then say things like, 'I didn't think it would turn out like this,' or 'I didn't mean for that to happen.'"
10052140-0202 = "Whether the target is other people, nature, or the world itself."
10052140-0203 = "You mess everything up and don't even show a hint of taking responsibility."
10052140-0204 = "Doing things like that, don't you have any regrets?"
10052140-0205 = "Don't you ever wish you could go back to the past and start over?"
10052140-0206 = "[s] \"...I have plenty of regrets.\""
10052140-0207 = "..."
10052140-0208 = "[s5] \"If I had a chance, 'Next time for sure!'\"\n[s6] \"I think everyone has thought that at some point.\""
10052140-0211 = "..."
10052140-0212 = "[s] \"But even if regrets remain, I don't wish to go back to the past.\""
10052140-0213 = "...Why is that?"
10052140-0214 = "[s] \"Because we look back at the past to move forward.\""
10052140-0215 = "...!"
10052140-0216 = "[s7] \"To walk through to the very end.\"\n[s8] \"We look back at the path we've walked so far.\""
10052140-0220 = "[ns9] \"To follow in the footsteps of our predecessors and forge a path—\"\n[ns10] \"That is our way of life.\""
10052140-0223 = "...!"
10052140-0224 = "The human way of life..."
10052140-0225 = "Then, what about us...?"
10052140-0226 = "..."
10052140-0231 = "Ein? Are you there?"
10052140-0235 = "Y-Yes! Elder Sister!"
10052140-0236 = "I apologize. I've burdened Ein.\nHowever, I have certainly been reborn."
10052140-0237 = "N-No, I'm the one who should apologize! Because we were so weak... we ended up relying on you, Elder Sister...!"
10052140-0238 = "No. As an elder sister, I am happy to be relied upon by Ein, Sof, and Ohr."
10052140-0239 = "I am truly happy to be able to help everyone."
10052140-0240 = "Y-Yes...!"
10052140-0241 = "..."
10052140-0242 = "Sof, Ohr. C-Can you hear me? W-We're still okay..."
10052140-0243 = "We still—won't lose!"
10052140-0244 = "Daath's preparations are complete!\nWe'll be heading your way soon!"
10052140-0251 = "I see."
10052140-0252 = "Then...!"
10052140-0253 = "Yes."
10052140-0254 = "We've bought enough time."
10052140-0258 = "Now—listen!"
10052140-0259 = "What's broken can be fixed! For defiled sanctity, light can be rekindled!"
10052140-0260 = "We can still start over! Just like you don't give up!\nUm, and also—"
10052140-0261 = "Expanding possibilities!"
10052140-0262 = "Enlightenment through knowledge!"
10052140-0264 = "Chokhmah's wisdom! Geburah's courage!"
10052140-0265 = "The intangible shadow cast from indivisible unity!!!"
10052140-0270 = "What are those girls doing?"
10052140-0271 = "That's... no way!?"