[translation]
10052120-0001 = "Ritual"
10052120-0011 = "Whaaaaaa!?!"
10052120-0012 = "To the second defense line...? You must be joking...?"
10052120-0017 = "..."
10052120-0018 = "Let's organize the situation."
10052120-0020 = "Y-Yes...! The remaining areas for the prophets are... only two."
10052120-0021 = "The Steel Continent is already over 70% occupied by the enemy."
10052120-0022 = "...The remaining two areas will only buy us time."
10052120-0024 = "They'll probably break through."
10052120-0025 = "Ugh...!"
10052120-0026 = "Ein, calm down. We have to acknowledge what we can't change. It's necessary to think about countermeasures."
10052120-0027 = "Wh-Where did... things go wrong...?"
10052120-0028 = "Was it because I underestimated those people...!?"
10052120-0029 = "I'm sorry, Sof... I'm sorry, Ohr... #nI'm sorry, Big Sis, *sob*!!"
10052120-0034 = "It's alright, Ein. You did nothing wrong."
10052120-0035 = "It's just that an unexpected variable, [ruby=つかつき]Tsukitsuki[/ruby] Rio, slipped in."
10052120-0036 = "Or perhaps it was the Princess and the [ruby=侍女]Maid[/ruby]..."
10052120-0037 = "If we're going by that, then Teacher too..."
10052120-0038 = "..."
10052120-0039 = "Maybe it's also because the combat power on that side was higher than expected..."
10052120-0041 = "Was it because... we deployed the Steel Continent ahead of schedule...?"
10052120-0043 = "But if we hadn't deployed it then... I don't think I would have met you, Big Sis, like this."
10052120-0044 = "Yeah..."
10052120-0046 = "Yes. For that, I am grateful to Ein, Sof, and Ohr."
10052120-0047 = "Big Sis..."
10052120-0048 = "Sof and Ohr, come here. #n I will embrace you."
10052120-0053 = "Eh, really...?"
10052120-0061 = "This is not an act that will break through anything."
10052120-0062 = "In a way, it might be a meaningless act."
10052120-0063 = "But... doesn't it calm your heart a little?"
10052120-0064 = "If you can relax, a good idea might come to you."
10052120-0068 = "Ugh... *sob*..."
10052120-0069 = "Cry your heart out. There's no one else here but us."
10052120-0070 = "It's alright, I'm here. I am truly happy to have met Ein, Sof, and Ohr."
10052120-0076 = "We keep losing control of the Steel Continent."
10052120-0077 = "However, it can also be said that it's not a critical problem yet."
10052120-0078 = "If we can get back the 'body' that the Maid... Kei is using, everything will be back to normal."
10052120-0079 = "It's... ultimately a matter of security level and access rights!"
10052120-0080 = "The expansion of the Steel Continent has stopped, but we should be able to do something about that too."
10052120-0081 = "We just need to regain control of each area of Netzach!"
10052120-0082 = "The remaining forces are two prophets."
10052120-0083 = "And—"
10052120-0084 = "Me."
10052120-0085 = "..."
10052120-0086 = "Before, my output was too strong, so my body couldn't handle it."
10052120-0087 = "In other words, if the problem of [ruby=強度]durability[/ruby] can be solved, I should be able to unleash all my [ruby=出力]potential[/ruby] without reservation."
10052120-0088 = "Solving that is our job!"
10052120-0089 = "I-I will definitely make sure you can soar in your complete form, Big Sis!!!"
10052120-0090 = "For what it's worth, there's still a slight room to utilize the prophets."
10052120-0092 = "Really?"
10052120-0094 = "Ein, please explain."
10052120-0098 = "Um..."
10052120-0099 = "The prophets who were inside the Steel Continent will return to a part of Netzach, but..."
10052120-0100 = "The prophets who were outside the Steel Continent, their remains... will remain, right...?"
10052120-0101 = "I suppose so... but so what?"
10052120-0105 = "...Wait, could it be?"
10052120-0106 = "Precisely."
10052120-0107 = "You can do it!?"
10052120-0108 = "If we can transport them this far, that is..."
10052120-0109 = "The problem is the transportation, huh..."
10052120-0111 = "And we have to do it secretly..."
10052120-0113 = "It's already difficult, and now more conditions are added..."
10052120-0114 = "Is it reckless...?"
10052120-0115 = "..."
10052120-0116 = "No, a job is best when it's a little difficult."
10052120-0121 = "Oh, as expected of you, Sof!"
10052120-0123 = "R-Really!?"
10052120-0124 = "Yeah. We still have some capacity for Labor production."
10052120-0125 = "Th-That's a relief! Then I'll also...!"
10052120-0126 = "No. Ein, you stay here."
10052120-0127 = "Yes...!? Y-You're right, I'm unreliable..."
10052120-0128 = "No, no. Ein, you're the most important. You're going to be incredibly busy from now on."
10052120-0129 = "...Me?"
10052120-0130 = "That's right. From now on, without Ein, we won't be able to do anything."
10052120-0135 = "Y-Yes!?!?"
10052120-0136 = "Ein, listen carefully. #n There are broadly two things I want you to do..."
10052120-0144 = "...Understood?"
10052120-0149 = "..."
10052120-0150 = "Ein? Are you alright?"
10052120-0156 = "Ein!?"
10052120-0157 = "Perhaps the pressure was too much."
10052120-0158 = "But... Ein, please."
10052120-0159 = "Depending on this, our possibilities will be greatly reduced."
10052120-0160 = "We might be able to manage the reinforcement of Malkuth Big Sis if we try hard."
10052120-0161 = "But the other one is something only Ein can do."
10052120-0166 = "..."
10052120-0167 = "I understand. I'll try. #n...No, I will do it."
10052120-0168 = "Absolutely, I will! Even if it means dying!"
10052120-0169 = "No, even if I die!"
10052120-0170 = "Calm down, Ein... #n We're doing this so that none of us have to."
10052120-0171 = "Th-That's right...!"
10052120-0172 = "But... I'll try my best!"
10052120-0173 = "Well, I suppose she's speaking metaphorically..."
10052120-0178 = "..."
10052120-0179 = "Thank you, Ein."
10052120-0180 = "Please take care of my body."
10052120-0181 = "Yes!!!"
10052120-0190 = "Questioning the distinction between real and unreal is outdated. #n The difference between the two is merely a matter of how the subject is perceived."
10052120-0191 = "After all, there is no significant difference between the two."
10052120-0192 = "For example, imaginary numbers exist. #n Just as there's a possibility of a universe where left and right are inverted and time flows backward."
10052120-0196 = "!!!"
10052120-0197 = "Did you hear that?"
10052120-0198 = "Y-Yes! This time I'll properly...!"
10052120-0199 = "The content...!"
10052120-0200 = "Waaah! I remember it but I can't explain it!"
10052120-0201 = "It's alright. I heard it too. #n It was a metaphor about the multiverse."
10052120-0202 = "Multi...verse...?"
10052120-0203 = "It's about a universe where left and right are swapped and time flows backward."
10052120-0204 = "It sounds strange, but there's no proof it doesn't exist."
10052120-0205 = "...Does that mean the voice's owner, could it be...?"
10052120-0206 = "Kei? Did you figure something out?"
10052120-0207 = "Actually, it's not entirely beyond my guess. #n But... even so, I can't explain this."
10052120-0208 = "I'm sorry, Aris. I don't want to hide anything from you, but... this might be something I can't tell you..."
10052120-0209 = "..."
10052120-0210 = "Is it a problem that would change what Aris and Teacher, and everyone else needs to do?"
10052120-0211 = "Yes? No... I don't think so. It's just..."
10052120-0212 = "If that were to intervene..."
10052120-0213 = "...I understand. Aris will continue with what Aris needs to do."
10052120-0214 = "Thinking too deeply about things I don't understand won't lead to anything good."
10052120-0218 = "...Let's do that. #n The remaining areas... there are only two left."