[translation]
10052160-0001 = "Malkuth: Pilgrim of the Kingdom Reaching the World's End"
10052160-0002 = "[ns] \"Those children!?\""
10052160-0003 = "...It seems they're hiding."
10052160-0004 = "Why did they do something like this...? Even at this point, it seems they still have no intention of telling us."
10052160-0005 = "Is our bond still not strong enough...?"
10052160-0006 = "...It's not that simple, Aris."
10052160-0007 = "But it is perplexing."
10052160-0008 = "To say it was all for us, and yet not explain a single thing even when cornered like this."
10052160-0009 = "Right. #nJust talking would buy us time. It's inefficient."
10052160-0010 = "Or perhaps they're acting without thinking ahead in the first place. #nThat's why there's nothing to talk about."
10052160-0011 = "No matter what, they wouldn't have caused such a situation so carelessly..."
10052160-0015 = "Well, the Four Heavenly Kings of the Demon Lord's Castle either don't know the real situation, #nor they just say incomprehensible things!"
10052160-0016 = "Maybe we didn't even need to ask? #nLet's just call it saving time!"
10052160-0017 = "What if there's a reason they absolutely can't tell us...?"
10052160-0018 = "E-Even if there's a reason, I don't think this is acceptable..."
10052160-0020 = "I-I think we're safe here...! #nThey shouldn't be able to find us..."
10052160-0022 = "Ugh... this is tiring, isn't it?"
10052160-0023 = "To this extent..."
10052160-0027 = "Ein, Sof, Ohr, are you alright?"
10052160-0028 = "Y-Yes...! Still--"
10052160-0034 = "No problem! #nUm... Ein seems a little tired, but don't worry, Big Sister."
10052160-0040 = "Good grief. Ein and Sof lack grit. #nStill--!"
10052160-0046 = "..."
10052160-0047 = "Ein, Sof, Ohr."
10052160-0048 = "The Steel Continent was your will, wasn't it?"
10052160-0049 = "Yes... Is something wrong with that?"
10052160-0050 = "I was very happy to hear that Ein, Sof, and Ohr created this Steel Continent of their own will."
10052160-0051 = "However, why did you try to create the Steel Continent? #nWhat did you hope to gain from it--I still don't know."
10052160-0052 = "The plan to expand the Steel Continent and cover Kivotos. #nI perceive that there is no firm reason behind that plan."
10052160-0053 = "Th-That is..."
10052160-0054 = "It's alright. I didn't say it to blame you."
10052160-0055 = "Just, for what purpose were you trying to expand the Steel Continent?"
10052160-0056 = "And regarding the fact that you won't even tell me the reason."
10052160-0057 = "I am simply curious."
10052160-0058 = "Because I believe if you hadn't insisted on the Steel Continent, none of this would have happened."
10052160-0059 = "..."
10052160-0060 = "I'm sorry, Big Sister."
10052160-0061 = "There's a reason we can't tell you."
10052160-0062 = "Because it must not be uttered aloud..."
10052160-0063 = "But please believe us. It's all for you, Big Sister..."
10052160-0067 = "No, it's for you, Big Sister, and for us."
10052160-0068 = "Ein, Sof, Ohr, for me?"
10052160-0069 = "Why, exactly?"
10052160-0070 = "Hey, Big Sister."
10052160-0071 = "Yes, Sof."
10052160-0075 = "Big Sister, do you want to live?"
10052160-0076 = "Huh?"
10052160-0077 = "..."
10052160-0078 = "I'm sorry, I don't understand the intent of your question..."
10052160-0079 = "As long as I possess consciousness, it's natural to wish for its continuation. #nIn that sense... yes, I want to live."
10052160-0080 = "But, Ein, Sof, Ohr."
10052160-0081 = "You already know, don't you?"
10052160-0082 = "Yes. Of course. Much more than anyone else."
10052160-0083 = "Even so, we... want to live."
10052160-0084 = "We want to live... forever, together with you, Big Sister."
10052160-0085 = "That is..."
10052160-0086 = "...!"
10052160-0087 = "I see."
10052160-0088 = "I can't perfectly understand yet, but if that is what you wish."
10052160-0089 = "U-Ugh..."
10052160-0090 = "..."
10052160-0091 = "I'm sorry, Big Sister. We already..."
10052160-0092 = "Yes, I know."
10052160-0093 = "It's alright. #nFrom now on, trust me."
10052160-0094 = "For that person, and for my precious sisters."
10052160-0097 = "Everyone, over there!"
10052160-0102 = "So this is the final boss battle, right?"
10052160-0103 = "Yes. I think it's an apt metaphor. 'Momoi, who occasionally says something good.'"
10052160-0104 = "Um... how many nicknames do I have?"
10052160-0105 = "Do you really want to know?"
10052160-0106 = "N-No... I'm fine."
10052160-0107 = "Please focus properly, already!"