[translation]
10052090-0001 = "Kukmar: The Ancient Guardian Who Protected the Kingdom"
10052090-0003 = "[ns] \"Hey, Kei-chan.\""
10052090-0004 = "What is it?"
10052090-0005 = "[s] \"I wonder if it's okay to have Kei-chan participate in combat...\""
10052090-0006 = "Are you only just now realizing that?"
10052090-0007 = "[s] \"Because I'm worried...\""
10052090-0008 = "If you're teasing me again, I'll get angry."
10052090-0009 = "It's alright, Teacher. If it comes down to it, leave it to me."
10052090-0010 = "[s] \"Eimi is the best agent, after all.\""
10052090-0014 = "Did you just say 'best agent'?"
10052090-0015 = "[s] \"Ah, um, of course Toki is too! Yes!\""
10052090-0016 = "I'm satisfied, so I'll take my leave now."
10052090-0022 = "What am I even seeing...?"
10052090-0023 = "Speaking of which, it was Chairman Rio who discovered Kukmar, right?"
10052090-0024 = "Huh? Yes... that's right."
10052090-0025 = "A work vessel suddenly appearing from the ground. That really surprised me."
10052090-0026 = "It really felt like a 'special phenomenon,' didn't it?"
10052090-0027 = "..."
10052090-0028 = "Rio. As the one who established the Special Phenomenon Investigation Department, what do you think of the current situation?"
10052090-0029 = "Huh? Kei, you know about that too?"
10052090-0030 = "Well... I've generally learned the data and history up to this point."
10052090-0031 = "Did I not mention this...?"
10052090-0033 = "So that's how it was..."
10052090-0034 = "Um, about the current situation, right? #nIs 'deeply moved' the expression to use in a situation like this?"
10052090-0036 = "...! "
10052090-0037 = "...! "
10052090-0038 = "Why do you have that expression?"
10052090-0039 = "Ah... no, it's just..."
10052090-0042 = "Why do you have that expression?"
10052090-0044 = "Ah... no, it's just..."
10052090-0045 = "I thought you've changed a lot too, Chairman."
10052090-0046 = "You're saying that so directly!?"
10052090-0048 = "Can I take that... in a good way? Or perhaps..."
10052090-0050 = "Has your judgment suddenly deteriorated!?"
10052090-0051 = "Kei, calm down. If you get angry at every little thing, you might cause an error in your emotional circuits, you know?"
10052090-0053 = "I can't deny that. Your body hasn't been completely analyzed yet."
10052090-0054 = "If a fatal error occurs, we might not be able to handle it."
10052090-0061 = "Ah... geez...!"
10052090-0062 = "[s] \"...Kei-chan, are you okay?\""
10052090-0063 = "If I collapse from stress, it'll be your fault, you know..."
10052090-0067 = "Kei!? No! Aris, I don't want that!"
10052090-0068 = "No... I was just saying it..."
10052090-0069 = "[s] \"You have a lot of hardships...\""
10052090-0070 = "Thank you for understanding, Teacher..."
10052090-0076 = "Come on, it's time for work, Kei. Teacher, find a safe place."
10052090-0077 = "It's better to be working so I don't have time to think unnecessary things..."
10052090-0078 = "Well then, shall we begin?"