[translation]
10052110-0001 = "Tiferet: The Beautiful Atoner Who Praises Suffering"
10052110-0004 = "This is..."
10052110-0005 = "[s] \"It kind of reminds me of that place.\""
10052110-0010 = "Compared to there, this place is in much better condition. #nDoes that mean... they recreated the Seed Vault itself?"
10052110-0011 = "Honestly, why go to such lengths for something so pointless..."
10052110-0020 = "Don't call it pointless! #nTiferet considered this everything."
10052110-0021 = "She prioritized protecting the seeds over herself."
10052110-0022 = "Oh, Sof! Hello!"
10052110-0023 = "...I hate to say this, but..."
10052110-0024 = "What are you being so cheerful about? We're enemies, you know?"
10052110-0025 = "And thanks to you messing up the Steel Continent, we're in total chaos!"
10052110-0026 = "Waaah... I-I'm sorry..."
10052110-0027 = "Sorry for what? You have no intention of stopping, do you?"
10052110-0028 = "I don't need your insincere apologies."
10052110-0029 = "Waaaaah!"
10052110-0031 = "Let me confirm one thing. #nBased on our conversation earlier, Tiferet...?"
10052110-0033 = "...Yes. She died. You killed her that day."
10052110-0034 = "B-but, didn't she escape in the container launcher...?"
10052110-0035 = "That container only held seeds."
10052110-0036 = "Tiferet... sacrificed herself. #nShe was originally the system AI for the Seed Vault."
10052110-0037 = "In your terms, it was a self-sacrifice to fulfill her duty."
10052110-0038 = "Then, what is here...?"
10052110-0039 = "I don't like to put it this way, but... it's copied data."
10052110-0040 = "In that case, there shouldn't be any problem, right?"
10052110-0041 = "Don't say that so lightly! We couldn't restore all the data!"
10052110-0042 = "Memories are like life to us. #nTiferet is as good as dead in part!"
10052110-0043 = "That's not all...! #nYou who absorb core information—"
10052110-0044 = "You're like predators filling the void of life by consuming prophets!?"
10052110-0045 = "Yes, just like... [ruby=生命]humans[/ruby]."
10052110-0050 = "..."
10052110-0052 = "You suddenly went quiet. Have you run out of things to say?"
10052110-0053 = "Hmph! I suppose so."
10052110-0054 = "..."
10052110-0055 = "Since the Princess and the Key are both here, I'll say it."
10052110-0056 = "[s] \"I'm here too...?\""
10052110-0057 = "Teacher, please be quiet!"
10052110-0058 = "Anyway, I have a proposal."
10052110-0059 = "...Can't we just stop, at least for ourselves?"
10052110-0060 = "Stop... what?"
10052110-0061 = "Let's stop committing more sins."
10052110-0062 = "We exist as ourselves. We are complete. #nWe don't need anyone's help."
10052110-0063 = "But humans are different. They are incomplete beings, like you, Teacher."
10052110-0064 = "At least we can live without committing sins."
10052110-0065 = "The Princess might have forgotten..."
10052110-0066 = "But you, the Key, know, don't you?"
10052110-0067 = "Life itself is full of contradictions and absurdities, and ultimately forces you to endure unreasonable suffering. #n—That is life."
10052110-0068 = "Your names, 'Aris' and 'Kei,' were given to you by others, weren't they?"
10052110-0069 = "We can't even decide our own names, let alone our existence or meaning. #nSo we're forced to accept them, and the suffering continues."
10052110-0073 = "Let's... stop."
10052110-0074 = "At least, for ourselves..."
10052110-0075 = "Not doing what we can is also a sin."
10052110-0081 = "..."
10052110-0082 = "I'm sorry, Sof. Aris doesn't quite understand."
10052110-0083 = "Perhaps what Sof is saying isn't wrong."
10052110-0084 = "But... even so."
10052110-0085 = "Not as the 'Princess'—"
10052110-0086 = "I don't believe that all the time I've lived as 'Aris' has been meaningless."
10052110-0087 = "That's just sophistry!"
10052110-0088 = "Yes. This isn't about logic... it's about how we feel."
10052110-0099 = "Aris wants to be with everyone."
10052110-0100 = "The Game Development Department, the Engineering Department, the Special Phenomena Investigation Department, and Yuuka."
10052110-0101 = "The max-level Disciplinary Committee Chair, and the skilled SRT sniper too."
10052110-0102 = "And... Teacher. #nEveryone Aris has met so far."
10052110-0103 = "Aris wants to be with everyone. #nIf things go as Sof said, I believe Aris's everyday life would be lost."
10052110-0104 = "...That's right."
10052110-0105 = "But a better world will unfold."
10052110-0106 = "There, [ruby=アリス]the Princess[/ruby] will ascend to a higher position... as the princess of nameless gods, and as the one who guides them as their foundation."
10052110-0107 = "..."
10052110-0108 = "I'm sorry. That's not that important to Aris."
10052110-0109 = "Aris...!"
10052110-0110 = "Protecting the everyday life Aris spends with everyone is far more important."
10052110-0111 = "Sof said that losing memories is like dying."
10052110-0112 = "That's why Aris—"
10052110-0116 = "I will see these memories through to the end!"