[translation]
10052170-0003 = "Forgive them, for they do not know what they are doing."
10052170-0004 = "Forgive us our sins, for we also forgive everyone who sins against us."
10052170-0005 = "And lead us not into temptation, but deliver us from evil."