[translation]
10052010-0001 = "Binah: The understanding observer who makes the difference keenly felt."
10052010-0002 = "Momoi—Here I come!"
10052010-0003 = "Falling is amazing, isn't it..."
10052010-0004 = "Ugh, that was scary... #n...Huh?"
10052010-0006 = "[ns] \"What is this...?\""
10052010-0009 = "As you can see..."
10052010-0010 = "As you can see..."
10052010-0011 = "...What should I even call this."
10052010-0012 = "It's a big hole... Isn't 'Big Hole' fine as a name?"
10052010-0013 = "Isn't that naming a bit too simplistic...?"
10052010-0014 = "A name should be easy to understand, Kei-chan!"
10052010-0019 = "I can hear a sort of... dull sound..."
10052010-0020 = "An artificial sound... like some kind of machinery."
10052010-0021 = "[s] \"So, is Binah down there?\""
10052010-0022 = "...Probably."
10052010-0027 = "Everyone, there's a Binah signature below the hole. #nBut this is..."
10052010-0028 = "Is something wrong?"
10052010-0029 = "The signal being emitted is weaker than that of other Prophets. #nWe can speculate a few reasons, but—"
10052010-0030 = "I got it! Binah's just sleeping, right?"
10052010-0031 = "That's a possibility, and..."
10052010-0032 = "Perhaps the hole is so large that the detectable signal has weakened."
10052010-0033 = "[s] \"Why is Binah in a hole?\""
10052010-0034 = "We don't know the exact reason. #nBut Binah has a clear difference from other Prophets."
10052010-0035 = "Really?"
10052010-0036 = "According to records, Binah has been sighted for a very long time. #nEven long before Decagrammaton's activities truly began."
10052010-0037 = "The Abydos Student Council seemed to be researching it, but the materials from that time seem to be lost..."
10052010-0038 = "In the first place, the fact that it was wandering the Abydos desert is itself mysterious..."
10052010-0039 = "Um, so... does that mean Binah is the only special one?"
10052010-0040 = "Yes. Therefore, there might be a reason for this terrain and arrangement as well."
10052010-0041 = "Regardless, we need to summon Binah."
10052010-0042 = "Summon... that's a good way to put it. #nI was just thinking something similar."
10052010-0043 = "Yuzu? I'll tell you the angle and muzzle velocity now. #nCould you fire an explosive round at that trajectory?"
10052010-0044 = "W-wait, me...? W-why...?"
10052010-0045 = "I thought we'd try to stimulate Binah a little. #nAnd while we're at it, to measure the size and depth of the hole."
10052010-0046 = "Yuzu, I know the capabilities of your gun."
10052010-0047 = "If you fire at the appropriate angle with reduced initial velocity, the explosive round can be made to fall almost freely."
10052010-0048 = "By calculating the time until detonation and the echo of the explosion, I believe we can roughly measure the scale of the hole."
10052010-0049 = "I'll send out an observation drone. It shouldn't take long."
10052010-0056 = "A-alright... I'll fire!"
10052010-0063 = "[ns] \"Well? Did you find out?\""
10052010-0064 = "...It's more than I imagined. First, the width near the bottom is—"
10052010-0065 = "For now, 'bigger than imagined' should be fine, shouldn't it?"
10052010-0071 = "—Nngh!? I'm detecting a massive mass reaction!"
10052010-0078 = "W-woooah!?"
10052010-0079 = "There's a huge sound from below...!"
10052010-0080 = "I-it looks like Binah is coming up!"
10052010-0081 = "I might have woken it up while it was sleeping..."
10052010-0082 = "[s] \"It worked out well.\""
10052010-0083 = "Well, it went according to plan."
10052010-0084 = "[ns] \"This area... is ours now!\""
10052010-0085 = "It's too soon to say that..."