[translation]
10052030-0002 = "Wh-wh-wha... WHAAAAAT!!"
10052030-0003 = "Don't think you've won just yet!!"
10052030-0008 = "Well then, shall we head back?"
10052030-0009 = "...Yes."
10052030-0018 = "[ns] \"Himari! Rio! Are you two alright?\""
10052030-0019 = "Oh, Sensei. To think you'd be this worried. #n It seems my little exertion was worth it."
10052030-0020 = "There's no need to worry about me ♪"
10052030-0021 = "In fact, I think using this trick every time might be a good idea ♪"
10052030-0022 = "I have a feeling that's not a good idea..."
10052030-0023 = "[ns] \"That's right. Just like Rio said.\""
10052030-0024 = "Dejected."
10052030-0025 = "...Why are you acting so dejected on purpose?"
10052030-0026 = "Either way, I'm just glad you're both safe."
10052030-0027 = "Kei is worried about me too? #n Hehe, I'm already feeling better!"
10052030-0028 = "Never mind that! Honestly!"
10052030-0032 = "Chief, President. Can I have a moment? #n I think I found something like a core."
10052030-0037 = "This is... a core?"
10052030-0039 = "Kei, can you confirm it?"
10052030-0040 = "I'll try... #n Eimi, could you set it down on the ground?"
10052030-0041 = "Huh? Got it."
10052030-0045 = "..."
10052030-0046 = "Understanding... Observer... [ruby=JEHOVAH ELOHIM]Jehovah Elohim[/ruby]... #n Silence and Greed, Abundance and Sorrow..."
10052030-0047 = "...!"
10052030-0048 = "Confirmed. It is indeed Binah's core."
10052030-0049 = "You can tell without seeing the actual object?"
10052030-0050 = "Yes, I can now."
10052030-0051 = "...I see. #n The area around this hole is already under our control..."
10052030-0052 = "In addition, this is like a gateway to the Steel Continent's network. #n Something like this is manageable."
10052030-0053 = "And... there's something new I've learned about the Prophet's core."
10052030-0054 = "What is it?"
10052030-0055 = "First, let me recap what I told you before. #n The information held by the core can be installed into my body."
10052030-0056 = "That means I will inherit the network's higher authority and divine power... the status of each Sephiroth."
10052030-0057 = "And furthermore..."
10052030-0058 = "By incorporating and applying the Prophet's core, we might be able to enhance the transport ship itself."
10052030-0059 = "In what way...?"
10052030-0060 = "Well... if we incorporate Binah's core into the transport ship, the transport ship will be able to use some of Binah's abilities and output."
10052030-0061 = "It should be the same for the other Prophet's cores."
10052030-0066 = "You don't mean...!!"
10052030-0067 = "Just like I thought, Kei! A lifeform that utilizes the enemy's abilities!"
10052030-0068 = "No, to put it another way, it's like..."
10052030-0069 = "Please, at least use something else..."