[translation]
10052153-0008 = "Ah... Ugh... Ughhh..."
10052153-0009 = "Wh-what should I do...!?"
10052153-0012 = "President Rio! At this rate, Yuzu-chan will...!"
10052153-0013 = "Don't you have some kind of ultimate move!?"
10052153-0014 = "Ultimate move..."
10052153-0018 = "Yuzu! I'm going to release all of Neo Avant-garde-kun's limiters right now!#nAnd--"
10052153-0019 = "I'm installing your exclusive Battle Gear now!"