[translation]
10052055-0002 = "It somehow worked out..."
10052055-0003 = "..."
10052055-0004 = "[s] \"Is there something on your mind?\""
10052055-0005 = "It's not really something that's on my mind."
10052055-0006 = "...Besides, I don't have the luxury of worrying about anyone."
10052055-0007 = "But..."
10052055-0008 = "Teacher."
10052055-0009 = "[s] \"Yes?\""
10052055-0010 = "Why... does conflict arise?"
10052055-0011 = "[ns] \"Perhaps because each side has something they cannot yield.\" "
10052055-0012 = "Of course, I believe everyone has something they cannot yield."
10052055-0013 = "However... even when neither side knows what that is..."
10052055-0017 = "...Will life forms ever be able to reconcile?"
10052055-0018 = "[s] \"I want to believe so.\""
10052055-0019 = "You can't quite believe it yet, can you?"
10052055-0020 = "[s1] \"You could say that, but...\"\n[s2] \"Still, you know.\""