[translation]
10052095-0002 = "Kukumer, I confirm the silence."
10052095-0003 = "Still... sigh... #nIt's hot here... more than that time..."
10052095-0004 = "[s1] \"I'd like you to bear with your combat uniform for now. \"\n[s2] \"Because I don't want Eimi to be in danger. \"\""
10052095-0007 = "...Um, Eimi? #nI'm sorry... but I have a favor to ask..."
10052095-0008 = "Yeah? Sure. As long as it's not about staying here for a long time."
10052095-0009 = "Ah, um... the temperature and atmospheric pressure here are significantly different from other areas--"
10052095-0010 = "It seems it will take a little more time to extract the core's information..."
10052095-0016 = "[ns] \"Eimi!?\""
10052095-0017 = "I'm sorry..."
10052095-0018 = "No... Kei isn't at fault..."
10052095-0019 = "The fault lies with... this world..."
10052095-0020 = "You say things just like those children..."