[translation]
10052155-0007 = "N-No, that's a lie... This can't be happening...!"
10052155-0008 = "Why...? What should I do...?\nThe plan will be ruined at this rate...!"
10052155-0013 = "...Huh?"
10052155-0015 = "This signal—could it be!?"
10052155-0020 = "O-Oh, sorry to keep you waiting... It's alright now!"
10052155-0021 = "Big Sister is deploying!!!"
10052155-0028 = "Big Sister!!!!"
10052155-0029 = "I'm sorry. Ein, Sof, Ohr."
10052155-0030 = "From here on, leave it to me."
10052155-0044 = "Kyaaaaaaaaaah!?!?"
10052155-0045 = "Yuzu, emergency eject!"
10052155-0046 = "H-How!?!?"
10052155-0047 = "I'll do it from here!\nEmergency Ejection System—Activate!"
10052155-0049 = "Wh-What...!?"
10052155-0054 = "Kyaaaaaaaaaah!?!?"
10052155-0061 = "Neo Avant-garde-kun—destroyed!\nYuzu is...!?"
10052155-0062 = "It's alright, she ejected safely. Her parachute is open too."
10052155-0068 = "Uuuugh..."
10052155-0072 = "Yuzu!"
10052155-0073 = "Yuzu-chan!"
10052155-0075 = "Are you alright, Yuzu!?"
10052155-0081 = "Uuugh..."
10052155-0082 = "Yuzu! You did great!"
10052155-0086 = "Y-Yes...?"
10052155-0087 = "I-I'm glad if I could be of help to everyone. Hehe..."
10052155-0091 = "Rio-sama."
10052155-0092 = "What is it?"
10052155-0093 = "Next, please make me the pilot.\nI want to be petted by Sensei like Yuzu."
10052155-0094 = "Wh-What...?"
10052155-0096 = "Toki. We have other work to do, don't we?"
10052155-0102 = "Big Sister..."
10052155-0103 = "I'm sorry, Big Sister..."
10052155-0104 = "Because we were so powerless..."
10052155-0106 = "It's alright. Ein, Sof, Ohr."
10052155-0107 = "When my sisters suffer, I, their elder sister, will step forward."
10052155-0108 = "However, they don't seem like an easy opponent.\nWe can always revive the Prophet, but..."
10052155-0109 = "To do that, it seems we'll need to overcome them."
10052155-0111 = "Y-Yes!"
10052155-0112 = "To think we'd have to rely on Big Sister... I wish you didn't have to deploy, if possible..."
10052155-0113 = "It's alright. We can still get it back. For now, at least...!"
10052155-0115 = "To everyone I'm meeting for the first time—"
10052155-0116 = "The Princess, and the Key—"
10052155-0117 = "Allow me to formally introduce myself once again."
10052155-0118 = "I am a single will created under the banner.\nA pilgrim of the kingdom who reached the ends of the world—I am Malkuth."
10052155-0119 = "I-I'm Tendou Aris..."
10052155-0120 = "...I'm Kei. That's what I'm called here."
10052155-0121 = "...!"
10052155-0122 = "I'm Tendou Kei!"
10052155-0123 = "Huh!?!?"
10052155-0125 = "...?"
10052155-0127 = "Because Kei is family! I heard that all family members use the same surname!"
10052155-0128 = "Th-That's certainly true, but...!"
10052155-0129 = "Kei, is something wrong?\nCould it be... Aris, are you misunderstanding something?"
10052155-0130 = "No, it's not that...!"
10052155-0131 = "I-I was just wondering if... I was allowed to be called that..."
10052155-0132 = "Tendou... Kei..."
10052155-0133 = "Heh, heheh..."
10052155-0138 = "..."
10052155-0139 = "So, you chose that name after all."
10052155-0140 = "Aris. Kei."
10052155-0141 = "A-Ahem."
10052155-0142 = "That's right. Got a problem with it?"
10052155-0143 = "No. Free will always guides us."
10052155-0144 = "Even if it's merely a sophisticated illusion."
10052155-0146 = "B-Big Sister and... here, the Jehovah created from Netzach-chan's core..."
10052155-0147 = "The supreme Tzevaot!"
10052155-0148 = "As long as the Holy Land and Zohar's vessel remain!"
10052155-0150 = "Yes."
10052155-0151 = "We can always start everything over—"
10052155-0152 = "We can always rebuild everything."
10052155-0153 = "Therefore, I, the elder sister, will go forth here."
10052155-0157 = "Ein, Sof, Ohr, please hide yourselves for a while."
10052155-0159 = "Yes!!!"