[translation]
10052020-0001 = "JEHOVAH ELOHIM"
10052020-0002 = "Point Oscar, arrival. Well then... I'll begin."
10052020-0003 = "[s] \"Is there anything I can do to help?\""
10052020-0004 = "No, I'm fine. Leave it to me. #nFirst... using [ruby=Head-Mounted Display]this HMD[/ruby], I'll connect to the network in this area."
10052020-0009 = "I don't think mere visual information input/output would be enough... Ah, I see. #nThat suit is equipped with a device to amplify bio-currents, isn't it?"
10052020-0010 = "Yes. That's why, through the HMD, I can perceive the network in this area as a single conceptual space."
10052020-0011 = "All the data within it is visualized with 3D coordinates, and in an infinite space--"
10052020-0012 = "Argh! I get it! I get that I don't get it, so it's fine!"
10052020-0013 = "Huh? Huh...?"
10052020-0014 = "Make it easier to understand! Summarize it in three lines!"
10052020-0015 = "Yeah, I agree with my sister this time."
10052020-0016 = "Ah, of course, I understand that Chairman Rio is trying to explain it carefully. #nBut, we don't have much time right now..."
10052020-0017 = "(It was a perfectly good explanation for me...)"
10052020-0022 = "[ns] \"Again, is there anything we can do?\""
10052020-0023 = "Let's see... Until I return safely, could you handle the surrounding defense?"
10052020-0024 = "While I'm diving, I'll be defenseless."
10052020-0025 = "Kei, please provide support for me just in case."
10052020-0026 = "Alright Midori! Yuzu! Let's go on patrol!"
10052020-0033 = "I'm not sure what you mean by 'support'..."
10052020-0034 = "From what I can see, you only have one HMD prepared, right?"
10052020-0035 = "Yes. That's why--"
10052020-0036 = "In case of emergency, I want you to take over."
10052020-0037 = "What? What do you mean...?"
10052020-0041 = "...Are you thinking of something strange? #nAmplification of bio-currents... in case of emergency..."
10052020-0042 = "What if it fails...? #nWill the effects also be amplified and rebound onto Rio's body...?"
10052020-0043 = "Yes, that's correct."
10052020-0044 = "If it fails... my brain would be completely fried."
10052020-0045 = "Are you sane!? Give that to me. #nIn case of emergency, my body would probably sustain less damage than yours."
10052020-0047 = "[ns] \"I can't agree to something so dangerous.\""
10052020-0048 = "No, this is the right way. #nOf course, I can't deny the possibility of both of you failing."
10052020-0049 = "But... Kei is the last resort. #nAt least, you shouldn't be entrusted with it from the start."
10052020-0050 = "It's not like I'm approaching this with failure in mind."
10052020-0051 = "Besides, if it were truly dangerous and the success rate were low... #nHimari would have stopped me by any means necessary."
10052020-0053 = "Grrr, that's...!"
10052020-0054 = "[ns] \"...Will you promise me you'll definitely come back safely?\""
10052020-0055 = "Yes. I'll do my best."
10052020-0060 = "...If I sense anything abnormal, I will stop you by force."
10052020-0061 = "Understood."
10052020-0062 = "...Well then, I'm off."
10052020-0067 = "Ugh...!"
10052020-0068 = "(Dizziness... The sheer volume of information is overwhelming...)"
10052020-0069 = "(A feeling of floating... I might drift away, losing my sense of coordinates...)"
10052020-0070 = "(For now, I'll add a value for virtual gravity...)"
10052020-0077 = "With this... it's a little better, perhaps."
10052020-0078 = "(Still... what a tremendous sight.)"
10052020-0079 = "You've finally arrived. I've been waiting for ages, you know?"
10052020-0080 = "!? "
10052020-0083 = "Welcome, [ruby=Tsukatsuki]Tsukatsuki[/ruby] Rio."
10052020-0084 = "Ohr...!"
10052020-0085 = "You remembered my name? #nWell, it doesn't really matter. Because--"
10052020-0086 = "You're going to die here!"
10052020-0087 = "!!!"
10052020-0092 = "You're surprisingly good at escaping. In that case, how about this?"
10052020-0096 = "My feet...!?"
10052020-0097 = "Look, look, you'll keep falling forever, won't you?"
10052020-0101 = "You've constructed a terrain structure here based on gravity."
10052020-0102 = "Yes, it's just like you humans. It's natural for you."
10052020-0103 = "Grrr...!"
10052020-0104 = "However, we are not bound by such things."
10052020-0105 = "To quote Sof-- #nOur way of thinking is fundamentally different from yours, who are bound by gravity even in your souls."
10052020-0106 = "How about this?"
10052020-0110 = "Sideways... I'm being pulled!?"
10052020-0111 = "How does it feel to fall to the right? #nNow to the left! And on top of that... upwards!"
10052020-0117 = "Finally, with mercy... I'll let you fall downwards!"
10052020-0124 = "Grrr... Ugh...!"
10052020-0126 = "How disappointing. Shall we end this soon?"
10052020-0127 = "Neither you nor I have a physical form while we are here."
10052020-0128 = "To borrow Sof's words again-- we are like ghosts."
10052020-0129 = "Therefore, no matter how much you are injured here, it will not affect your actual body."
10052020-0131 = "Instead... it affects your very mind."
10052020-0132 = "Here's a quiz."
10052020-0134 = "If you were to [ruby=die here]die here[/ruby], what do you think would happen to your real body?"
10052020-0135 = "...Your brain would be completely fried by an electric shock exceeding the tolerance limit."
10052020-0136 = "You knew that. In that case, I'll give you a little credit."
10052020-0137 = "Well then..."
10052020-0138 = "..."
10052020-0142 = "Are... are you sure it's okay...? #nIf they meet that child, even those people--"
10052020-0143 = "They'll die...?"
10052020-0144 = "Yeah... I guess so."
10052020-0145 = "We hadn't hurt anyone yet, nor had we thought of it..."
10052020-0150 = "...Tch."
10052020-0151 = "Prepare yourself-- Rio Tsukitsuki!"
10052020-0163 = "I... I won't give up!"
10052020-0164 = "It's useless!"
10052020-0165 = "...! "
10052020-0166 = "For someone as open as you!"
10052020-0181 = "Ngh...!"
10052020-0186 = "What are you spacing out for?"
10052020-0191 = "Huh...?"
10052020-0192 = "Huh...?"
10052020-0193 = "Himari...!?"
10052020-0199 = "Fufu."
10052020-0201 = "As I thought, things turned out as I expected. #nYour super genius, sickly, beautiful hacker has come to save you."
10052020-0202 = "You... that motorcycle..."
10052020-0203 = "It's a wheelchair."
10052020-0204 = "No, no matter how you look at it..."
10052020-0205 = "It's a w-h-e-e-l-c-h-a-i-r."
10052020-0206 = "That's a motorcyc--"
10052020-0208 = "It's useless. I'm telling you it's a wheelchair."
10052020-0209 = "I'm primarily in charge of rear support. #nBut if necessary, I'll rush anywhere on my [ruby=wheelchair]wheelchair[/ruby]."
10052020-0210 = "This is truly the appearance of a versatile, combat-ready beautiful girl. #nMore importantly, this wheelchair has a hidden function--"
10052020-0211 = "..."
10052020-0212 = "Fufu, let's stop here. #nIt's most effective not to reveal secrets."
10052020-0213 = "A super genius, pure, sickly, beautiful girl rider... #nNo, a super genius, pure, wheelchair-bound beautiful girl is a mysterious being."
10052020-0214 = "...Did you say 'beautiful girl' twice just now?"
10052020-0215 = "Oh, Kei. You ask such unrefined questions."
10052020-0216 = "A single flower blooming above the clouds. #nShe's a lady as noble as fresh snow and as clear as pure water--"
10052020-0217 = "Does it matter how many times I describe her as a 'beautiful girl'?"
10052020-0218 = "Eimi... Help me..."
10052020-0222 = "So, what will you show me next? Little lady?"
10052020-0223 = "The super genius, sickly, beautiful girl and cyber fairy, [ruby=Akeboshi]Akeboshi[/ruby] Himari, has grasped all the previous patterns."
10052020-0224 = "An extra obstacle has appeared..."
10052020-0225 = "However, this is a space dominated by Ohr."
10052020-0226 = "The possibility of you winning is not even one in ten thousand!!!"
10052020-0231 = "(Indeed... he has a point.)"
10052020-0232 = "(But for now, I just need to buy time...!!!)"
10052020-0233 = "Oh, do you really think so? #nEven the attack just now wasn't that impressive?"
10052020-0234 = "You're full of confidence."
10052020-0235 = "In this space, I can do anything and become anything. #nDon't you understand yet?"
10052020-0236 = "So, Rio Tsukitsuki and Himari Akeboshi are both only capable of this much?"
10052020-0237 = "Well, it doesn't matter. This time, I'll make you fall diagonally."
10052020-0238 = "Himari, the gravity here is controlled by Ohr--!"
10052020-0242 = "...?"
10052020-0248 = "?"
10052020-0249 = "Fufufu."
10052020-0250 = "No reaction...? #nO-once more...!"
10052020-0257 = "Nothing is happening...?"
10052020-0258 = "Wh-what?! Why!?"
10052020-0259 = "Oh, you're surprised?"
10052020-0260 = "My signal isn't being input...!? "
10052020-0261 = "What did you do, Himari Akeboshi!!!"
10052020-0262 = "Fufufu."
10052020-0267 = "Manager, Chairman. Can you hear me?"
10052020-0268 = "As instructed--"
10052020-0269 = "--I destroyed everything."
10052020-0270 = "Good work. Perfect timing."
10052020-0271 = "That's good. Communication ends."
10052020-0275 = "..."
10052020-0276 = "......"
10052020-0277 = ".............."
10052020-0278 = "You destroyed everything... You don't mean the communication hub system!?"
10052020-0279 = "The most straightforward method of cracking..."
10052020-0280 = "This is why humans...!!!"
10052020-0281 = "...I'm sorry."
10052020-0282 = "Isn't it a little late for that?"
10052020-0283 = "But..."
10052020-0284 = "Now, we're on equal footing. #nI'll let you go this time?"
10052020-0285 = "Just you wait!!"