[translation]
1013505-1 = "Quest"
1013505-2 = "(I rushed over to Millennium)"
1013505-7 = "I caught you~!"
1013505-8 = "L-let go of me...!"
1013505-9 = "Kei-chan, do you not like us?"
1013505-10 = "That is a completely separate matter...!"
1013505-11 = "Ah, are you just embarrassed? You really are just a little different from Aris!"
1013505-12 = "(Why is it that Aris is just Aris and I, Kei-chan)"
1013505-16 = "[ns1] \"Hmm? I thought it was an emergency...\"\n[ns2] \"It's wonderful everyone's getting along so well!\""
1013505-19 = "Sensei! You're just in time!#nAs an instructor, you simple must save a student in --"
1013505-20 = "Ah, Sensei! Hello!"
1013505-21 = "Would Sensei like to join in?"
1013505-22 = "[s] \"I think I'll enjoy watching from the sidelines.\""
1013505-23 = "Excu-se me!?"
1013505-24 = "...."
1013505-26 = "I was an idiot for believing in this adult--!!"
1013505-29 = "By the way, Kei-chan. You're Aris's twin little sister, right?"
1013505-30 = "Eh? Ah, yes.... I guess that's how it is..."
1013505-31 = "But your hair is completely different you know? The colors are opposites..."
1013505-32 = "Now that you mention it!"
1013505-33 = "A... haha.... these things can happen ... I think..."
1013505-34 = "I see, I see.#nWell then ... I'd like to bequeath todays quest!"
1013505-35 = "This, again..."
1013505-36 = "Did you not want to do it...?"
1013505-37 = "Eh, that's not what I meant...!"
1013505-41 = "...."
1013505-42 = "I'm okay doing it..."
1013505-43 = "It's just, um, I'm not use to it... and it's a little embarrassing...."
1013505-45 = "Kyaaaa!"
1013505-47 = "I have a bad feeling --!"
1013505-49 = "Kei-chan, you're So~~ cute!!!"
1013505-54 = "[ns] \"Cute~~~!!!\""
1013505-55 = "Why are you joining in!!!"
1013505-56 = "*deep breaths* Fu...moving along.#nCould you take this to the lecture all in the building right over?"
1013505-57 = "Ah, okay... it's what you'd call a delivery Quest..."
1013505-58 = "Yep. And this time it's prepaid.#nHere you go, a necklace."
1013505-59 = "....!"
1013505-60 = "It's pretty."
1013505-61 = "It's plated with blue-ish chrome, and a jewel flecked with yellow. An accessory that's not too gaudy."
1013505-62 = "But are you okay giving me something so valuable?"
1013505-64 = "Don't worry about it! We at the New Materials Research Club just made it from some things we had lying around."
1013505-65 = "That gem is an artificial diamond, so it's just simple carbon."
1013505-67 = "I see... Recently, artificial ones have been better quality..."
1013505-69 = "Well then, thanks for the delivery!"
1013505-70 = "Come anytime you need a quest!"
1013505-72 = "No... I think I'm all good for today."
1013505-73 = "...Haa."
1013505-74 = "How long do you plan on keeping that up, Sensei?"
1013505-75 = "[s] \"Fufufu~\""
1013505-76 = "What is it."
1013505-77 = "[s] \"I think I just saw something good~\""
1013505-78 = "Why it always at this timing!!!"
1013505-81 = "I really can't... why is it always me--"
1013505-82 = "Wait. I already know what you're going to say.#nYou're just going to say that they care for me, or they're doting on me. Is that about right?"
1013505-83 = "Don't get depressed because I predicted you.#nYou *are* an a adult."
1013505-84 = "[s] \"How's school?\""
1013505-85 = "...."
1013505-86 = "Well, it's not bad."
1013505-87 = "[s] \"I see. I'm glad you like it.\""
1013505-88 = "Were you listening!? Don't just go and interpret what I say!"
1013505-89 = "Ha...."
1013505-90 = "Anyways, I'm in the middle of a quest, so don't bother me too much."
1013505-91 = "Hm....? I just said, I'm in the middle of a quest..."
1013505-92 = "...!!!!"
1013505-93 = "E, Errand! It's just an errand!"
1013505-94 = "Ah--! You're smiling again! What is wrong with you!"
1013505-95 = "[s] \"I haven't done anything yet!\""
1013505-96 = "Well, you're banned from future actions as well!"
1013505-97 = "[s] \"I demand freedom of expression!\""
1013505-98 = "Sensei is an exception!"
1013505-99 = "Ah, It's Kei. You look like you're having fun."
1013505-106 = "I am not!#nAnyways, this is perfect. My que- errand, was to deliver this."
1013505-107 = "Let's see here... Ah, the results of the experiment finally came."
1013505-108 = "Wouldn't it be more efficient just to send these over the internet?"
1013505-109 = "That would be difficult for these specifically."
1013505-110 = "Why would that be?"
1013505-111 = "It would be a bit of a security issue. These do happen to be confidential."
1013505-112 = "The internet's fatal flaws are the weakness of its security and the length of storage time!"
1013505-113 = "Indeed. It's why magnetic tapes are still in use."
1013505-114 = "Well, I do wish that a more reliable method would appear. But you have to use what you can."
1013505-115 = "Okay. In celebration of a completed quest, why do we go and celebrate at an arcade?"
1013505-116 = "U-umm....?"
1013505-117 = "Hm? You were having so much fun last time....?"
1013505-118 = "That was true last time, but....! No, um..."
1013505-119 = "[s] \"Ah, did you like games, Kei-chan?\""
1013505-120 = "She does! I think you'd be surprised if you watched, Sensei."
1013505-121 = "N-no...! Um, that was just....!"
1013505-122 = "Huh... then were you just hanging out with me out of obligation that time ...?"
1013505-123 = "N-no that's wrong!"
1013505-127 = "[ns] \"Fufu, why don't you be honest with yourself?\""
1013505-128 = "Y-you...."
1013505-130 = "YOU CHEEKY ADULT!!!"