[translation]
1013503-1 = "Welcome to Kivotos"
1013503-2 = "(I went to Milennium to check on Kei)"
1013503-3 = "(Kei gave a displeased look when she noticed me.)"
1013503-10 = "Then, let us start class."
1013503-11 = "Our class today is on \"Living Spaces and Society\"."
1013503-12 = "I will speak about cities, which are an undeniable part of those."
1013503-13 = "Um... then, ... Kei-san?"
1013503-14 = "Can you tell me what you know about \"cities\"?"
1013503-15 = "Eh? Me...?"
1013503-16 = "Yes, please enlighten us."
1013503-17 = "Uhm...."
1013503-18 = "Cities are ... a symbol of civilization, the furthest from the natural state of things."
1013503-19 = "The root of the word Civilization, Civil, shares an origin with the word City: Civitas."
1013503-20 = "If cities, places where many people gather and live, didn't exist."
1013503-21 = "The world would be in a much different state than it is now."
1013503-22 = "Humans are beings who use communal thinking to turn abstract thoughts into reality, after all."
1013503-23 = "(Eh?!...Huh?!)"
1013503-24 = "(Sh-she's right, but...)"
1013503-26 = "On the other hand, because cities are where many people gather, many problems arise."
1013503-27 = "Because multifaceted problems tangle together in a complicated manner, solving them is no easy task."
1013503-28 = "If I were to give an example, it would be where to tackle the issue of transportation methods."
1013503-29 = "(She just went and said the entire contents of today's class....!)"
1013503-30 = "(Oh no... what should I do....?)"
1013503-32 = "Um... Why did the topic change from vectors to quantum fields...?"
1013503-33 = "Because, it is trying to prove that the mass gap is greater than zero through mathematical methods."
1013503-34 = "It's not a matter of just calculating it. Because that's simple."
1013503-35 = "In actuality, this shows the limit of using mathematical structures using path integration formulations."
1013503-36 = "A,ahem...!"
1013503-37 = "I-it's a little early, but this ends today's class."
1013503-43 = "Amazing!"
1013503-44 = "She had an aura, but this transfer student really is something special!"
1013503-46 = "Eh...?"
1013503-47 = "Hey, your name is Kei-chan right?#nHow have you been studying up until now? If you have any tricks, please do tell!"
1013503-48 = "You were talking about the Yangâ€“Mills existence and mass gap problem right?#nOur school *was* made to solve the Millennium Problems after all!"
1013503-49 = "Ah ... Uh... Em... I...."
1013503-51 = "(Kei made eye contact)"
1013503-52 = "(She was mouthing some words at me)"
1013503-53 = "(Pl.ease.sa.ve.me.!)"
1013503-55 = "(I of course chose to mouth back my response)"
1013503-57 = "[ns] (Yo.'re.so.pop.u.lar!)"
1013503-59 = "(This time I really will kill Sensei and then myself!!)"
1013503-61 = "Uu...I'm exhausted...."
1013503-62 = "[s] \"Kei-chan, you're so smart!\""
1013503-63 = "Please, just shut up!"
1013503-64 = "Ha...."
1013503-65 = "This is a good opportunity, so I'm going to say this but....#nAs you may have guessed, I know about most anything."
1013503-66 = "I needed to, back when I was still the \"attendant\""
1013503-67 = "When the Millennium Science School built a research facility in the ruins, I even tried a bunch of things."
1013503-68 = "So..."
1013503-69 = "What I wanted to say was, um...."
1013503-70 = "...."
1013503-71 = "I think these classes are nothing more than a formality."
1013503-72 = "[s] \"Do you hate going to class?\""
1013503-73 = "..."
1013503-74 = "Before even asking that, I just have a question."
1013503-75 = "Is there any point for a student who knows everything to go to school?"
1013503-76 = "[s] \"There certainly is.\""
1013503-77 = "That is?"
1013503-78 = "[s] \"Because it's fun playing with everyone.\""
1013503-79 = "Pardon me?"
1013503-80 = "That's it?"
1013503-81 = "[s1] \"Of course.\"\n[s2] \"Because a student's job is to learn and to play!\""
1013503-84 = "You're just making stuff up..."
1013503-85 = "...."
1013503-86 = "And I believe that there are people who get tired being around others."
1013503-87 = "[s3] \"You're right.\"\n[s4] \"But I believe even those people\"\n[s5] \"Sometimes feel a little lonely.\""
1013503-91 = "... So they should go to school just for those times?"
1013503-92 = "... U.."
1013503-93 = "But what if they're the grumpy kind of person whose picky with their friends?"
1013503-94 = "That's why Sensei's here...?"
1013503-95 = "....."
1013503-96 = "I get what you're saying, but you should really realize."
1013503-97 = "There's only one of you. Do you know how many students are in Kivotos?"
1013503-98 = "Just dealing with Millennium students would be hard enough. Where does this self-confidence come from...?"
1013503-99 = "[s6] \"You're certainly right. So Kei-chan--\"\n[s7] \"You should become friends with them in my stead!\""
1013503-102 = "Why me?"
1013503-103 = "Eh? The Hero Aris would have done it...?"
1013503-104 = "...."
1013503-105 = "......"
1013503-106 = "........"
1013503-107 = "Ha... You really are..."
1013503-108 = "nothing more than a smooth talker."
1013503-109 = "I got it."
1013503-110 = "I'll think about it. For now."
1013503-111 = "[s] \"You're such a good girl, Kei-chan!\""
1013503-112 = "I never said I would do it!!"