[translation]
1013502-1 = "Stress Relief"
1013502-3 = "...."
1013502-4 = "[s] \".....\""
1013502-5 = ".... Why are you staring at me like that?"
1013502-6 = "Is there something on my face?#nNo, that can't be it. I looked in the mirror."
1013502-7 = "[s] \"No... How should I say this....\""
1013502-8 = "?"
1013502-9 = "[s] \"I was just thinking that it really did work out well.\""
1013502-10 = "... I suppose that's true."
1013502-11 = "[s] \"Also that... Kei-chan really is cute....\""
1013502-12 = "Why are we suddenly bringing this up now?!"
1013502-13 = "[s] \"Did you maybe prefer your older body?\""
1013502-14 = "That is *not* the case!"
1013502-15 = "Eh? Then you think I'm I not happy that I'm cute?"
1013502-16 = "....."
1013502-17 = "......."
1013502-18 = ".........."
1013502-19 = "It's not like .... I hate it."
1013502-20 = "[s] \"You don't like it?\""
1013502-21 = "Th-thats...."
1013502-22 = "...."
1013502-23 = ".... I ...."
1013502-24 = "I like it! Only if you forced me to choose, I might add though!"
1013502-25 = "[s] \"Fufu\""
1013502-26 = "What...?"
1013502-27 = "[s] \"It's cute that you can't be honest.\""
1013502-28 = "You~~!!!!!!!"
1013502-30 = "It seems like this body was made with performance on the front lines in mind but...."
1013502-31 = "Given that, it sure is stiff."
1013502-32 = "I should just use WE-40 on the joints? What are you saying!#nWhat are you saying!"
1013502-33 = "That's a lubricant, or rather used for cleaning!#nAnd that's different from what it was originally used for!!"
1013502-34 = "And the stiffness was just a metaphor!!"
1013502-35 = "[s] \"Sorry, sorry....\""
1013502-36 = "... that being said."
1013502-37 = "It's like I'm using something left on the ground.#nI should be happy that it just moves."
1013502-38 = "No, it's not like I'm annoyed or anything."
1013502-39 = "Actually, I should be thankful for the situation."
1013502-40 = "And life never goes the way you want it to.#nIsn't just having half of it go well is on the better side?"
1013502-41 = "So, if there's still something left to burn, then I think you should burn it to ashes."
1013502-42 = "Until those flames reach something in the unseen beyond."
1013502-43 = "In any case, this body was fated to be discarded."
1013502-44 = "I'm the one saying this, but it just makes me depressed."
1013502-45 = "[s] \"Are you sure you don't want your old body....?\""
1013502-46 = "Over! My! Dead! Body!!!"
1013502-47 = "Geez.... can't even say a single joke here...."
1013502-48 = "And this body is built in a much more delicate way than it looks."
1013502-49 = "It may feel different seeing it from a third person point of view...."
1013502-50 = "So .... what I want to say is...."
1013502-51 = "[s] \"Everyone thinks you're precious, you know.\""
1013502-52 = "I, I know that!#nThat's not what I wanted to say!"
1013502-53 = "Um... what I mean is...."
1013502-54 = "A ribbon, or..."
1013502-55 = "Something to tie my hair would be nice....."
1013502-56 = "[s] \"Ribbon?\""
1013502-57 = "...!!"
1013502-58 = "You know what? Forget about it! Pretend you didn't hear it!#nNo, you actually didn't hear anything!"
1013502-59 = "Wh-why are you smirking! I'm gonna get angry for real, you know !?"
1013502-60 = "Eh? You'll ask Rio...?"
1013502-61 = "Why, Rio...?"
1013502-62 = "...."
1013502-63 = "...!!"
1013502-64 = "This is on purpose, right!?"
1013502-65 = "[s1] \"Perish the thought! Rio seems like she'd know about these things.....\"\n[s2] \"I'm truly thinking about you when I'm saying this!\""
1013502-70 = "THIS IS EXACTLY WHAT I HATE ABOUT YOU!!!"