[translation]
1013508-1 = "On living Conditions"
1013508-3 = "Ah, you came?"
1013508-4 = "Is this .... really a place where humans live?"
1013508-5 = "[s] \"Let me help.\""
1013508-6 = "Eh?"
1013508-7 = "Ah... okay. Thank you very much. It would be faster with 2 people after all."
1013508-12 = "Haa... Momoi just makes a mess all the time. And of course she never cleans."
1013508-13 = "On the other hand, Midori is good at cleaning and has a modicum of life upkeep skills but..."
1013508-14 = "She doesn't clean nearly enough...."
1013508-15 = "And Yuzu... She's starting to get over her hiding habit, but all she does is coding all day..."
1013508-19 = "Aris .... I'm worried about her."
1013508-20 = "She has the 2nd most ability to keep herself alive, but humans are beings who reflect their surroundings...#nand the people around her...."
1013508-21 = "No, I'm not saying they're bad people.#nIn fact, I think they're on the good side, but normally I--"
1013508-30 = "Fu... It's finally gotten a little better."
1013508-31 = "This won't last more than 3 days though. I would bet on it."
1013508-32 = "[s] \"After all that, 3 days... I see....\""
1013508-33 = "Yes."
1013508-34 = "...."
1013508-35 = "....?"
1013508-36 = "Wait a moment, Sensei."
1013508-37 = "[s] \"W-what's the matter?\""
1013508-38 = "Did you just break eye contact there?"
1013508-39 = "[s] \"K-kei-sama, this is a misunderstanding.\""
1013508-40 = "Kei-sama...?"
1013508-41 = "...."
1013508-42 = "Sensei."
1013508-43 = "Look me in the eyes."
1013508-44 = "[s] \"I-I refuse! I won't bend to tyranny!\""
1013508-45 = "Just look at me in the eyes for heaven's sake!"
1013508-46 = "[s] \"Guuu...!\""
1013508-47 = "Very good. Then put your hand over your heart and answer."
1013508-48 = "You do normally clean, right?"
1013508-49 = "[s] \"....!\""
1013508-54 = "Ha!? Wait a moment, I already understand everything now! Hey! Don't run!"
1013508-58 = "..."
1013508-59 = "[s] \"...\""
1013508-60 = "Sensei."
1013508-61 = "[s] \"Uh, yeah?\""
1013508-62 = "Is this a residence? Or is it some sort of garbage mansion."
1013508-63 = "If you answer the first, then you have no morals. If you answer the latter then you're a failure of a human being."
1013508-64 = "I give you 10 seconds. Begin excuses."
1013508-65 = "[s1] \"Listen to me, Kei-chan! I can explain everything!\"\n[s2] \"Normally cleaning and chores are an endless task are they not?!\""
1013508-68 = "So?"
1013508-69 = "[s] \"Even if you clean today, tomorrow's burden will just come again!\""
1013508-70 = "Continue."
1013508-71 = "[s3] \"So, if you just do everything at once when you feel like it!\"\n[s4] \"It feels nice and is more logical, right!?\""
1013508-77 = "Are you not making excuses like a certain Realist dressed in black?"
1013508-78 = "Are you done with the excuses now?#nThen...."
1013508-84 = "Really, why do I always..."
1013508-90 = "It's better than Rio's room but... No, that really is setting the bar too low..."
1013508-94 = "Look at all this dust. If you live in such a place, it'll be bad for you health, you know?"
1013508-101 = "Fu..."
1013508-102 = "Now then, Sensei?"
1013508-103 = "[s] \"Yes....\""
1013508-104 = "Do you have anything so say?"
1013508-105 = "[s5] \"I'm terribly sorry. Truly I am in your debt.\"\n[s6] \"I have no excuses. I give my thanks.\""
1013508-108 = "As long as you learned your lesson."
1013508-109 = "If it gets messy again...."
1013508-113 = "..."
1013508-114 = "You ARE going make a mess again, aren't you."
1013508-115 = "Ha... Don't struggle by yourself and call me."
1013508-116 = "[s7] \"...!?\"\n[s8] \"You'll help...?\""
1013508-119 = "There's no way you'll do it by yourself anyways."
1013508-120 = "And it's faster with two isn't it?"
1013508-124 = "[ns] \"I knew it..... I knew it....!!\""
1013508-125 = "What is with the weird build up..."
1013508-126 = "Wait a second, that grin..."
1013508-127 = "If you say something weird, I really--!"
1013508-128 = "[ns9] \"Kei-chan is cute!\"\n[ns10] \"Kei-chan is cute!!\"\n[ns11] \"Kei-chan is cute!!!\""
1013508-132 = "AAAAHHHHHHHHHHHHHH!!!!!!!!!!"