[translation]
90002110-0001 = "Episode 11; Burnt Offering"
90002110-0003 = "This is...!"
90002110-0005 = "No way...!"
90002110-0007 = "!?"
90002110-0008 = "...?"
90002110-0009 = "Kei? Are you alright...?"
90002110-0010 = "(Wha...)"
90002110-0011 = "(Something is about to begin...? What in the world is this...?)"
90002110-0012 = "(The prophet's information within me...)"
90002110-0013 = "(As if it suddenly gained a will of its own...!)"
90002110-0016 = "No――!!!"
90002110-0017 = "...?"
90002110-0018 = "What is this...?"
90002110-0021 = "Sister!! Sister――!!!"
90002110-0022 = "Ah... it's no use anymore...!"
90002110-0023 = "We... our sister..."
90002110-0025 = "[log][FF6666]Here, the vessel is complete[-][/log]"
90002110-0027 = "[log][FF6666]Soon, the cup will be filled[-][/log]"
90002110-0030 = "Please, I beg you! Give us a little more time!"
90002110-0031 = "Our sister is the last Sephira!#nIf all paths are walked correctly――"
90002110-0032 = "Ten minutes... no, even one minute is fine..."
90002110-0033 = "We understand that wish. For we were created for that purpose.#nHowever..."
90002110-0040 = "[ns] \"What in the world is that...?\""
90002110-0041 = "It looks like a structure built for a ritual...#nPerhaps an altar?"
90002110-0042 = "Why is something like that...?#nAnd the Steel Continent..."
90002110-0044 = "This is..."
90002110-0045 = "I see. However, my body is..."
90002110-0046 = "No, perhaps precisely because of that?"
90002110-0047 = "...Ah."
90002110-0048 = "I am the last Sephira.#nThe Gate of the Supplicant――the foundation of the Tree of Life."
90002110-0049 = "Having traversed all paths, a creation destined to become □□□□."
90002110-0050 = "If this is the destined path――"
90002110-0052 = "No, no, no!!!"
90002110-0053 = "Ah, ahhh..."
90002110-0054 = "Ugh, ughh..."
90002110-0056 = "Ein, Sof, Ohr."
90002110-0057 = "Please do what must be done."
90002110-0058 = "!?"
90002110-0059 = "What must be done...?"
90002110-0060 = "Th-that is..."
90002110-0061 = "Please! I beg you!#nPlease... don't take our sister away!!"
90002110-0062 = "Ein!"
90002110-0063 = "Calm down!"
90002110-0069 = "If someone is destined to be sacrificed, I will take their place――!!!!"
90002110-0070 = "!?"
90002110-0071 = "Kei...?"
90002110-0082 = "Ein, Sof, Ohr, thank you.#n...However, that is impossible."
90002110-0083 = "Why is that?#nFor our sister, I would――!"
90002110-0084 = "Ein, remember."
90002110-0086 = "[log][FF6666]That is not possible[-][/log]"
90002110-0088 = "[log][FF6666]To you, mystery has not been granted[-][/log]"
90002110-0091 = "!!!!"
90002110-0092 = "Then, who created us this way...?"
90002110-0093 = "From the beginning, everything..."
90002110-0094 = "Ein, Sof, Ohr. Please think once more."
90002110-0095 = "Our purpose, the reason we are here."
90002110-0100 = "H-huh...!?"
90002110-0101 = "The Sword of Burnt Offering..."
90002110-0102 = "This moment... has finally arrived, hasn't it?"
90002110-0103 = "Please."
90002110-0104 = "To fulfill my duty――lend me your hand."
90002110-0106 = "..."
90002110-0107 = "U-uuugh, uuuughhh...!"
90002110-0108 = "Aaaaaaaaaaaaaaaaaaah――!!!"
90002110-0110 = "Ein, Sof, Ohr. Thank you.#n...I'm sorry."
90002110-0114 = "...Goodbye."
90002110-0116 = "..."
90002110-0117 = "............"
90002110-0118 = ".................."
90002110-0122 = "The first Stigma shall be etched here."
90002110-0123 = "This is that which shall become the 'Law'."
90002110-0128 = "The second Stigma shall be etched here."
90002110-0129 = "This is that which shall become the 'Proof'."
90002110-0134 = "The final Stigma shall be etched here."
90002110-0135 = "This is that which shall become the 'Covenant'."
90002110-0137 = "Let it be done according to your will."
90002110-0138 = "We shall rejoice in it."
90002110-0142 = "May your will be done on heaven and earth――"
90002110-0143 = "Here, your kingdom shall come."
90002110-0144 = "The vessel has been prepared."
90002110-0145 = "Soon, the cup will be filled."
90002110-0151 = "Next; That Which Vanished"