[translation]
90002170-0001 = "Episode 17; The Human Answer"
90002170-0003 = "[ns] \"That is not an answer.\""
90002170-0004 = "...What do you mean?"
90002170-0005 = "[s] \"It may be a human answer, but it is not a divine answer.\""
90002170-0009 = "[ns] \"That is not self-justification.\""
90002170-0010 = "...!"
90002170-0011 = "[ns] \"There is no need to eliminate our sorrow.\""
90002170-0013 = "[ns1] \"The past is the past.\"\n[ns2] \"There is no way to undo what has happened.\""
90002170-0016 = "But from now on, it will be different. I will rectify it."
90002170-0017 = "[s] \"You cannot do that.\""
90002170-0018 = "Why do you think so?"
90002170-0019 = "[s3] \"Because all of that is me.\"\n[s4] \"There is no way to understand others by eliminating sorrow.\""
90002170-0022 = "...!"
90002170-0023 = "[ns5] \"Above all, if I were to run away like that.\"\n[ns6] \"How could I face my students?\""
90002170-0028 = "...!"
90002170-0029 = "I see... So that's how it is..."
90002170-0030 = "..."
90002170-0031 = "...Ehehe."
90002170-0032 = "I'm envious."
90002170-0033 = "Yes...? Of what?"
90002170-0034 = "Th-that your teacher is such a person. Ehehe."
90002170-0035 = "...Hehe, please allow me to make a slight correction."
90002170-0036 = "About what?"
90002170-0041 = "It's *our* teacher."
90002170-0042 = "Yes, from now on."
90002170-0043 = "...!"
90002170-0045 = "...Even at this stage, still a student? Truly foolish."
90002170-0046 = "[s] \"Perhaps so.\""
90002170-0047 = "I thought you would make a slightly better choice."
90002170-0048 = "[s] \"Because I was nothing from the start.\""
90002170-0049 = "No one will blame you. For only you and I are here."
90002170-0050 = "Even if you avert your eyes from your own heart, no one will fault you for it."
90002170-0054 = "[ns] \"Perhaps that's one way to think about it.\""
90002170-0056 = "...Sensei is Aris's comrade."
90002170-0058 = "If it's natural for a teacher to help students, isn't it also natural for students to want to help their teacher?"
90002170-0060 = "Let's trust Momoi and Midori here."
90002170-0062 = "Therefore, surely from now on, while traversing that gap, they will stumble many times and rise again..."
90002170-0063 = "I believe they will find a path someday."
90002170-0077 = "[ns] \"Even so, it's still no good.\""
90002170-0079 = "[ns7] \"If Sensei ceases to be 'Sensei'.\"\n[ns8] \"Then students can no longer be 'students'.\""
90002170-0082 = "Even if there is no one to witness it?"
90002170-0085 = "[ns9] \"...That's right.\"\n[ns10] \"Because 'I' am watching myself.\""
90002170-0090 = "..."
90002170-0091 = "I see."
90002170-0092 = "As one who will become a god, I shall respect your choice."
90002170-0093 = "However, that does not imply acceptance."
90002170-0094 = "Return to your students. By your will, to your old world."
90002170-0098 = "[ns] \"...?\""
90002170-0099 = "You may use anything."
90002170-0100 = "The Shittim Chest, the Adult Card, and the power your students possess."
90002170-0101 = "However... if you and your students truly defy me—"
90002170-0102 = "Be aware that extinction awaits you."
90002170-0103 = "These are my words. The same applies to all of you present."
90002170-0104 = "Let those with ears hear. This is my wrath and my warning."
90002170-0111 = "Ugh!? We were found out...!?"
90002170-0112 = "M-more importantly... Huh!"
90002170-0113 = "Everyone! Sensei is descending!"
90002170-0116 = "(With my body still floating in the air, I was slowly lowered to the ground.)"
90002170-0117 = "(Depending on how one looks at it, it might appear as divine authority, mercy, or grace...)"
90002170-0118 = "(What awaits beyond this is certainly not such a thing.)"
90002170-0122 = "Sensei!"
90002170-0123 = "Sensei, are you alright?"
90002170-0124 = "[s] \"I'm fine! More importantly, now...\""
90002170-0129 = "Oh..."
90002170-0130 = "Um..."
90002170-0131 = "H-hello... We meet again..."
90002170-0132 = "[USERNAME] Sensei."
90002170-0133 = "[s] \"...Yeah. Was everyone doing well?\""
90002170-0134 = "Y-yeah..."
90002170-0135 = "Isn't this not the time for such talk?"
90002170-0136 = "[s] \"You're right. First, we need to discuss this.\""
90002170-0138 = "(Focusing on the main points, I explained the situation to everyone.)"
90002170-0140 = "...I see."
90002170-0141 = "I understand. To borrow Momoi's expression—"
90002170-0142 = "It's finally time to fight the final boss, the Demon King, isn't it?"
90002170-0147 = "H-h-heee... If this were a game, we might still be able to manage..."
90002170-0148 = "Having come this far, we can't turn back now, can we?"
90002170-0149 = "It's alright, Sensei. We know a certain amount too."
90002170-0150 = "You ask how we knew? Well, it's like this—"
90002170-0151 = "W-wait! Isn't it better not to say that...?"
90002170-0152 = "Why?"
90002170-0156 = "Because that's what humans call 'eavesdropping', isn't it? That thing..."
90002170-0157 = "What about it?#nThere are even seniors who eavesdrop on Schale's office, you know?"
90002170-0163 = "...Are you really alright?"
90002170-0165 = "W-what should we do...?"
90002170-0166 = "[s] \"You all can rest; it's fine.\""
90002170-0167 = "B-but..."
90002170-0168 = "Don't worry about it. Your position is ambiguous, after all."
90002170-0169 = "If you wish to lend your strength, let's save it for another time."
90002170-0173 = "...Oh, I'm sorry. Disregard that."
90002170-0174 = "Y-yes...?"
90002170-0175 = "Please hide somewhere."
90002170-0176 = "Eh...?"
90002170-0178 = "Our magnificent 'God' has arrived."
90002170-0186 = "Ah, ah-wah-wah-wah...!"
90002170-0190 = "Now, quickly."
90002170-0191 = "A-alright, I understand...!"
90002170-0196 = "Sensei, Aris is ready."
90002170-0197 = "It's alright. Please don't apologize."
90002170-0198 = "Perhaps Aris... may have been named for this very moment, this very time."
90002170-0202 = "Please, Sensei! If we're going to do it, let's do it with spirit!"
90002170-0204 = "Sensei! We will do our best too!"
90002170-0205 = "Shittim Chest, process optimization complete.#n—Sensei, your orders."
90002170-0208 = "[ns] \"Alright, let's do it!\""
90002170-0218 = "Yes!!!"
90002170-0220 = "Next time; A Story for You"