[translation]
90002070-0001 = "Episode 6; Kei"
90002070-0002 = "Kei? Wake up, Kei!#nI don't want this... Please don't leave Aris alone!"
90002070-0003 = "Kei!!!!"
90002070-0008 = "...Aris."
90002070-0012 = "Kei!? Aris is here! Please...!"
90002070-0013 = "Excuse me, please calm down..."
90002070-0014 = "Huh...?"
90002070-0015 = "Haaah... I'm tired..."
90002070-0016 = "Are you... alright?"
90002070-0017 = "It's fine. Only various parts of my body are broken."
90002070-0020 = "I'll examine her. Aris, a moment please."
90002070-0021 = "Y-yes...!"
90002070-0024 = "There are no abnormalities in Kei's consciousness... or life signs."
90002070-0025 = "Really!? Kei... I'm so relieved...!"
90002070-0026 = "However, Kei's body has almost reached its limit."
90002070-0027 = "W-what should we do about that...?"
90002070-0028 = "It's nothing difficult. It can be resolved by overhauling her body."
90002070-0029 = "It seems the problem is solely with the hardware."
90002070-0030 = "Th-that's good, Kei..."
90002070-0031 = "Wait a moment. So, you mean to maintain this body and continue using it?"
90002070-0032 = "That's the plan, but... is there a problem?"
90002070-0036 = "..."
90002070-0037 = "I have a suggestion..."
90002070-0038 = "Taking this opportunity, could you change me into another body?"
90002070-0039 = "That said, a suitable chassis..."
90002070-0040 = "There is one! Right there!"
90002070-0041 = "There...?"
90002070-0043 = "You mean the one here?"
90002070-0044 = "But this one was made by Decagrammaton, right...?"
90002070-0045 = "After analysis, it should have been determined to be fine."
90002070-0046 = "That's not right. We only said there were no problems with its operation, didn't we?"
90002070-0047 = "That's right. We did say that if the consciousness circuit was transplanted, it could move immediately, but..."
90002070-0048 = "So! Use me!"
90002070-0049 = "I can't agree. We can't even predict what might happen. It's far too dangerous..."
90002070-0050 = "Above all, I'm not confident we can breach the security inside the chassis."
90002070-0051 = "I'll try that.#nAs I said earlier, I should be able to breach it if I have time."
90002070-0052 = "[s] \"I don't think we have much time left...\""
90002070-0053 = "Hmm... I can't say there's no possibility, but considering the risks, still--"
90002070-0057 = "Why are you giving up before even trying!?"
90002070-0058 = "You won't know unless you try, will you!?"
90002070-0059 = "Oh, it seems her usual self is back."
90002070-0060 = "This chassis, it's made from materials from the Steel Continent, isn't it?"
90002070-0061 = "If it goes well, there's even a chance we could find a clue!"
90002070-0062 = "But if it fails..."
90002070-0064 = "So, please don't just say negative things!"
90002070-0065 = "First, let's try it! If that doesn't work, we can think about it then!"
90002070-0066 = "Somehow, aren't you more emotional than usual...?"
90002070-0067 = "Transferring consciousness itself has already been successful.#nAfter all, I was originally inside a keychain, you know?"
90002070-0073 = "Yes! Aris still has it as a memento!"
90002070-0074 = "Ah, yes. Thank you.#nAnyway, what I want to say is--"
90002070-0075 = "Since it succeeded last time, it will be fine this time too!"
90002070-0076 = "I don't know how many times I've said this, but...#nIf it doesn't work, we can think about it then, right!?"
90002070-0077 = "Could it be... you dislike your current body that much...?"
90002070-0078 = "If you won't listen to me--"
90002070-0079 = "I won't move another inch!!!"
90002070-0088 = "Kei!?"
90002070-0089 = "Ugh... I got too excited and my body..."
90002070-0091 = "[ns] \"...Why don't we try doing as Kei says?\""
90002070-0092 = "But..."
90002070-0093 = "Huh? Is it impossible, you ask?#nI don't think so... but still... there are risks involved."
90002070-0094 = "If possible, I don't want to add any more variables."
90002070-0095 = "[s] \"If it succeeds, I think there's something to gain, too?\""
90002070-0096 = "It's a hopeful observation, but... in any case, it's highly probable that chassis was made by Decagrammaton's engineers."
90002070-0097 = "Furthermore, the security system is almost certainly related to Kei.#nIf we can analyze it, it will surely be a big clue."
90002070-0098 = "By connecting an additional auxiliary storage device, it's also possible to prepare for failure."
90002070-0099 = "Preserving Kei's consciousness is not considered a major risk, but..."
90002070-0100 = "What I'm concerned about is a significant loss of time."
90002070-0101 = "The time to transfer consciousness to the new chassis, and the time to analyze the security--"
90002070-0102 = "When there's no time to spare, that might be wasted."
90002070-0103 = "[s] \"...\""
90002070-0107 = "[ns] \"Even so, let's try it!\""
90002070-0108 = "Sensei, are you serious!?"
90002070-0109 = "No, I understand what you're trying to say.#nThe return on success is great, and even if we fail, we won't lose Kei. But..."
90002070-0110 = "There are simply too many variables..."
90002070-0111 = "Huh...? You want to grant her wish...?#nSensei, you really are something..."
90002070-0112 = "..."
90002070-0116 = "Alright..."
90002070-0117 = "Since Sensei says so much, it can't be helped.#nAnd it's also a request from a cute junior."
90002070-0118 = "Kei, you did it! Everyone will lend their strength!"
90002070-0119 = "Hehe, hehehe... As expected, if you plead desperately...#nit gets through, doesn't it..."
90002070-0120 = "Oh, I see! Then I'll try it on Yuuka next time!"
90002070-0121 = "I don't think that'll work..."
90002070-0123 = "We'll input simultaneously on three. One, two--"
90002070-0124 = "--Three!"
90002070-0131 = "...Kei?"
90002070-0132 = "Me too! I want to see too!#nOhh...!"
90002070-0136 = "Normal operation of the chassis has been confirmed. Now, all that's left is..."
90002070-0137 = "Kei. Do you recognize us?"
90002070-0140 = "[ns] \"...Kei?\""
90002070-0143 = "...Sensei?"
90002070-0144 = "Aris?"
90002070-0146 = "Kei!!!"
90002070-0152 = "As expected of Kei! Aris, I believed in you!"
90002070-0153 = "...I told you. It would be fine. Everyone is being too dramatic..."
90002070-0154 = "[s] \"It was that important, you know.\""
90002070-0155 = "If everyone had been calm, it might have been lonely in its own way, you know?"
90002070-0156 = "It can't be helped. I'll try to act calm, at least."
90002070-0157 = "No, that's quite alright..."
90002070-0159 = "Um... Allow me to reintroduce myself, I am Kei."
90002070-0160 = "I'm Kei!"
90002070-0161 = "Ohh, now she finally looks like a beautiful girl android!"
90002070-0162 = "Yeah. I think it's a good design."
90002070-0163 = "Th-that's good... Kei."
90002070-0164 = "(I thought the previous design wasn't bad either, though...)"
90002070-0169 = "...I can walk on two legs, and my throat isn't a speaker."
90002070-0170 = "Hair, hands, even fingers..."
90002070-0174 = "...U-ugh."
90002070-0175 = "Congratulations, Kei.#nI apologize for dampening the mood, but... have you learned anything?"
90002070-0176 = "Even if there was nothing, Kei is happy, and I think that's enough."
90002070-0180 = "After throwing such a tantrum, if there was nothing, I wouldn't be able to face anyone, would I?"
90002070-0181 = "Fortunately, I have a lot to talk about."
90002070-0182 = "For now, let's return to the transport ship."
90002070-0184 = "Next; Possibility"