[translation]
90002020-0001 = "Episode 2; The Winds of Change Are Stirring"
90002020-0003 = "Good morning, everyone. #nThis is Toki Asuma, your captain."
90002020-0004 = "We are currently flying at an altitude of 8,000 meters, and no issues are anticipated along our flight path."
90002020-0005 = "We will soon be arriving at our destination, the Steel Continent. #nPlease fasten your seatbelts in preparation for any unexpected turbulence."
90002020-0006 = "For your safety, please return your tables to their original upright position."
90002020-0007 = "Huh? There aren't any tables, are there?"
90002020-0008 = "Right. I was just saying."
90002020-0009 = "Hehe. Captain Toki, you're surprisingly playful."
90002020-0010 = "Then allow me to introduce myself—#nI'm Himari Akeboshi, in charge of operations and flight assistance♪"
90002020-0011 = "At this time, we anticipate an on-schedule arrival."
90002020-0012 = "Well, this is a journey through the sky... Everyone, how does it compare to *that* time?"
90002020-0018 = "Back then, we were too high up, so it didn't feel real..."
90002020-0019 = "N-Now, I really feel like I'm flying through the sky, ehehe..."
90002020-0021 = "Hey, President. #nI'm sitting in the co-pilot's seat as instructed, but was all this really necessary?"
90002020-0022 = "Isn't it a bit inefficient?"
90002020-0023 = "No, this is more rational."
90002020-0024 = "As the number of personnel increases, so do the things we need to be mindful of. #nTherefore, it was necessary to reduce Toki's burden."
90002020-0025 = "As a perfect maid, I believe there would have been no issues even if I were alone."
90002020-0026 = "We must consider all contingencies. #nWe need to be prepared for every variable."
90002020-0027 = "If you insist, Rio-sama."
90002020-0029 = "Even so, this transport ship... it's truly amazing!"
90002020-0031 = "Th-This is my first time properly seeing the inside of the ship too..."
90002020-0032 = "Hmm, I wish we had explored it more while we had the chance."
90002020-0033 = "It couldn't be helped, given the circumstances."
90002020-0039 = "For now, let's just recall our memories. #nRight outside the cockpit was the lobby, wasn't it?"
90002020-0043 = "Honestly, it was cleaner than my room..."
90002020-0044 = "...How messy is your room? Please clean it properly."
90002020-0045 = "Yes... I've been reminded again how important cleaning is."
90002020-0046 = "Pfft!?"
90002020-0047 = "Are *you* really saying that...?"
90002020-0050 = "The most vulnerable and most important space on the transport ship is the hangar."
90002020-0051 = "Yes. There's a hatch leading outside, and also descent pods."
90002020-0052 = "All the AMAS we brought are in the hangar, right? #nSpeaking of which, I think I saw something... conical?"
90002020-0053 = "That is..."
90002020-0054 = "...You don't need to worry about it."
90002020-0055 = "Hmm?"
90002020-0056 = "I was surprised that I could barely hear the engine noise in the hangar."
90002020-0057 = "Yes... I-It's quiet enough that I feel like I could safely hide there in an emergency..."
90002020-0058 = "It's the most dangerous place in an emergency, so please don't do that...?"
90002020-0065 = "[ns1] \"It's still amazing, but...\"\n[ns2] \"How did you prepare all this?\""
90002020-0068 = "It's nothing special. We merely applied the technology Millennium has cultivated."
90002020-0069 = "Researching and realizing concepts that can be imagined... is not that difficult."
90002020-0070 = "The problem arises when researching fields that cannot even be imagined."
90002020-0071 = "Yes. The ability to imagine something is, in itself, proof that a clue is visible."
90002020-0072 = "The despair when suddenly confronted with facts beyond imagination..."
90002020-0073 = "[s] \"Did something like that happen?\""
90002020-0074 = "It happens sometimes when you're doing research."
90002020-0075 = "Gravity is a good example. #nWe all live bound by gravity, but the graviton, which can be called its source—"
90002020-0076 = "Stooop! Suddenly launching into technical explanations is a bad habit of President Rio! #nYou'll be disliked by everyone if you keep doing that!"
90002020-0077 = "I-Is that so...?"
90002020-0078 = "But... I'm already used to being disliked..."
90002020-0080 = "That's not quite the right response here..."
90002020-0085 = "...Let's change the subject. #nToki, what's the flight status?"
90002020-0087 = "There are no abnormalities on the flight path. The signal from the Steel Continent is growing stronger and stronger."
90002020-0088 = "If anything, the signal might be too strong. It might be difficult to determine a landing spot."
90002020-0090 = "Can't we just land anywhere?"
90002020-0092 = "That's not an option. #nIf we were to head towards a location with an established air defense system, it would be the end for us."
90002020-0093 = "This transport ship prioritizes 'transport' and 'research.' #nAs a result, its defensive capabilities are a bit lower."
90002020-0095 = "Furthermore, given that our opponent is the Steel Continent... in other words, the 7th Prophet, 'Netzach'—"
90002020-0096 = "It's highly likely that our common sense won't apply."
90002020-0097 = "Exactly. In fact, it's already becoming difficult to even determine our flight altitude."
90002020-0099 = "We are currently flying concealed within the clouds, attempting to disrupt visible light, infrared, and radar."
90002020-0100 = "...Though it's also difficult for us to visually confirm the Steel Continent with our naked eyes."
90002020-0102 = "Can we not actively detect Netzach?"
90002020-0104 = "To do that, we would need to emit radio waves from our side. #nWe would likely be reverse-detected immediately."
90002020-0105 = "Also, the signal being too strong is causing another problem."
90002020-0106 = "No matter what signal we detect, it all converges into one. #nTo the point where there's no longer any meaning in analyzing it."
90002020-0107 = "[s] \"So... what should we do?\""
90002020-0108 = "..."
90002020-0110 = "..."
90002020-0111 = "We have no choice but to proceed as we are."
90002020-0112 = "You could phrase that a little better..."
90002020-0113 = "Is there a problem?"
90002020-0114 = "...No."
90002020-0115 = "In any case, we will be arriving shortly."
90002020-0121 = "We will now begin our descent—"
90002020-0133 = "Kyaaah!?"
90002020-0134 = "Toki, what's happening!?"
90002020-0135 = "Emergency! I've detected a massive... signature!"
90002020-0136 = "Is that... a mechanical arm?"
90002020-0137 = "Signal analysis complete—it's the 9th Prophet, 'Yesod'!"
90002020-0139 = "Yesod!?"
90002020-0145 = "Whoaah!?"
90002020-0146 = "Waaah!?"
90002020-0152 = "Ah-wah-wah-wah...!"
90002020-0153 = "Wh-What is thattt!!"
90002020-0154 = "H-Heeek...!"
90002020-0156 = "Everyone, grab onto something, anything! #nEimi! What's the damage report?"
90002020-0159 = "Engine damage. But the main engine is maintaining output. #nThe sub-engines might be beyond repair..."
90002020-0160 = "Engine fire detected! Activating fire suppression system!"
90002020-0165 = "Unable to maintain altitude and aircraft balance... President! At this rate—!"
90002020-0166 = "We're going to crash!"
90002020-0171 = "What's the fire status!?"
90002020-0172 = "Engine fire extinguished! However, the aircraft's outer hull is still burning!"
90002020-0173 = "Reverse thrust the engines to critical point!"
90002020-0177 = "Reverse thrust the engines to critical point! #nActivating emergency landing sequence! Brace for impact—!"
90002020-0191 = "[ns] \"Is everyone okay!?\""
90002020-0192 = "Ow, ow, ow... My head's spinning..."
90002020-0193 = "Seatbelts really are important, aren't they..."
90002020-0194 = "I've never resented having only one wheel so much..."
90002020-0195 = "M-More importantly... where are we...? #nIt doesn't look like the Steel Continent we heard about in the explanation..."
90002020-0196 = "The edge of the Steel Continent... It seems to be a barely remaining piece of land."
90002020-0197 = "We were attacked by Yesod's giant arm—"
90002020-0199 = "And as a result, we made an emergency landing here."
90002020-0212 = "A-Again!?"
90002020-0213 = "Multiple hostile signatures on radar! #nToki, connect to the external cameras!"
90002020-0214 = "Displaying."
90002020-0229 = "Those are... the same individuals that attacked us at the Seed Vault."
90002020-0230 = "We're surrounded. At this rate...!"
90002020-0231 = "It's alright, Rio-senpai! Aris will protect everyone here!"
90002020-0236 = "Ah, ah...!"
90002020-0237 = "Aris-chan!?"
90002020-0242 = "..."
90002020-0243 = "Game Development Department! Move out!"
90002020-0245 = "Big Sis!?"
90002020-0246 = "W-We are...?"
90002020-0248 = "That's right! We can't just leave it all to Aris, can we? #nSensei, we're going!"
90002020-0254 = "B-Big Sis! ...Me too!"
90002020-0255 = "One for all... all for one..."
90002020-0260 = "Everyone, wait!"
90002020-0261 = "[s] \"...\""
90002020-0263 = "[ns] \"Eimi, can I leave the Game Development Department to you?\""
90002020-0264 = "Me?"
90002020-0265 = "..."
90002020-0266 = "Yeah, leave it to me."
90002020-0272 = "[ns] \"Rio and Toki, please repair the transport ship as much as possible.\""
90002020-0273 = "Yes... Understood."
90002020-0274 = "Let's go, Rio-sama. We'll start with the engines."
90002020-0276 = "What should we do?"
90002020-0277 = "[s] \"Kei and Himari... please stand by for now.\""
90002020-0278 = "Oh, it's a bit lonely not to be relied upon..."
90002020-0279 = "No, I understand. Please leave the overall situation assessment to me."
90002020-0287 = "Ugh, this is endless!"
90002020-0288 = "But we can't back down here! To protect Sensei and everyone!"
90002020-0293 = "Everyone, let's fall back a bit. Momoi, follow me."
90002020-0297 = "Huh...?"
90002020-0298 = "That voice is... Eimi-san!"
90002020-0299 = "I'm here to help. #nLeave the front lines to Momoi and me."
90002020-0300 = "Aris, please provide fire support from the rear."
90002020-0301 = "Midori and Yuzu, I'd like you to fill the middle of the formation."
90002020-0302 = "Yes! We're counting on you, Eimi!"
90002020-0303 = "Alright. Let's do what we can."
90002020-0305 = "W-Will it be okay...?"
90002020-0313 = "Well."
90002020-0314 = "We can handle this much."