[translation]
90002045-0002 = "[ns] \"Alright!\""
90002045-0003 = "Yesod's signal has weakened to its limit!"
90002045-0004 = "[s] \"Did we do it!?\""
90002045-0008 = "Hey, don't say that line--!!"
90002045-0013 = "Whoa!?"
90002045-0014 = "Kyaa!?"
90002045-0016 = "Momoi, Midori, look over there."
90002045-0018 = "Ugh... my ears... Wait, over there?"
90002045-0019 = "The wall separating the Steel Continent...?"
90002045-0025 = "Yes, it's gone."
90002045-0026 = "..."
90002045-0027 = "Thank you, Sensei. You saved us."
90002045-0030 = "Yesod attack team, return immediately!"
90002045-0031 = "We are already initiating retrieval. Hangar, do you read?"
90002045-0035 = "Ta-da! Aris has returned safely! We took down the big wall!"
90002045-0036 = "Yes, well done."
90002045-0038 = "Hatch closure confirmed. We've also received confirmation from Eimi that she's safe. With this--"
90002045-0043 = "!?"
90002045-0044 = "Rio? What's wrong?"
90002045-0045 = "Look at the wall!"
90002045-0046 = "Yesod's wall is starting to regenerate!"
90002045-0047 = "!!!"
90002045-0052 = "What now!?"
90002045-0053 = "Huh...?\nThe wall is... starting to generate from the inside... At this rate...!"
90002045-0055 = "Run!"
90002045-0057 = "Again!?"
90002045-0058 = "Big sister, hurry! If the wall forms, we won't be able to get inside!"
90002045-0063 = "Pant, pant...!"
90002045-0064 = "Huff, huff...!"
90002045-0065 = "Jump!"
90002045-0074 = "Are you both okay?"
90002045-0080 = "Ow, ow, ow... Did we manage to get in?"
90002045-0084 = "Wow..."
90002045-0088 = "A-amazing..."
90002045-0089 = "It's like a dream..."
90002045-0095 = "Eimi Izumi Moto, reporting from the field."
90002045-0096 = "We have entered inside the Steel Continent's wall."
90002045-0098 = "Next time; Forward Operating Base"