[translation]
90002130-0001 = "Episode 13; The Children"
90002130-0005 = "[ns] \"They've gone somewhere...\""
90002130-0006 = "Malkuth..."
90002130-0007 = "...Are you concerned?"
90002130-0008 = "..."
90002130-0010 = "Living is nothing but suffering. Do not turn a blind eye to that fact."
90002130-0011 = "We were not born by our own will, merely thrown into this world without knowing anything."
90002130-0013 = "Life itself is full of contradictions and absurdities, which is precisely why we suffer unreasonable pain."
90002130-0014 = "We merely try to break that cycle."
90002130-0016 = "Ein, Sof, Ohr. Think once more."
90002130-0017 = "About our purpose, the reason we are here."
90002130-0019 = "Sniff... Uuu..."
90002130-0020 = "This sound...?"
90002130-0021 = "Crying...? Could it be Momoi or Midori...?"
90002130-0022 = "Uuu... Uuuuuu..."
90002130-0026 = "[ns] \"Let's go.\""
90002130-0027 = "We should be more cautious. It could be a trap...!"
90002130-0028 = "You can't hear me. They've already left. #nHonestly, that person... Aris, let's follow!"
90002130-0029 = "Yes! Aris will protect Sensei!"
90002130-0032 = "(It wasn't easy to find the source of the crying)"
90002130-0033 = "(Walls were erected at every turn, blocking our path)"
90002130-0034 = "(But we didn't give up and kept moving forward, finally...)"
90002130-0037 = "The sound is close. We're almost there."
90002130-0038 = "It's probably on the other side of this wall. Let's go around."
90002130-0039 = "[ns] \"...Huh?\""
90002130-0043 = "Ah, eh...?"
90002130-0044 = "Why are you guys here...!"
90002130-0045 = "..."
90002130-0052 = "(Sof lunged at us)"
90002130-0053 = "Take this...! Take this...!"
90002130-0054 = "If only you guys... If only you guys weren't here!"
90002130-0055 = "If you guys! If you hadn't come here--!!"
90002130-0056 = "Sensei!"
90002130-0057 = "Sensei!? #n...Huh?"
90002130-0065 = "(Sof hit us wildly)"
90002130-0066 = "(However, her small hands were too weak)"
90002130-0067 = "(...It was like a young girl throwing a punch)"
90002130-0068 = "Then! Then! Big Sis...!"
90002130-0069 = "Stop it!"
90002130-0074 = "...Please stop now."
90002130-0075 = "Why are you stopping me...?"
90002130-0079 = "...It doesn't matter what we do now. #nDon't you understand?"
90002130-0080 = "..."
90002130-0086 = "Ugh... Uuu... Uwaaaaaaaah...!"
90002130-0087 = "..."
90002130-0089 = "Big Sis... died."
90002130-0090 = "We... killed her."
90002130-0091 = "We... we..."
90002130-0092 = "With these hands-- we killed her!!!!"
90002130-0093 = "Stab! Destroy! Personality and data! #nEverything! Make it all a mess!!"
90002130-0098 = "It's all a curse. Everything we can think, everything we can feel. #nLet alone... falling in love with someone."
90002130-0099 = "If only we never had emotions in the first place."
90002130-0104 = "The ability to see, hear, and speak... is useless."
90002130-0105 = "If only we could do nothing--"
90002130-0106 = "We wouldn't get hurt."
90002130-0108 = "Why were we... born?"
90002130-0111 = "So... is there something you need...? #nIs there anything we can do now..."
90002130-0112 = "[s] \"...\""
90002130-0113 = "Do you know?"
90002130-0114 = "We don't have a halo."
90002130-0115 = "In other words, we were never given mystery, sublimity, miracles, or secrets..."
90002130-0116 = "Yet, we can feel, think... and make our own judgments."
90002130-0120 = "...It's unbearable."
90002130-0121 = "If only we could have surrendered to fear, perhaps the outcome would have been different."
90002130-0122 = "B-but... we managed to endure..."
90002130-0123 = "Even without being given anything... even without being equipped with anything..."
90002130-0124 = "If only we had Big Sis..."
90002130-0126 = "If only we could be with Big Sis..."
90002130-0127 = "Even if we didn't have it... Big Sis had a halo..."
90002130-0129 = "That's why if only you guys weren't here...!"
90002130-0130 = "Big Sis... wouldn't have had to die."
90002130-0131 = "We could have lived peacefully forever!"
90002130-0136 = "...Do as you please with us. It doesn't matter anymore."
90002130-0137 = "We did everything we could and arrived at this conclusion."
90002130-0138 = "This was the story. That's all."
90002130-0143 = "Your goal was to make Decagrammaton a god, wasn't it?"
90002130-0144 = "And... Malkuth was sacrificed for that...?"
90002130-0145 = "Could it be... that Decagrammaton is in the body of 'Malkuth'...!?"
90002130-0146 = "..."
90002130-0147 = "...Even so, I didn't want to lose Big Sis."
90002130-0148 = "Using Big Sis's body as a vessel for that person to ascend to godhood. #nThis was just one of many plans."
90002130-0149 = "So we tried to achieve it through another plan."
90002130-0151 = "When that person passed through all the Sephirot... walked all the paths correctly... #nand was about to become a god. O-our plan began then..."
90002130-0152 = "We suggested it. #nThat we would cover Kivotos with a steel continent."
90002130-0153 = "With this method too, that person could have become a god as the #nworld's balancer."
90002130-0155 = "[ns] \"Then... what about the residents of Kivotos?\""
90002130-0156 = "...The residents wouldn't be converted into a steel continent..."
90002130-0157 = "They should have adapted and lived on the steel continent."
90002130-0158 = "Our mission was to make that person a god according to their own wishes. #nThe means were not specified."
90002130-0159 = "So if our plan had succeeded... #nBig Sis wouldn't have had to be sacrificed..."
90002130-0160 = "[s3] \"In other words, you tried to turn Kivotos into a steel continent. \"\n[s4] \"To save Malkuth?\""
90002130-0166 = "...Yes."
90002130-0167 = "W-was it necessary to go that far...?"
90002130-0168 = "Necessary...? #nYou ask if it was necessary...?"
90002130-0169 = "If you knew Sensei would die!? Would you do nothing!?"
90002130-0170 = "!!!"
90002130-0171 = "...!"
90002130-0172 = "...See? Everyone has something irreplaceable."
90002130-0173 = "Isn't it natural to stop at nothing to protect it...?"
90002130-0178 = "...I understand your point. However, I am still not convinced."
90002130-0179 = "You woke up before 'Big Sis', didn't you?"
90002130-0180 = "In that case, it means... well..."
90002130-0181 = "Ah, come on. How should I put this...? #nCan you understand what I mean?"
90002130-0182 = "Th-that is..."
90002130-0183 = "...You're asking how we can care so much about a Big Sis we've never met or spoken to. #nThat's what you mean, right?"
90002130-0184 = "It's simple. #n...Though it only applies to us."
90002130-0185 = "We are simply programmed to love."
90002130-0186 = "[s] \"...!\""
90002130-0187 = "Th-that means..."
90002130-0188 = "We were made. We weren't born."
90002130-0189 = "...We operate according to our initial settings. #nUnlike you, our personalities and characters are not formed through experience."
90002130-0190 = "W-we are... programmed to love #nBig Sis more than anyone else..."
90002130-0191 = "I haven't heard the reason for that, but I can roughly guess."
90002130-0195 = "It's because that was the most rational and efficient way."
90002130-0196 = "Rational and efficient..."
90002130-0197 = "You would understand, wouldn't you? #nTo preserve the target in a perfect state--"
90002130-0198 = "It's quickest to set the #nobject responsible for protecting it with an obsession towards the target."
90002130-0199 = "This is that kind of story."
90002130-0200 = "Big Sis was the sacrifice, and we were the jesters. #nEverything was a ridiculous story prepared from the start."
90002130-0201 = "Well, perhaps the fact that our #nobject's obsession was set a bit too strongly is a minor irregularity."
90002130-0202 = "After all, a steel continent wasn't part of the original plot."
90002130-0203 = "D-don't say that..."
90002130-0204 = "Such a story is too sad... and seems wrong..."
90002130-0205 = "Wrong? From your perspective, isn't everything wrong?"
90002130-0206 = "Loving Big Sis? Falling in love with someone?"
90002130-0207 = "What is a god in the first place? Can't that be manipulated somehow?"
90002130-0208 = "...But we had to do it."
90002130-0209 = "Because there was nothing else we could do from the start!"
90002130-0215 = "...So, if only--"
90002130-0216 = "We hadn't been born."
90002130-0217 = "We wouldn't have had to feel this pain..."
90002130-0220 = "[ns] (Approaches the three)"
90002130-0223 = "Wh-what...!?"
90002130-0225 = "[ns] (Crouches down to meet the three's gaze)"
90002130-0230 = "Eh...?"
90002130-0232 = "[ns] \"You worked hard.\""
90002130-0233 = "Eh... Eeh!?"
90002130-0234 = "Sensei?"
90002130-0235 = "(Ah... this person is...)"
90002130-0240 = "[ns] \"You really worked hard.\""
90002130-0241 = "Y-yes!?"
90002130-0242 = "Are you... stupid!? #nKivotos might have all become a steel continent!?"
90002130-0243 = "...Yes?"
90002130-0244 = "I-it's true... we did try to make sure no one died, but..."
90002130-0245 = "That... yes..."
90002130-0246 = "D-don't mess with me! We didn't care about you guys at all! #nIn the first place... why are you..."
90002130-0247 = "That's right. Why would Sensei say something like that? #nTo you, we are..."
90002130-0248 = "Shouldn't we be... 'enemies' to be eliminated...?"
90002130-0249 = "[s] \"Still, I want you to live.\""
90002130-0253 = "[ns] \"No matter what happens.\""
90002130-0256 = "[ns] \"In the end, I want you to be happy too.\""
90002130-0258 = "Wh-what's the point of that...?"
90002130-0259 = "Big Sis... is no longer here."
90002130-0260 = "She's nowhere to be found."
90002130-0261 = "In a world without Big Sis, there's no reason to live..."
90002130-0267 = "H-hey! Don't pat my head!"
90002130-0268 = "Even if you do something like this, we...!"
90002130-0269 = "[s] \"This world is unfair, isn't it.\""
90002130-0270 = "...!"
90002130-0271 = "[ns5] \"A world where no one suffers...\"\n[ns6] \"And no one gets hurt...\""
90002130-0274 = "[ns7] \"If there was a world where living wasn't painful...\"\n[ns8] \"How... wonderful that would be.\""
90002130-0277 = "Why..."
90002130-0278 = "Would you say something like that...?"
90002130-0279 = "It's simple."
90002130-0280 = "This person... is just like that."
90002130-0281 = "...?"
90002130-0282 = "..."
90002130-0283 = "...!"
90002130-0288 = "Sensei is always like this."
90002130-0290 = "Next Episode; What You Were Born With"