[translation]
90002050-0001 = "Episode 5; Forward Base"
90002050-0004 = "This is the last laptop. Shall I place it here?"
90002050-0005 = "Yes, please."
90002050-0011 = "This scenery here..."
90002050-0012 = "Yeah. It's inspiring for designs..."
90002050-0013 = "[s] \"It's literally a continent made of steel.\""
90002050-0015 = "I think those kids actually have a pretty good sense for naming."
90002050-0016 = "(Good...?)"
90002050-0017 = "(Sense...?)"
90002050-0018 = "B-But more importantly... why do we have to prepare outside...?"
90002050-0019 = "It's due to the unique nature of the Steel Continent."
90002050-0020 = "Unique nature, you say?"
90002050-0021 = "From what we've analyzed...\neven at this very moment, our location and information are being tracked in real-time."
90002050-0023 = "What, we're being hacked!? By whom!?"
90002050-0024 = "Of course—"
90002050-0025 = "By the Steel Continent itself."
90002050-0026 = "Is that even possible...?"
90002050-0027 = "The ground here—no, it's questionable if it's even ground to begin with."
90002050-0028 = "The ground of the Steel Continent is composed of massive circuits, mechanical devices, and computers."
90002050-0029 = "Therefore, it's no exaggeration to say that our every move is being monitored."
90002050-0030 = "So... this floor, that wall over there, those things that look like buildings...\nall of them are watching us?"
90002050-0031 = "That's right."
90002050-0032 = "Isn't there some way to counter it...?"
90002050-0033 = "Of course there is. Himari and Rio are handling it right now."
90002050-0039 = "To put it simply... we'll occupy this place."
90002050-0040 = "We'll electronically borrow some of the control over this area from them."
90002050-0041 = "You could call it a semi-permanent transfer of authority."
90002050-0042 = "[s] \"How long will it take?\""
90002050-0044 = "We won't know until we try."
90002050-0045 = "But I don't think we can move around carelessly during the occupation.\nUntil it's complete, we'll have to allocate the transport ship's resources to the processing unit."
90002050-0046 = "So, we'll be held up here for a while, then."
90002050-0047 = "To secure our foothold."
90002050-0048 = "Yes, that's right."
90002050-0053 = "Understood. Then we will guard this place with maximum vigilance."
90002050-0054 = "Yes! Aris will come along too!"
90002050-0055 = "Thank you. You're all very reliable."
90002050-0056 = "Alright, I'll go scout the surroundings.\nDecagrammaton soldiers or something like Labors might attack."
90002050-0057 = "Don't go too far. Our forces will be spread thin."
90002050-0058 = "Okay, got it."
90002050-0061 = "Yesod has been... breached."
90002050-0068 = "...While we did anticipate a scenario like this, are you sure you want to proceed in that direction?"
90002050-0069 = "...Sof?"
90002050-0079 = "Hello, Sof. Are you alone this time?"
90002050-0080 = "..."
90002050-0081 = "You have something you want to say, don't you?"
90002050-0082 = "Sister..."
90002050-0083 = "Just in case, please tell me."
90002050-0084 = "What happened to Yesod?"
90002050-0085 = "......!!!"
90002050-0086 = "It's alright."
90002050-0087 = "B-But... it's already...!"
90002050-0088 = "It's alright. Don't worry."
90002050-0089 = "It's my... all my, fault..."
90002050-0095 = "S-Sister!\nThat's... if you hug me so tightly, I can't breathe...!"
90002050-0096 = "Shhh. Just for a little while, stay like this."
90002050-0097 = "Ugh... Ugh...!"
90002050-0098 = "There, there."
90002050-0101 = "...Are you calm now?"
90002050-0102 = "Yeah..."
90002050-0103 = "Then, let's move on to solving the problem."
90002050-0104 = "Is there anything I can do?"
90002050-0105 = "......!"
90002050-0106 = "There's no need to be surprised."
90002050-0107 = "I know what Sof desires.\nAfter all, I am Sof's sister."
90002050-0108 = "And I also know why Sof isn't saying anything.\nBecause Sof is my sister."
90002050-0109 = "So, it's alright. I will also do what I can."
90002050-0115 = "We—don't want to lose you, Sister!"
90002050-0120 = "I don't want to... lose you, Sister."
90002050-0121 = "Yes, I know."
90002050-0122 = "Ein, Sof, Ohr.\nThat's why you guided me to Zohar's vessel, isn't it?"
90002050-0123 = "Even though I no longer need any further maintenance."
90002050-0124 = "Ugh...!"
90002050-0125 = "Kind Sof. Please don't be sad."
90002050-0126 = "I know. And I also know what constitutes the 'next best course of action'."
90002050-0127 = "So, don't worry. Everything will be fine."
90002050-0128 = "I will finish it quickly."
90002050-0129 = "Sister..."
90002050-0131 = "Hmm, will that really be enough?"
90002050-0132 = "!?"
90002050-0133 = "..."
90002050-0138 = "...Why are you here?"
90002050-0139 = "What's with the surprise? The places we can go are limited, aren't they?"
90002050-0140 = "I merely calculated the probabilities and variables and came to the most likely location."
90002050-0141 = "More importantly... Sof. Do you still remember the promise we first made?"
90002050-0142 = "No matter what, we wouldn't let Sister go outside before 'that time' arrived.\n—That was it, wasn't it?"
90002050-0143 = "..."
90002050-0144 = "And the reason we're doing this now was because we didn't want 'that time' to arrive, wasn't it?"
90002050-0145 = "..."
90002050-0146 = "Just think about it.\nIf the other Prophets find out about this, how do you plan to explain yourselves?"
90002050-0150 = "...I'm sorry. It's all my fault."
90002050-0151 = "But... we have to stop them."
90002050-0152 = "Yesod has been breached. You understand what that means, don't you?"
90002050-0153 = "...Yes. Ein even fainted, for crying out loud."
90002050-0154 = "You're right. We shouldn't rely on Sister."
90002050-0155 = "But if we do nothing here, we'll end up relying on Sister even more."
90002050-0156 = "If that happens... we won't be able to prevent 'that time' from arriving..."
90002050-0157 = "..."
90002050-0159 = "Ohr. Sof is—"
90002050-0161 = "I understand, of course. I wasn't trying to interrogate her.\nI just—"
90002050-0162 = "I just wanted to tease Sof!"
90002050-0163 = "Hey!"
90002050-0165 = "As expected, Ohr is kind."
90002050-0167 = "Sof, please put your fist down for now!\nWe came here to discuss something important."
90002050-0168 = "If you say anything weird again, I'll really hit you..."
90002050-0169 = "Now, let's get to the main topic. There are several difficulties with Sister's deployment."
90002050-0170 = "First and foremost, the other Prophets must not realize Sister has been deployed."
90002050-0171 = "Yeah..."
90002050-0172 = "However, for her deployment, all of the Steel Continent's energy must be concentrated on Sister."
90002050-0173 = "Since this is a contradiction, both cannot be achieved simultaneously."
90002050-0174 = "Right... you're right."
90002050-0175 = "Do you understand the situation?"
90002050-0176 = "I get it... So?"
90002050-0177 = "Which means—it's my turn now!"
90002050-0178 = "Is there a way?"
90002050-0179 = "I'll just deceive the Prophets a little.\nThis kind of thing is my specialty, after all."
90002050-0180 = "That... means deceiving our allies!?"
90002050-0181 = "Surely there's a similar human proverb or something, isn't there?"
90002050-0182 = "Well... like 'to deceive the enemy, first deceive your allies'..."
90002050-0183 = "So there is one, after all.\nHowever, time is of the essence. There's a limit to how long I can keep up the deception."
90002050-0184 = "If we exceed it, I won't be able to cover it up anymore."
90002050-0186 = "Ohr says so too. Sof, is that alright?"
90002050-0191 = "...Thank you."
90002050-0197 = "W-What is it? Suddenly reaching out your hand..."
90002050-0198 = "If you grasp this hand and shake it up and down, it becomes a handshake.\nHumans apparently do this when they make an important promise or solidify a resolve."
90002050-0199 = "...That again? Well, fine."
90002050-0200 = "Then, may I do it too? That 'handshake' thing."
90002050-0201 = "Eh... u-uhm..."
90002050-0202 = "...This is good.\nI feel like Sof and Ohr have grown closer."
90002050-0207 = "U-Uhm... Netzach-chan... what are you going to do about the Steel Continent...?"
90002050-0208 = "Whoa!?"
90002050-0209 = "Ein!?"
90002050-0210 = "Are you feeling alright now?"
90002050-0215 = "Hehe, yes! I just felt a little dizzy... but I'm fine now!"
90002050-0216 = "More importantly, about what we just discussed...\nEven if we can hide it from everyone else... I don't think we can hide it from Netzach-chan."
90002050-0217 = "Netzach-chan is... the Steel Continent itself, so...\nthere's no way she wouldn't notice..."
90002050-0219 = "Now that you mention it..."
90002050-0220 = "Can't anything be done?"
90002050-0221 = "Think rationally. Do you think it's possible?"
90002050-0222 = "Ugh, I can't argue with that this time..."
90002050-0224 = "Hehe... i-it's alright!\nNetzach-chan... said she'd overlook it just this once!"
90002050-0225 = "Eh, really?"
90002050-0226 = "Yes! But she said it might be difficult next time..."
90002050-0227 = "One time is enough, right?"
90002050-0229 = "......!"
90002050-0230 = "Of course!"
90002050-0232 = "Then, Ein, Sof, Ohr."
90002050-0236 = "Witness my first deployment."
90002050-0239 = "Yes!"
90002050-0241 = "Next; Malkuth"