[translation]
90002120-0001 = "Episode 12; What Disappeared"
90002120-0005 = "What's happening...?"
90002120-0006 = "They were helping each other just a moment ago... A falling out?"
90002120-0011 = "It is certainly perplexing.#nJudging by their reactions, it's unlikely this is going according to plan..."
90002120-0016 = "Is that... some kind of ritual...?#nWhat could be its purpose...?"
90002120-0017 = "To state the facts, the energy flow converging on Malkuth has stabilized.#nThe transformation of the Steel Continent also seems to have ceased."
90002120-0018 = "Kei, do you have any insight?"
90002120-0023 = "No. I only have the impression that it's quite fanatical.#nMore importantly..."
90002120-0025 = "Please! Please!#nPlease... don't take my sister!!"
90002120-0026 = "If someone must be sacrificed, I'll take their place—!!!!"
90002120-0030 = "(What was the true meaning of those words...?)"
90002120-0035 = "Sensei!"
90002120-0036 = "Look out!"
90002120-0041 = "[ns] \"Whoa!?\""
90002120-0043 = "(Kei and Aris were pushed by Rio.)"
90002120-0044 = "Sensei! Are you alright!?"
90002120-0045 = "[s] \"What happened!?\""
90002120-0046 = "Watch your step! It's not over yet!"
90002120-0053 = "[ns] \"The wall—from the ground!?\""
90002120-0054 = "Ah...!?"
90002120-0055 = "Rio!"
90002120-0060 = "Thank you..."
90002120-0068 = "The shaking has stopped for now, but... in an instant, the wall became like this..."
90002120-0069 = "Our comrades are being separated... It's just like that time."
90002120-0074 = "That time?"
90002120-0075 = "Kei?"
90002120-0076 = "It was during 'Eridu'.#nBack then, we activated the bulkheads and separated everyone from C&C, didn't we?"
90002120-0077 = "That's right..."
90002120-0078 = "Memories of that time remain with Aris as well."
90002120-0079 = "It's like seeing an old dream, a hazy feeling, but..."
90002120-0080 = "...That's true.#nBack then, Aris... was one with Kei."
90002120-0081 = "..."
90002120-0082 = "..."
90002120-0083 = "Kei. If I were to—"
90002120-0084 = "If you're about to say it's your fault, or if you had done better...#nthen stop immediately."
90002120-0085 = "K-Kei?"
90002120-0086 = "Kei!?"
90002120-0087 = "Things just happen. There's no reason for it.#nTherefore, we must simply accept them as they are."
90002120-0088 = "Besides, there's no point in dwelling on what has already happened.#nEspecially if it has nothing to do with you."
90002120-0089 = "In the first place, that's not what's important!"
90002120-0090 = "So...?"
90002120-0091 = "How can we escape this situation?#nAnd how can we return safely? Only that matters!"
90002120-0092 = "Understood? I will return alive. No matter what—I will return!"
90002120-0093 = "No matter what happens, I want to survive until the very end!"
90002120-0094 = "...!"
90002120-0095 = "Yes! Kei is absolutely right!"
90002120-0096 = "[s] \"Yeah. I agree.\""
90002120-0101 = "[ns1] \"No matter what—\"\n[ns2] \"Kei should survive and return.\""
90002120-0104 = "...Do you truly understand?"
90002120-0109 = "I'm talking about everyone here! What good would it do if only I returned!?"
90002120-0113 = "[ns] \"Yeah.\""
90002120-0114 = "Hmph... What's with that smile...?"
90002120-0116 = "[ns] \"Alright. Then let's go.\""
90002120-0117 = "Do we have a plan?"
90002120-0118 = "Anywhere is better than staying here, isn't it?#nWe need to walk around and gather some information."
90002120-0119 = "We also need to reunite with Himari and the others quickly."
90002120-0120 = "Yes! Aris is a hero, so I'll lead the way!"
90002120-0121 = "How dependable."
90002120-0127 = "...Wait a moment. What is that...?"
90002120-0128 = "Huh...?"
90002120-0130 = "(Gazed in the direction Rio was pointing.)"
90002120-0131 = "(Beyond the wall, in the distance, was—)"
90002120-0135 = "(It was the form of 'something' that was called Malkuth until recently...)"
90002120-0137 = "Next Time; Children"