[translation]
90002060-0001 = "Episode 6; Malkuth"
90002060-0009 = "Sensei! Labor and Decagrammaton soldiers are heading your way!"
90002060-0010 = "[s] \"Understood on our end too! Eimi, what's your assessment?\""
90002060-0011 = "Set up a defensive line. I'll return as soon as possible."
90002060-0016 = "...Ah, disregard that. Detected a separate unit. Probably a scout.#nI'll take them out and then return."
90002060-0017 = "[s] \"Don't get hurt, okay...?\""
90002060-0018 = "Are you worried about me? That makes me happy."
90002060-0019 = "It can't be helped. I'll head to the front lines too, so Sensei will worry about me."
90002060-0020 = "...No, Toki, you need to protect Sensei, right? What if something happens to Sensei?"
90002060-0021 = "That's true. Then, I'll choose the option that allows me to stay with Sensei longer."
90002060-0022 = "What should Aris and the others do...?"
90002060-0023 = "...Let's trust Eimi. I think it's best for us to proceed with occupying this area."
90002060-0024 = "I agree, that's more logical."
90002060-0025 = "Fortunately, system construction is almost complete."
90002060-0026 = "...Oh?"
90002060-0027 = "[s] \"Kei?\""
90002060-0028 = "We were... analyzing this area, right?"
90002060-0029 = "Is there a problem?"
90002060-0030 = "Not far from here, there's a structure... It seems to be some kind of facility."
90002060-0034 = "A structure, you say?"
90002060-0035 = "What kind of facility could it be?"
90002060-0036 = "Perhaps ruins abandoned long ago?"
90002060-0037 = "Have you forgotten that the Steel Continent was formed quite recently?"
90002060-0038 = "Whatever it is, I think its nature as a 'structure' is important.#nPerhaps it could be utilized as a defensive stronghold."
90002060-0039 = "It should be safer than this open area. Let's go investigate."
90002060-0046 = "..."
90002060-0047 = "..."
90002060-0048 = "Th-this place is...?"
90002060-0049 = "Aris... knows.#nRare items are hidden in places like this, right...!"
90002060-0053 = "[ns] \"Is it some kind of... research facility?\""
90002060-0054 = "...I agree."
90002060-0055 = "For now, I'll send Eimi these coordinates."
90002060-0060 = "...What's that?"
90002060-0064 = "These... don't they resemble those children?"
90002060-0065 = "And in such numbers..."
90002060-0066 = "It's like looking at specimens... Ugh, it's unsettling..."
90002060-0067 = "On this glass tube... something is written."
90002060-0072 = "\"DEFECTED\"...?#nIf taken literally, it means 'defective product'."
90002060-0073 = "..."
90002060-0074 = "I don't think so."
90002060-0075 = "Meaning?"
90002060-0076 = "Probably--"
90002060-0077 = "'Defective' would be more accurate."
90002060-0078 = "Defective...?"
90002060-0089 = "We've only just begun analysis, but we've discovered a few things."
90002060-0090 = "First, there are no operational issues.#nIf some kind of consciousness circuit is implanted, they could be activated immediately."
90002060-0091 = "Despite being 'branded' as defective, their condition is good."
90002060-0092 = "However, the problem lies with the host's security."
90002060-0093 = "Kei has confirmed that... they are protected by what could be called an ancient form of security."
90002060-0094 = "While troublesome, it's not an unknown technology to me."
90002060-0095 = "Given enough time, I believe I can bypass it, but..."
90002060-0100 = "Yo, everyone safe?#nI came as instructed, but what kind of place is this?"
90002060-0101 = "Eimi! Glad you're safe! Um, this place is--"
90002060-0106 = "...What could it be?"
90002060-0107 = "Aris!?"
90002060-0108 = "Aris-chan!?"
90002060-0109 = "From the looks of it, you're investigating that, right?"
90002060-0110 = "I've set up a defensive line with AMAS outside the facility."
90002060-0111 = "Yeah, I confirmed it. I took care of the enemy scout unit, so it should be safe for a while."
90002060-0116 = "[ns] \"What!?\""
90002060-0122 = "Outside! The AMAS defensive line... it's been breached!?"
90002060-0123 = "How...? We should have defeated the nearby enemies..."
90002060-0124 = "Let's confirm it quickly, rather than thinking about it!"
90002060-0129 = "U-Uwaaaah!?"
90002060-0130 = "Big sis, are you okay?"
90002060-0131 = "S-Sensei, over there...!"
90002060-0133 = "[ns] \"Eh...?\""
90002060-0134 = "What is that...?"
90002060-0141 = "(An individual I've never seen before. But those characteristics are unmistakably Decagrammaton... Could it be?)"
90002060-0142 = "...Malkuth?"
90002060-0143 = "Malkuth!?"
90002060-0146 = "As expected, you are the one most knowledgeable about us."
90002060-0147 = "The one who pursues the stars--Tsukatsuki Rio."
90002060-0148 = "!?"
90002060-0149 = "Akeboshi Himari."
90002060-0150 = "Izumimoto Eimi, Asuma Toki."
90002060-0151 = "Key of the Nameless Gods."
90002060-0152 = "...Um, my name is--"
90002060-0153 = "What is born cannot be changed. Don't you agree, Kei?"
90002060-0154 = "...!!!"
90002060-0155 = "And, Sensei."
90002060-0162 = "[ns] \"You are Malkuth?\""
90002060-0163 = "In times like these... one says 'It's a pleasure to meet you,' right?"
90002060-0167 = "Greetings, everyone.#nA greeting from Ein, Sof, and Ohr."
90002060-0168 = "I am a single will created under the banner.#nA pilgrim of the kingdom who has reached the ends of the world."
90002060-0169 = "I am Malkuth."
90002060-0173 = "Now then... good night."
90002060-0174 = "Sensei--!"
90002060-0180 = "Aaaaaaaah!!"
90002060-0184 = "[ns] \"Toki!\""
90002060-0185 = "Toki, in her Ab-Eshuv state, taken down in one hit...!?"
90002060-0186 = "(This is absurd. With this kind of firepower, we can't even stand a chance...)"
90002060-0190 = "...Sensei? What are you--!?"
90002060-0191 = "[ns] Runs forward."
90002060-0195 = "[ns] Shields the students."
90002060-0196 = "Sensei! What are you doing!?"
90002060-0197 = "...You are exactly as I expected. That's reassuring."
90002060-0198 = "Sacrifice yourself, but don't lay a hand on the students, is that it?"
90002060-0199 = "[s] \"...!\""
90002060-0200 = "It's alright. There's no need for that."
90002060-0201 = "...You seem confused. Yes, I understand."
90002060-0202 = "However, I will state this clearly."
90002060-0203 = "We have no intention of taking anyone's life."
90002060-0204 = "Asuma Toki was merely given a moderate impact, not enough to be fatal."
90002060-0211 = "Sen...sei..."
90002060-0213 = "Please, step back... I will protect you..."
90002060-0217 = "No matter what, I will protect Sensei... To Eimi... and to myself...!"
90002060-0221 = "O-Onee-sama! Time is running out...! P-Please hurry...!"
90002060-0222 = "..."
90002060-0223 = "When everything ends and the time of transition arrives, you will all eventually understand."
90002060-0224 = "That we are attempting to remove all your sins and suffering."
90002060-0225 = "[s] \"How will you do that?\""
90002060-0226 = "If you touch a sooty spot, you'll get soot on you."
90002060-0227 = "In that case, one simply needs to avoid approaching the burnt remains in the first place."
90002060-0228 = "[s] \"That's not quite right, is it?\""
90002060-0229 = "We are not seeking your consent."
90002060-0230 = "For I have come here to declare that all will be so. That is why I am here."
90002060-0231 = "Onee-sama! Preaching the gospel is fine, but I'd like you to prioritize our original objective now!"
90002060-0232 = "--The time has come."
90002060-0233 = "I will gladly see you off at the end of your pilgrimage."
90002060-0240 = "Gh... Ngh...!"
90002060-0244 = "Toki?"
90002060-0245 = "Toki!"
90002060-0247 = "(A blinding flash obstructed my vision.)"
90002060-0248 = "(I instinctively closed my eyes.)"
90002060-0252 = "Sensei! It's alright! We're here!"
90002060-0254 = "[ns] \"Arona? Plana?\""
90002060-0255 = "Struggling. Insufficient output. The energy flow is working against us.#nHowever, we cannot back down."
90002060-0256 = "No holding back! Sensei and all the students are precious!"
90002060-0257 = "Affirmative. If we don't do our best, we can't face everyone."
90002060-0259 = "Ugh...! Ughhh...!"
90002060-0260 = "...Kuh."
90002060-0261 = "Please... Just a little more...!"
90002060-0265 = "Remaining energy... insuffi..."
90002060-0270 = "Plana-chan!? P-Please hold on! Ugh, even if it's just me...!"
90002060-0274 = "Uwaaaah!!"
90002060-0278 = "..."
90002060-0279 = "Huh...? Malkuth's output suddenly weakened!#nBut why...?"
90002060-0280 = "!!!"
90002060-0281 = "Sensei! It's Kei!"
90002060-0286 = "[ns] \"Kei! Get back!\""
90002060-0287 = "Even in this situation, that's your response. Truly, you're an adult who never ceases to surprise."
90002060-0288 = "...Well, that's precisely why I can entrust Aris to you."
90002060-0289 = "[s] \"What are you going to do...?\""
90002060-0290 = "Don't worry. This place is filled with the power of the Nameless Gods."
90002060-0291 = "And in this place, I am the most skilled at handling that power."
90002060-0292 = "...It seems to have been arbitrarily arranged, and the sensation is different from usual."
90002060-0293 = "In any case, that self-proclaimed prophet, Malkuth, must be bewildered."
90002060-0295 = "Unexpected. This variable was unforeseen."
90002060-0296 = "Onee-sama... um..."
90002060-0297 = "Time's up... is..."
90002060-0298 = "Ah, but I can manage to buy a few more seconds!#nAnything more than that would be impossible, though..."
90002060-0299 = "Understood. I will not hold back."
90002060-0304 = "What, its output is still increasing...! Is it a monster...!?"
90002060-0305 = "S-Sensei!? I'm fine!#nWith Aris here, there's no way I'd fall!"
90002060-0306 = "After receiving the energy... I'll reorganize it..."
90002060-0307 = "Uwaaaahhh--!!!"
90002060-0312 = "Kuh--!!"
90002060-0314 = "Don't... mess with me...!"
90002060-0315 = "After using this power--"
90002060-0316 = "Who do you think I am!!"
90002060-0320 = "O-Onee-sama...!"
90002060-0321 = "This is my limit! Come back quickly!"
90002060-0322 = "Onee-sama! Don't push yourself! The results don't matter anyway!!"
90002060-0323 = "..."
90002060-0324 = "Understood. Ein, Sof, Ohr."
90002060-0332 = "Malkuth is... retreating...?"
90002060-0333 = "Sensei, are you alright!?"
90002060-0334 = "Sensei!"
90002060-0335 = "Are you alright, Sensei!? Toki, Kei, Himari-senpai, Rio-senpai too...!"
90002060-0336 = "K-Kei-chan...?"
90002060-0337 = "Kei!?"
90002060-0345 = "Kei? Wake up, Kei!#nI don't want this... Don't leave Aris alone!"
90002060-0347 = "KEY!!!!"
90002060-0349 = "Next; Kei"