[translation]
90002040-0001 = "Episode 4; Yesod"
90002040-0003 = "These are easy to handle."
90002040-0004 = "...That arm is just too massive."
90002040-0016 = "That makes one hit..."
90002040-0017 = "Ugh!?"
90002040-0022 = "My leg...!"
90002040-0023 = "It's trapped in the rubble...!"
90002040-0027 = "Hmph, ugh, haaah...!"
90002040-0028 = "I don't think I can get it out..."
90002040-0037 = "...!!!"
90002040-0038 = "(Yesod raised its arm again.)"
90002040-0039 = "(Surrounding us and cutting off our escape... Does it intend to crush us, allies and all?)"
90002040-0040 = "(It is efficient. It can just make more.)"
90002040-0041 = "(But I...)"
90002040-0042 = "Even if it means a minor injury—!"
90002040-0054 = "...Huh?"
90002040-0059 = "Are you okay!?"
90002040-0060 = "Big sis! We'll move it on three...!"
90002040-0061 = "One, two—"
90002040-0066 = "—Three!!!"
90002040-0072 = "...Momoi? Midori?"
90002040-0074 = "Heh heh! We came to help! Sensei asked us to!"
90002040-0075 = "Are you alright?"
90002040-0077 = "Yes. Thank you, both of you."
90002040-0078 = "Also..."
90002040-0083 = "Hm?"
90002040-0084 = "Yes?"
90002040-0086 = "Run to the right at full speed, without looking back."
90002040-0088 = "Why—Huh!?"
90002040-0096 = "Kyaaah!?"
90002040-0104 = "Th-That was a close call..."
90002040-0105 = "Thank you, Eimi."
90002040-0107 = "No, thank you."
90002040-0108 = "Well then, Sensei."
90002040-0109 = "Make sure you do it right."
90002040-0114 = "Is this maximum speed!?"
90002040-0115 = "Yes. If we increase the RPMs any further, the engine will explode."
90002040-0116 = "Can't we use the Augmenter?"
90002040-0117 = "It'll only last a few seconds, but... are you sure?"
90002040-0118 = "Permission granted!"
90002040-0119 = "Understood. Opening the gate!"
90002040-0126 = "Well then, everyone, let's meet on top of Yesod."
90002040-0127 = "Aris, deploying!"
90002040-0133 = "Yesod Attack Squad has begun their descent."
90002040-0134 = "I return command to Sensei. I'll be counting on you."
90002040-0135 = "[s] \"I'll settle this while Eimi and the others are safe!\""