[translation]
90002190-0001 = "Episode 19; The Day God Fell"
90002190-0002 = "How about a rebellious phase?"
90002190-0004 = "The first Stigma disappears."
90002190-0005 = "!?"
90002190-0007 = "This is like an emergence, in other words, 'Liberation'."
90002190-0012 = "The second Stigma disappears.\nThis is like a birth, in other words, 'First Cry'."
90002190-0017 = "The last Stigma disappears.\nThis is like thawing, in other words, 'Budding'."
90002190-0024 = "Th-this is...!"
90002190-0029 = "The Sword of Burnt Offering... has been drawn...!?"
90002190-0030 = "Ugh, ugh...!"
90002190-0035 = "...?"
90002190-0036 = "Why am I... again...?"
90002190-0037 = "...!?"
90002190-0038 = "...Huh?"
90002190-0039 = "Sof, Ohr! Is this...!?"
90002190-0040 = "Yes! No way... really...!"
90002190-0041 = "Big Sister is--"
90002190-0043 = "She's back!!!!"
90002190-0044 = "She didn't disappear! She survived!! It's a miracle!!!"
90002190-0045 = "Ein? Sof? Ohr?\nI... why? How...?"
90002190-0046 = "Big Sister!!!!"
90002190-0053 = "My body... can move...?"
90002190-0054 = "Everyone! Please compose yourselves!"
90002190-0058 = "Hmm...? Kei...? Aris is..."
90002190-0059 = "...Ah! I have to fight Decagrammaton!\n...Huh?"
90002190-0060 = "Sensei, are you alright?"
90002190-0061 = "[s] \"Yes... I'm fine.\""
90002190-0062 = "I'm relieved you're safe..."
90002190-0064 = "Big Sister!"
90002190-0066 = "Ein, Sof, Ohr..."
90002190-0067 = "..."
90002190-0071 = "Sensei... and everyone else too."
90002190-0072 = "This is... isn't it like 'yesterday's enemy is today's friend'?"
90002190-0088 = "...Huh?"
90002190-0089 = "Eh...?"
90002190-0090 = "What...?"
90002190-0091 = "...!"
90002190-0092 = "No...?"
90002190-0093 = "Ein...? Sof...? Ohr...?"
90002190-0097 = "Ah, ah... AAAAAAAAAH--!?!?!?!?"
90002190-0098 = "[ns] \"...!!\""
90002190-0099 = "N-no... This is too much--!!"
90002190-0100 = "Don't look back!"
90002190-0101 = "?!?!?!?"
90002190-0104 = "[ns] \"?!?!?!?"
90002190-0106 = "Kill the god! We're prepared for this!"
90002190-0107 = "Cough, cough! Th-that's right... Don't worry about us...!"
90002190-0108 = "Have you forgotten why you came all this way?\nIt was to prevent the world from being covered by the Steel Continent, wasn't it?"
90002190-0110 = "This is your only chance!\nOr do you intend to make our choice meaningless?"
90002190-0114 = "B-but...!"
90002190-0115 = "Ein? Sof? Ohr?"
90002190-0116 = "Why...?"
90002190-0117 = "Heh, hehe. Well, you see."
90002190-0118 = "This was right... this is what we had to do.\nI was glad to see Big Sister one last time. Ahaha..."
90002190-0119 = "...There's something I've always wanted to say."
90002190-0121 = "Someone told me, 'You did well.'"
90002190-0124 = "They told me to be friends, to resist if I had a wish, and just said whatever they pleased."
90002190-0127 = "We're not doing this because it's right. There's nothing else we can do.\n...This is our fight."
90002190-0130 = "W-we want Big Sister to live."
90002190-0133 = "No matter what happens, only Big Sister must survive."
90002190-0136 = "See more things, meet more people, and experience more."
90002190-0139 = "Much, much more than us--"
90002190-0142 = "Experience many, many different things."
90002190-0145 = "Please, survive until the very end."
90002190-0147 = "Ah... ah... AAAAAAH...!"
90002190-0148 = "I told you. Don't look back."
90002190-0149 = "Give me a break. It's embarrassing, isn't it?"
90002190-0150 = "Hehehe... Thank you. For saying you wanted to be friends..."
90002190-0151 = "Keep moving forward without stopping. Until the very end."
90002190-0152 = "Th-that's right...! To follow in the footsteps of your predecessors and forge a path... That's how you all live, isn't it...?"
90002190-0153 = "Oh! Also, be careful of people obsessed with self-actualization! Ahaha!"
90002190-0155 = "I'm sorry for trying to destroy your [ruby=Kivotos]world[/ruby]."
90002190-0156 = "I'm sorry for always doing as I pleased."
90002190-0157 = "Even so."
90002190-0158 = "If even a small part of your [ruby=Sensei's]world[/ruby]..."
90002190-0159 = "could be a place for Big Sister--"
90002190-0160 = "Please take care of our Big Sister."
90002190-0164 = "[ns] \"...!\""
90002190-0165 = "Ein...? Sof...? Ohr...!?"
90002190-0166 = "Ah, ah... AAAAAAAAAH...!!"
90002190-0167 = "AAAAAAAAAAAAAAH!!!"
90002190-0171 = "...Is this the limit of the vessel?"
90002190-0177 = "Cough, cough...!"
90002190-0178 = "[ns] \"Malkuth...!\""
90002190-0182 = "[ns] \"Someone, lend a hand!\""
90002190-0183 = "..."
90002190-0187 = "Aris will help!"
90002190-0188 = "Me too."
90002190-0189 = "Leave the heavy lifting to me."
90002190-0192 = "[ns] \"Are you alright?\""
90002190-0193 = "I am... Ein... Sof... Ohr..."
90002190-0194 = "[s3] \"Stand up, Malkuth.\"\n[s4] \"Let's [ruby=live]fight[/ruby] together.\""
90002190-0197 = "B-but..."
90002190-0198 = "[s5] \"It might be difficult for you right now,\"\n[s6] \"but please don't forget your sisters' will.\""
90002190-0201 = "...!"
90002190-0202 = "U-ugh...!"
90002190-0207 = "[ns] \"Rio! Himari! Please analyze the situation!\""
90002190-0208 = "Yes, understood!"
90002190-0213 = "...From Malkuth's body, Decagrammaton's signal has completely vanished!"
90002190-0214 = "Then, where is Decagrammaton...?"
90002190-0220 = "Over there, something seems to have appeared."
90002190-0228 = "Next Time; That Which Took Form"