[translation]
90002100-0001 = "Episode 10;000, 00, 0"
90002100-0002 = "Steel Continent!"
90002100-0003 = "Th-the assault...!#n...Ugh."
90002100-0004 = "You just got new equipment, didn't you? You need to be more motivated!"
90002100-0005 = "B-but..."
90002100-0006 = "Big sister, don't pester her. You're bothering Yuzu, aren't you?"
90002100-0007 = "That sounds bad!#nI'm just trying to encourage Yuzu!"
90002100-0011 = "Exactly! Courage is the most important weapon for a hero!"
90002100-0012 = "Why are you joining in too...?"
90002100-0014 = "[ns] \"First, we're heading to Binah's area, right?\""
90002100-0015 = "Yes. That area has a firewall protecting the Steel Continent.#nIf we succeed in breaking through, the subsequent assault should become somewhat easier."
90002100-0016 = "Our first objective is to secure Binah's core and gain access to the Steel Continent's network.#nFrom there, I'll leave it to Sensei's judgment."
90002100-0017 = "In that case, it would be best to split into two teams.#nThis transport ship offers excellent mobility."
90002100-0018 = "Let's flexibly adjust team formations as needed."
90002100-0019 = "But after we occupy an area, we definitely need to call Kei, right?"
90002100-0020 = "Yes. Then Kei will extract information from the Prophet's core,#nand convert it into our combat strength."
90002100-0021 = "...Could you please not make it sound like a lifeform that utilizes enemy abilities?"
90002100-0022 = "Oh, Kei knows that game too!#nThat's truly a god-tier game!"
90002100-0024 = "[ns] \"Kei, do you like games too?\""
90002100-0025 = "Of course not!#nThese are just memories and experiences remaining from when I synchronized with Aris—!"
90002100-0026 = "I see... So, Aris's memories were unnecessary for Kei..."
90002100-0027 = "Th-that's not it!#nUm, what I mean is, well...!"
90002100-0028 = "It's alright... Aris still wants to cherish Kei like that...#nNo matter what Kei thinks of Aris..."
90002100-0029 = "I told you it's not like that! Aris, please listen to me!!"
90002100-0030 = "Kei, don't worry about it. Aris will be fine..."
90002100-0031 = "Aris—!!"
90002100-0037 = "(Contrary to a flustered Kei, Aris turned to face us—)"
90002100-0038 = "(...and smiled mischievously!)"
90002100-0040 = "[ns] \"Aris, let's stop teasing her now.\""
90002100-0041 = "Hehe, I'm sorry, Kei."
90002100-0042 = "Huh? Teasing...?"
90002100-0043 = "[ns] \"Kei has such big reactions, doesn't she...?\""
90002100-0044 = "Hehe, that's right."
90002100-0045 = "..."
90002100-0046 = "...."
90002100-0047 = "......"
90002100-0048 = "Sensei—!!!"
90002100-0050 = "Well then, shall we go?#nI, Toki Asuma, will assist Sensei as a perfect maid."
90002100-0051 = "With that outfit, you don't really look like a maid...?"
90002100-0052 = "...I will assist Sensei as a perfect agent."
90002100-0053 = "That was a quick change..."
90002100-0054 = "Responding swiftly to situations. Don't you think that's precisely what an excellent agent does?"
90002100-0055 = "Vee."
90002100-0056 = "[s] \"Y-yeah, you're right...\""
90002100-0057 = "Um, shall we start soon?"
90002100-0058 = "Everyone, return to your positions."
90002100-0059 = "Then, I'll return command to Sensei."
90002100-0060 = "[s] \"It's nerve-wracking.\""
90002100-0061 = "Oh, aren't you experienced in command?"
90002100-0062 = "[s] \"You're right about that. Let's proceed as usual.\""
90002100-0067 = "[ns] \"Alright, let's begin the Binah assault!\""