[translation]
"90002030-0001" = "Episode 3; Sortie"
"90002030-0002" = "Now, let's organize the situation."
"90002030-0003" = "There are 'things we've learned' and 'things we need to do.' Which would you like to hear first?"
"90002030-0005" = "Then, please tell me what you've learned."
"90002030-0007" = "We're starting to get a clearer picture of the entities that attacked us."
"90002030-0008" = "Their model name is [ruby=Labor]Labor[/ruby]."
"90002030-0010" = "Labor...? "
"90002030-0015" = "It means 'worker.' Given this model's role, it's a fitting name."
"90002030-0016" = "As far as we can tell, there seem to be three types of Labors."
"90002030-0017" = "From what I saw at the scene... there was a rectangular model covered in something like armor."
"90002030-0018" = "It was very sturdy!"
"90002030-0019" = "I think we can call that model a 'Defensive Labor.'"
"90002030-0020" = "Next, a model equipped with a cannon so large it was obvious at a glance."
"90002030-0022" = "The design is a bit lacking, but... it seems we can call it a 'Turret Labor.'"
"90002030-0023" = "Ah, and then... there were two prototype-like... #nslightly smaller models..."
"90002030-0025" = "Then, let's call that model a 'Basic Labor.'"
"90002030-0026" = "Generally, smaller things look cuter... #nbut this one just reminded me of a spider..."
"90002030-0027" = "Are you saying spiders aren't cute?"
"90002030-0028" = "Of course, aesthetics are subjective. I understand your sense of beauty is... unusual."
"90002030-0030" = "Neither the department head nor the chairman, now is the time to discuss that."
"90002030-0031" = "[s] \"Is there anything else you've learned?\""
"90002030-0035" = "Yes. I believe this is the most important."
"90002030-0036" = "Labors can transform surrounding inorganic matter into Steel Continents."
"90002030-0037" = "What does that mean...?"
"90002030-0038" = "So, the Labors were expanding the Steel Continents?"
"90002030-0039" = "I don't think that's incorrect."
"90002030-0040" = "It's reasonable to assume that the mass production of Labors began after the Steel Continents had been constructed to a certain extent."
"90002030-0041" = "It's highly likely that the Labors approached the transport ship to incorporate it into the Steel Continent."
"90002030-0042" = "I haven't examined all the Labors, so this is just a possibility. #nBut in the first place, examining them all isn't realistic."
"90002030-0043" = "What concerns me is... #nthe fact that the Labors seem to be re-engineering the internal structure of the Steel Continents."
"90002030-0044" = "Re-engineering...?"
"90002030-0045" = "Construction of structures, repair of damaged areas—"
"90002030-0046" = "And assimilation of inorganic matter that was mixed in during the expansion of the Steel Continent."
"90002030-0047" = "Ah, that's why the transport ship..."
"90002030-0049" = "Yeah, I understand 'what we've learned.' So, what about 'what we need to do'?"
"90002030-0050" = "It's easy to say—"
"90002030-0054" = "—We need to break through Yesod."
"90002030-0055" = "[s] \"...\""
"90002030-0056" = "I'll share the information we have so far about the ninth Prophet, 'Yesod.'"
"90002030-0057" = "Strangely, Yesod has no original form."
"90002030-0058" = "What does that mean?"
"90002030-0059" = "For example, with Hod, it was originally the communication unit AI 'Hub' of Millennium."
"90002030-0060" = "Kolkhoz was a work ship, and Gebura was an unmanned probe."
"90002030-0061" = "In this way, structures based on AI systems have become Prophets by being hacked by Decagrammaton, along with their AI."
"90002030-0062" = "The only exception, you could say, is Binah. #nIt was first sighted decades ago in the Abydos Desert."
"90002030-0063" = "Is Yesod also an exception?"
"90002030-0064" = "Yes. This is a conjecture, but—"
"90002030-0065" = "I believe Yesod was [ruby=・]crea[/ruby][ruby=・]ted[/ruby] after the Steel Continent had been constructed to a certain extent."
"90002030-0068" = "Otherwise, there's no explanation for why we couldn't detect Yesod's signal, which is so enormous, until now."
"90002030-0069" = "That's a reasonable deduction."
"90002030-0071" = "And if we assume that to be true... #nit means Yesod is very pure."
"90002030-0072" = "A 'perfected' Prophet created solely for a purpose...?"
"90002030-0073" = "…Probably."
"90002030-0074" = "Its immense size and power are likely also a result of that optimization."
"90002030-0076" = "The more we discuss it, the more I feel like we're running out of solutions..."
"90002030-0077" = "Ah, Aris... everyone! It'll be alright!"
"90002030-0078" = "A hero... doesn't get scared before embarking on an adventure... Waaah!"
"90002030-0079" = "[s] (She already looks scared though...)"
"90002030-0081" = "But I think it has a weakness."
"90002030-0082" = "Does it...?"
"90002030-0083" = "From atop the wall, it can't move, can it?"
"90002030-0084" = "Th-that's true... #nIn games too, super-large bosses... can't move easily..."
"90002030-0085" = "I wasn't planning on comparing it to a game, but..."
"90002030-0087" = "Heh, that might actually be spot on."
"90002030-0088" = "Whatever it is, as long as it has mass, there are things it can't avoid."
"90002030-0089" = "Things it can't avoid? #n...I see."
"90002030-0090" = "It's a matter of speed and durability."
"90002030-0091" = "That's right. #nTo move a large mass, you need a corresponding amount of energy."
"90002030-0092" = "If you have enough energy, you can move it quickly, but its durability will likely reach its limit before it can move."
"90002030-0093" = "Of course, there's still much that's unknown about the strength and durability of this mysterious substance."
"90002030-0094" = "However, as a substance, it must have a limit."
"90002030-0095" = "[s] \"So... what does that mean?\""
"90002030-0096" = "In short, this is what it means."
"90002030-0097" = "Yesod's attacks are expected to have movement restrictions."
"90002030-0098" = "Based on that, if we devise a plan—"
"90002030-0099" = "—It will be a short, decisive battle using a diversion."
"90002030-0100" = "…That's correct."
"90002030-0101" = "Yesod's attacks... more precisely, its 'swinging arm attacks' are a threat in themselves."
"90002030-0102" = "However, if our predictions are correct, its movements should be slow."
"90002030-0103" = "If we focus on evasion, we might be able to create an opening."
"90002030-0104" = "We'll temporarily ignore its area-of-effect influence, which it uses to its advantage due to its size."
"90002030-0105" = "At least, it should be enough to distract Yesod a few times."
"90002030-0106" = "And during that opening, the main force will move by transport ship—"
"90002030-0107" = "And launch a surprise attack on Yesod from atop the wall."
"90002030-0113" = "Himari... you're proposing this plan, aren't you?"
"90002030-0114" = "…If it were the old you, wouldn't you have pushed ahead without consulting anyone?"
"90002030-0115" = "The current you, presenting a plan like this before I do—"
"90002030-0116" = "—is different. That just goes to show how cornered we are..."
"90002030-0117" = "…We don't have time."
"90002030-0118" = "Yes..."
"90002030-0119" = "[s1] \"Everyone, wait a moment.\"\n[s2] \"That plan...\""
"90002030-0122" = "..."
"90002030-0123" = "That's right."
"90002030-0124" = "This is a plan to defeat Yesod by using someone as bait."
"90002030-0125" = "Moreover, we can't guarantee the safety of the bait, and there's no certainty that we can defeat Yesod."
"90002030-0126" = "In other words, it's an extremely dangerous plan..."
"90002030-0127" = "[s3] \"I... cannot agree.\"\n[s4] \"As... everyone's teacher.\""
"90002030-0130" = "But I can't think of any other way."
"90002030-0132" = "Th-then...! Aris will...!"
"90002030-0133" = "..."
"90002030-0135" = "No, Aris."
"90002030-0136" = "Why not? I may be a trainee, but Aris is a hero! #nSo, to help everyone—"
"90002030-0137" = "That's right. Because you are the hero."
"90002030-0138" = "You will surely be the trump card."
"90002030-0139" = "…Does that include me?"
"90002030-0140" = "…Yes."
"90002030-0141" = "You always act so cold."
"90002030-0142" = "…I'm used to this."
"90002030-0143" = "I hate that about you."
"90002030-0147" = "It makes me so angry I can barely stand it...!"
"90002030-0148" = "Aren't you always angry, Kei?"
"90002030-0149" = "That's true... Ah, whatever! That's not what I mean!"
"90002030-0150" = "I'm angry in a different way! Don't add fuel to the fire!!"
"90002030-0151" = "[s] \"Is there really... no other way?\""
"90002030-0153" = "..."
"90002030-0154" = "..."
"90002030-0155" = "(The atmosphere in the room grew heavy.)"
"90002030-0156" = "(Yet, time relentlessly marches on...)"
"90002030-0161" = "Then, I'll do it."
"90002030-0165" = "[ns] \"!?\""
"90002030-0166" = "Eimi!?"
"90002030-0171" = "In short, I just need to draw its attention, right?"
"90002030-0173" = "B-but...!"
"90002030-0174" = "Eimi! Just like the teacher worried...!"
"90002030-0176" = "It's okay. This is the most efficient way. #nSo clear that there's no need for words like 'maybe.'"
"90002030-0177" = "I'm used to fieldwork, and I'm quite sturdy and fast."
"90002030-0178" = "B-but... what if it doesn't go as planned...!"
"90002030-0179" = "[s5] \"Eimi, can you please reconsider...?\"\n[s6] \"I... don't want to see any of you get hurt...\""
"90002030-0182" = "..."
"90002030-0190" = "!? "
"90002030-0191" = "!? "
"90002030-0192" = "(Eimi gently hugged me.)"
"90002030-0193" = "[s] \"Eh, Eimi... ?\""
"90002030-0196" = "Your body is still... nice and soft, teacher."
"90002030-0197" = "It's okay, teacher."
"90002030-0198" = "[s] \"But...!\""
"90002030-0199" = "Yeah. I understand."
"90002030-0200" = "But it's okay. #nIf you care about us—"
"90002030-0201" = "Trust us."
"90002030-0202" = "If it's natural for a teacher to help their students, isn't it also natural for students to want to help their teacher?"
"90002030-0203" = "That's true... If something were to happen to me—"
"90002030-0204" = "I'll resent you to the fullest. You'll be responsible forever."
"90002030-0205" = "Well then, I'm off."
"90002030-0210" = "[ns] \"Eimi!\""
"90002030-0213" = "…The operation begins."
"90002030-0214" = "Yes, let's get started."
"90002030-0215" = "To ensure Eimi returns safely, we too must steel ourselves."
"90002030-0216" = "Isn't that right, teacher?"
"90002030-0217" = "[s] \"…Tell me what needs to be done.\""
"90002030-0224" = "[ns] \"Then, everyone to your positions.\""
"90002030-0225" = "Reporting on engine repair status. #nBoth emergency takeoff and landing are possible."
"90002030-0226" = "I will now proceed to the hangar to prepare for descent."
"90002030-0228" = "Yes! Aris will go with Toki!"
"90002030-0229" = "I'll do my best...!"
"90002030-0231" = "Himari, I'm leaving the rest to you."
"90002030-0232" = "…Toki and Aris are our strongest assets and our trump cards."
"90002030-0233" = "Yuzu might show unexpected performance in missions like this."
"90002030-0234" = "However... Rio, do you really need to go too?"
"90002030-0235" = "…The front lines also need a tactical commander."
"90002030-0236" = "Isn't that an emotional decision driven by your sense of responsibility or guilt?"
"90002030-0237" = "…I'm going."
"90002030-0244" = "Sigh... #nLately, I feel like my popularity is waning. What do you think?"
"90002030-0245" = "[s] \"I think it's because everyone trusts you, Himari.\""
"90002030-0246" = "Heh, let's leave it at that."
"90002030-0247" = "Now, enough chatting... shall we begin?"
"90002030-0248" = "Well then, Sensei?"
"90002030-0249" = "[s] \"Operation start!\""
"90002030-0250" = "Hangar, do you read? Please report your status."
"90002030-0256" = "We have arrived at the hangar. We will board the pods."
"90002030-0257" = "Aris, you know the procedure, right?"
"90002030-0259" = "Yes! Of course!"
"90002030-0260" = "Um... where do I start...?"
"90002030-0261" = "I-I'll teach you, Aris-chan... #nThis is like a game manual..."
"90002030-0263" = "Then Yuzu, I'm counting on you with Aris."
"90002030-0266" = "Descent preparation complete. You may proceed anytime."
"90002030-0267" = "Then—"
"90002030-0268" = "Launch!"
"90002030-0278" = "Seriously, its size is unbelievable."
"90002030-0279" = "Alright."
"90002030-0280" = "Let's be efficient."
"90002030-0281" = "First—"
"90002030-0293" = "—the enemy right in front of us."