[translation]
90002250-0001 = "Episode 25: Epilogue (1)"
90002250-0003 = "Ah, Sensei!"
90002250-0004 = "Hello! Aris and Toki, hi there!"
90002250-0005 = "Hello!"
90002250-0006 = "Hello!"
90002250-0007 = "Hello."
90002250-0009 = "By the way, did something happen? #nI couldn't get a hold of you for the past few days..."
90002250-0010 = "I was on duty at Schale the day before yesterday, you know? #nYou'd better take responsibility for leaving me waiting!"
90002250-0011 = "[s] \"Sorry, sorry. Let me make it up to you next week.\""
90002250-0012 = "Really? It's a promise!"
90002250-0020 = "Huh? Just now, something..."
90002250-0022 = "！？！？"
90002250-0023 = "N-No! Nothing passed by at all! Right, Toki!?"
90002250-0024 = "Y-Yes. That's... right."
90002250-0029 = "……？"
90002250-0030 = "Is that so...?"
90002250-0031 = "[s1] \"Y-Yeah, that's right!\"\n[s2] \"I-I didn't notice anything!?\""
90002250-0034 = "Hmm? No, but..."
90002250-0035 = "Sensei... are you hiding something?"
90002250-0036 = "Su~spi~cious~"
90002250-0038 = "Waaaah! Toki, what should we do!"
90002250-0039 = "If it comes down to it, I'll use the repaired Abi-Eshuh to physically erase their memories...!"
90002250-0040 = "I-I don't think you should do that!!"
90002250-0042 = "Ah! We can just check the security camera footage! #nYou can do that, right?"
90002250-0043 = "Easy."
90002250-0044 = "[s] \"You can do that!?\""
90002250-0045 = "Of course. We're Millennium students, after all. #n...Well? Did you see anything?"
90002250-0049 = "No... nothing in particular..."
90002250-0050 = "Oh. How boring."
90002250-0051 = "[s] \"S-See? There was nothing, right?\""
90002250-0052 = "True. It seems we were mistaken."
90002250-0053 = "Well then, Sensei, we'll be going. See you later, Aris and Toki~"
90002250-0060 = "T-That was a lifesaver..."
90002250-0061 = "We managed somehow. Lady Rio, Kei. You can come out now."
90002250-0067 = "Phew..."
90002250-0068 = "I hid with you in the heat of the moment, but why did I have to..."
90002250-0070 = "I suppose this is a form of teamwork."
90002250-0071 = "There you go talking nonsense again..."
90002250-0078 = "……。"
90002250-0079 = "Rio?"
90002250-0080 = "So it's finally come to this..."
90002250-0081 = "It's okay, Rio-senpai. #nAris will be brave with you! I'm sure it'll go—"
90002250-0087 = "Oh, Sensei. Hello. Aris-chan and Toki-san too."
90002250-0088 = "U-Uwaaaah!?"
90002250-0094 = "[ns3] \"Didn't you say you'd be brave!?\"\n[ns4] \"Hiding behind me all of a sudden...!\""
90002250-0097 = "Is something the matter? You look as if you've seen a ghost."
90002250-0102 = "Ah, no... sorry... it's not like that... um..."
90002250-0103 = "Hehe. #n...Toki-san, thank you for the report as well. #nAm I correct in understanding that was the summarized version?"
90002250-0107 = "Y-Yes... I will provide the details later..."
90002250-0108 = "[s] （Even Toki is frightened...!）"
90002250-0109 = "You both worked very hard."
90002250-0110 = "However... there's someone else I'd like to speak with—"
90002250-0114 = "First, Kei-chan. Nice to meet you. I'm [ruby=Ushio]Noa[/ruby] Noa. #nThis is the first time we've met in person."
90002250-0118 = "So I'm being called Kei-chan here too... I am [ruby=Tendou]Kei[/ruby] Kei. #nI am pleased to meet you."
90002250-0119 = "Yes, indeed. I look forward to working with you."
90002250-0120 = "And—"
90002250-0127 = "Ugh...!"
90002250-0128 = "……。"
90002250-0129 = "……。"
90002250-0130 = "It really has been... a long time, President Rio."
90002250-0131 = "W-Wait. I can... explain everything."
90002250-0132 = "There's no need to rush your explanation here."
90002250-0133 = "I-Is that so...?"
90002250-0134 = "Yes. Because there's someone else who wants to hear what you have to say."
90002250-0135 = "Does that mean..."
90002250-0136 = "Yes. She's been waiting all this time."
90002250-0140 = "Yuuka-chan has, always."
90002250-0141 = "！？！？"
90002250-0142 = "Please, come inside."
90002250-0148 = "I-I understand..."
90002250-0149 = "……Sensei, even I'm starting to get scared..."
90002250-0150 = "[s] \"Me too...\""
90002250-0151 = "By the way, President?"
90002250-0152 = "W-What is it...?"
90002250-0153 = "Yuuka-chan gets angry sometimes, and she sulks sometimes."
90002250-0154 = "But even so, she listens to my requests one way or another... She's my kind friend."
90002250-0155 = "If such a Yuuka-chan were to get truly angry—"
90002250-0156 = "There's nothing I could do about it."
90002250-0157 = "！？！？！？"
90002250-0158 = "S-Sensei...!"
90002250-0159 = "[s] \"Rio.\""
90002250-0161 = "[ns] \"There are times... when a person just has to brace themselves...!\""
90002250-0162 = "……I understand."
90002250-0163 = "If this is what I must bear..."
90002250-0172 = "Oh, President. It seems you've had a very difficult time."
90002250-0173 = "Should I start by welcoming you back to Millennium?"
90002250-0174 = "Apparently, you saved Kivotos while we weren't looking."
90002250-0175 = "I should be grateful for that."
90002250-0176 = "Yes, I'll acknowledge what needs to be acknowledged. Otherwise, we can't move on to the next topic, right?"
90002250-0180 = "Um... please listen to me. I'll explain everything—"
90002250-0181 = "President?"
90002250-0182 = "The way you're saying that makes it sound like I'm..."
90002250-0183 = "From the embezzlement you've been covering up for a long time, to various other matters—"
90002250-0184 = "It sounds like you're desperately trying to endure it."
90002250-0185 = "U-Ugh...!"
90002250-0186 = "……Now then."
90002250-0188 = "I'd like to have a long talk with you—"
90002250-0189 = "Is that okay?"
90002250-0190 = "Hieee...!"
90002250-0197 = "U-Uwaaaah! Aris is scared!"
90002250-0198 = "So this is... the rumored..."
90002250-0200 = "Sensei, what should we do...!"
90002250-0201 = "[s] \"E-Endure it...!\""
90002250-0208 = "Hehe."
90002250-0209 = "Hehehe."
90002250-0215 = "R-Rio-senpai...?"
90002250-0216 = "Are you okay? No, I don't even need to ask..."
90002250-0225 = "[ns] \"Huh? Koyuki? Why are you...?\""
90002250-0227 = "……。"
90002250-0228 = "She probably did something to get scolded for."
90002250-0229 = "[s] \"I see...\""
90002250-0231 = "[ns] \"Is Rio... safe...?\""
90002250-0236 = "……。"
90002250-0237 = "I'm fine."
90002250-0238 = "Yes... I'm... fine."
90002250-0239 = "Just as Sensei said, I was prepared..."
90002250-0240 = "You look like you've taken quite a bit of damage for someone who was prepared...?"
90002250-0241 = "……。"
90002250-0242 = "One thing..."
90002250-0243 = "I've realized clearly."
90002250-0244 = "The truth... sometimes..."
90002250-0245 = "Reaps a person's spirit... that's what I've learned..."
90002250-0250 = "[ns5] \"Rio!? Rio!!\"\n[ns6] \"Rio... ugh... Rio... *sob*...\""
90002250-0255 = "It's pitiful, but..."
90002250-0256 = "It's an undeniable fact that she brought this on herself..."
90002250-0257 = "We can only watch over her, thinking of it as a kind of penance."
90002250-0263 = "Sigh... honestly..."
90002250-0264 = "[s7] \"H-Hey, Yuuka...\"\n[s8] \"It's been... a while.\""
90002250-0267 = "……。"
90002250-0268 = "It has. Aris-chan and Toki, too."
90002250-0269 = "……！"
90002250-0270 = "H-Hello."
90002250-0271 = "Neru-senpai... no, this time it's Himari-senpai. #nI'll have to go talk to them later too."
90002250-0272 = "……Yes."
90002250-0273 = "And..."
90002250-0277 = "You're Kei-chan, right?"
90002250-0278 = "……。"
90002250-0279 = "Y-Yuuka! Kei is okay! She's safe!"
90002250-0280 = "I-If there's any problem... A-Aris will definitely do something about it!"
90002250-0281 = "[s9] \"Right, right! I'll take responsibility too!\"\n[s10] \"So for now, just calm down... and let's talk slowly...?\""
90002250-0287 = "Being that flustered makes it even more suspicious..."
90002250-0288 = "……。"
90002250-0289 = "Well, in that case, Sensei, let's talk at Schale after this."
90002250-0290 = "……！"
90002250-0291 = "Now, about Aris-chan and Kei-chan."
90002250-0292 = "Uwaaaah..."
90002250-0293 = "Don't be so scared. I know most of the circumstances."
90002250-0294 = "Yes...?"
90002250-0295 = "Eh...?"
90002250-0296 = "I-Is that so...? But then, Kei will..."
90002250-0297 = "It's the same as your case."
90002250-0298 = "Yes...?"
90002250-0303 = "We need to proceed with Kei-chan's transfer procedures."
90002250-0305 = "……？"
90002250-0307 = "……！"
90002250-0308 = "Thank you very much!"
90002250-0309 = "Yes, yes, you're a good girl for saying thank you so honestly."
90002250-0313 = "Now then, Sensei. As promised, I'll be taking some of your time."
90002250-0314 = "[s] \"Y-Yes!\""
90002250-0321 = "And then! It's been like this since a long time ago, but President Rio!"
90002250-0322 = "She doesn't care about others at all, it's always 'all's well that ends well' with her!"
90002250-0324 = "She planned to compensate and balance the books in the end... Honestly, she's not Koyuki!"
90002250-0325 = "Of course, I know she doesn't mean any harm!"
90002250-0326 = "She's a timid person to begin with, so there's no way she could do something like that."
90002250-0327 = "[s11] \"H-Here! Yuuka! Have some sweets!\"\n[s12] \"L-Look, there's a zero-calorie one here too!\""
90002250-0332 = "Thank you. *munch munch*..."
90002250-0333 = "Phew..."
90002250-0334 = "[s13] （After talking for several hours...）\n[s14] （I succeeded in improving Yuuka's mood...）"
90002250-0337 = "Sigh... it's troubling..."
90002250-0338 = "Normally, we would have to hold her responsible for the damages caused by an officer's absence, but..."
90002250-0339 = "There's a problem with that..."
90002250-0340 = "Millennium hasn't actually suffered any significant damage."
90002250-0341 = "Even in this case, if you ask if there was any actual harm to Millennium, it was negligible..."
90002250-0342 = "[s15] \"In that case...\"\n[s16] \"Removing Rio from her position as President...?\""
90002250-0347 = "No? There's no one more suitable than President Rio."
90002250-0348 = "Even if you look at me with such surprise..."
90002250-0349 = "Millennium is a meritocratic school to begin with. #nIn terms of sheer ability, no student can match President Rio."
90002250-0350 = "And regarding this incident, we can't complain about the President's achievements."
90002250-0351 = "I only have an overview so far, but—"
90002250-0352 = "She saved the world, Kivotos."
90002250-0353 = "[s17] \"Thank you for thinking that way.\"\n[s18] \"But I have another concern...\""
90002250-0356 = "Yes? Whether President Rio can manage her daily life...?"
90002250-0357 = "What do you mean by that..."
90002250-0358 = "Sigh... I see..."
90002250-0359 = "You never know until you try."
90002250-0360 = "And she has you as a guardian, Sensei!"
90002250-0361 = "[s] \"Right. I think Rio has learned a lot too.\""
90002250-0363 = "[ns] \"It'll be fine... probably...\""
90002250-0364 = "Yes, let's start by believing in her. #n...Though I understand how you feel."
90002250-0365 = "Then there's the matter of Kei-chan's transfer procedures."
90002250-0366 = "The progress of the procedures is..."
90002250-0367 = "……。"
90002250-0368 = "There are some ambiguous parts in the rules."
90002250-0371 = "After all, it's as if a student suddenly appeared at Millennium."
90002250-0372 = "……I don't really like the expression, but she's a student who appeared like 'magic'."
90002250-0373 = "Millennium's school regulations don't cover how to handle such a case."
90002250-0376 = "[ns] \"Normally, you wouldn't expect that...\""
90002250-0377 = "Yes. So, treating it as a special case, I had the person with final decision-making authority decide."
90002250-0378 = "It was a help that President Rio had returned."
90002250-0379 = "If the President hadn't been here... who would decide, how responsibility would be taken, how the situation would be monitored, and so on..."
90002250-0380 = "It would have been a meeting lasting at least four days and three nights."
90002250-0381 = "Thanks to her, that situation was avoided."
90002250-0382 = "[s] \"I can guess the result, but... what did Rio say?\""
90002250-0383 = "……Ahem."
90002250-0384 = "Millennium's founding principle is to accept any student who has the will to learn."
90002250-0388 = "Kei is no exception; she is welcomed as a student of Millennium Science School. #n...She said."
90002250-0389 = "[s] \"That was fast!\""
90002250-0390 = "We already went through the procedures for Aris-chan."
90002250-0391 = "Even if it's not explicitly written in the rules, having a precedent makes things easier."
90002250-0392 = "Also, we've been talking about other people this whole time... but there's another reason I'm here, you know?"
90002250-0393 = "[s] \"Which is...?\""
90002250-0394 = "……。"
90002250-0399 = "Do you have any idea... how worried I was!?"
90002250-0400 = "Even back then! Just when I thought I'd finally located you! It was a tundra region!?"
90002250-0401 = "Without considering my feelings, you just said you'd handle it... and didn't even explain the situation..."
90002250-0402 = "I understand it wasn't a situation where you could. #nAnd... thanks to you, Sensei, the crisis of the Steel Continent was resolved."
90002250-0403 = "But..."
90002250-0405 = "I was worried..."
90002250-0406 = "[s] \"……Sorry.\""
90002250-0407 = "I don't care anymore..."
90002250-0408 = "[s] \"I won't do it again.\""
90002250-0409 = "If something similar happens again, you'll just repeat the same thing, won't you...?"
90002250-0410 = "[s19] \"I... can't deny that...\"\n[s20] \"But I'll try... not to disappear without a word.\""
90002250-0413 = "……Really?"
90002250-0414 = "[s] \"Y-Yeah!\""
90002250-0415 = "……I understand."
90002250-0418 = "In exchange, tell me everything. About what happened on the Steel Continent. #nThen... I'll forgive you."
90002250-0419 = "……Yes? Ah, I have already received a report, but... it was a 'Millennium-style' report."
90002250-0420 = "Omitting modifiers as much as possible... stating only facts... recording only cause and effect..."
90002250-0421 = "The idea that words are resources, and resources should be consumed rationally and efficiently—"
90002250-0422 = "It was a report very typical of Millennium."
90002250-0423 = "[s] \"Understood. ...But it'll be long, you know?\""
90002250-0424 = "Hehe, as long as it takes."
90002250-0428 = "[ns] \"Well then... where should I start?\""
90002250-0430 = "（Yuuka laughed, was moved, sometimes doubted... and sometimes, shed tears.）"
90002250-0431 = "（I told Yuuka everything that happened.）"
90002250-0448 = "（The Steel Continent, Decagrammaton, Ein, Sof, Ohr.）"
90002250-0449 = "（And about Kei.）"
90002250-0453 = "……Sensei."
90002250-0454 = "[s] \"Yeah?\""
90002250-0455 = "Are you asleep?"
90002250-0456 = "[s] \"I'm a bit sleepy, but... not yet...\""
90002250-0457 = "I see."
90002250-0458 = "Please rest for today."
90002250-0459 = "……You don't need to worry."
90002250-0466 = "Kei-chan, no matter what... by any means necessary."
90002250-0467 = "I will make sure she has a place at Millennium. Together with Aris-chan."
90002250-0468 = "Sensei, thank you for your hard work. And..."
90002250-0472 = "Thank you."
90002250-0474 = "Next: Epilogue (2)"