[translation]
90002010-0001 = "Episode 1;Phase Shift"
90002010-0004 = "Sof! I've told you this so many times!#nBig sister is going to get angry soon, you know?"
90002010-0005 = "I'm sorry, Big Sister Ein!#nPlease forgive me, I won't do it again..."
90002010-0006 = "J-Just this once, okay?#nHehe, big sister knows Sof is a good girl."
90002010-0007 = "And Ohr! Don't bully Sof too much.#nYou're overdoing it too, Ohr!"
90002010-0008 = "But Sof started it..."
90002010-0009 = "Ohr!"
90002010-0010 = "F-Fine, I get it...#nI'm sorry... Is this enough?"
90002010-0011 = "Hmm... well, you still don't seem very remorseful..."
90002010-0012 = "You tried hard for Ohr! Good job, good job."
90002010-0018 = "Ein? What are you doing?"
90002010-0019 = "Kyaaaah!? Big Sister Malkuth!?"
90002010-0022 = "I see. Is this the 'playing house' that humans often do?"
90002010-0023 = "And these mechanical dolls are Sof and Ohr, respectively, aren't they?"
90002010-0024 = "Y-Yes... I'm sorry, Big Sister Malkuth..."
90002010-0025 = "Please don't apologize. If Ein was enjoying herself, then I am happy too."
90002010-0026 = "So... what about this mechanical doll?"
90002010-0027 = "Yes! Those children are... um..."
90002010-0028 = "Th-They're my sisters!"
90002010-0029 = "I see...?"
90002010-0030 = "S-So, they're also Big Sister Malkuth's sisters!"
90002010-0031 = "Hmm...?"
90002010-0032 = "Um... these children are my sisters... and I'm Big Sister Malkuth's sister, so..."
90002010-0033 = "I know, Ein. So I am the 'eldest sister', correct?"
90002010-0034 = "Y-Yes! That's right!"
90002010-0035 = "Then...#nNice to meet you. I am Malkuth."
90002010-0036 = "B-Big Sister is greeting her younger sisters...!#nWh-What should I do... I'm so happy, my circuits might short-circuit...!"
90002010-0037 = "By the way, Ein?"
90002010-0038 = "Yes!"
90002010-0039 = "Do I not have a doll?"
90002010-0045 = "I-I-I-I'm so sorry, Big Sister! I n-never thought it would come to this... I'll m-make one right away!"
90002010-0046 = "It's alright."
90002010-0047 = "We are currently awaiting 'the final moment'."
90002010-0048 = "I believe it's just right to relax a little."
90002010-0049 = "B-But... we urgently need to change the phase of the 'Power of the Nameless Gods' flowing through the Steel Continent..."
90002010-0050 = "Ugh... If only the p-princess and her lady-in-waiting weren't here..."
90002010-0051 = "I trust Ein. I'm not worried at all."
90002010-0052 = "Besides, Ein will make a 'Malkuth mechanical doll' for me, won't she?"
90002010-0053 = "..."
90002010-0054 = "O-Of course! Big Sister!"
90002010-0055 = "But if that's the case... the Malkuth mechanical doll will become Ein's other younger sister."
90002010-0056 = "--Hello, Big Sister Ein."
90002010-0057 = "Kya-Kyaaaah!?"
90002010-0058 = "Big Sister Malkuth called m-me 'Big Sister'..."
90002010-0063 = "Perhaps I went a bit too far with my joke..."
90002010-0065 = "..."
90002010-0066 = "Sigh... What should I do..."
90002010-0067 = "..."
90002010-0068 = "Tiphareth..."
90002010-0075 = "Sof? What are you doing?"
90002010-0076 = "Whoa!? Big Sister Malkuth!?"
90002010-0077 = "Uh, um..."
90002010-0078 = "What you're holding is... a sealed box for something?"
90002010-0079 = "It seems a bit cracked, but... what is it?"
90002010-0080 = "This is... um..."
90002010-0081 = "...A box containing seeds.#nIt's one of the ones Tiphareth sent us."
90002010-0082 = "You know too, Big Sister, don't you?#nThat Tiphareth prioritized the seeds over herself..."
90002010-0083 = "Yes. And we decided to respect that choice."
90002010-0084 = "But there were a few boxes that weren't stored well."
90002010-0085 = "...This is the worst one among them."
90002010-0086 = "What do you mean by 'poor storage condition'?"
90002010-0087 = "...They're in a state where they could sprout at any moment."
90002010-0088 = "But even if they sprout on the Steel Continent..."
90002010-0089 = "Ah, I-I know it's not like me to worry about something like this!"
90002010-0090 = "But Tiphareth..."
90002010-0091 = "..."
90002010-0092 = "Sof.#nTiphareth is, indeed, with us even at this very moment."
90002010-0093 = "Yeah..."
90002010-0094 = "And I understand your desire, Sof, to cherish Tiphareth's will."
90002010-0095 = "So, how about we do this?"
90002010-0101 = "How about secretly... planting the seeds in the Holy Land?"
90002010-0102 = "B-Big Sister!? But that's...!"
90002010-0104 = "Yes, I know.#nIt is an act that could potentially violate our rules."
90002010-0105 = "However, the Holy Land is the origin of the Steel Continent, and it is also the only place where 'soil' still remains."
90002010-0106 = "That's because Netzach's abilities weren't used there..."
90002010-0107 = "In the Holy Land, that person's will..."
90002010-0108 = "Then, how about we consider it this way?"
90002010-0109 = "If the seeds overcome all hardships and take root...#nthat would be the moment Tiphareth's remaining free will bears fruit."
90002010-0110 = "Free will is an important element not only for humans but also for us, and ultimately, for that person as well."
90002010-0111 = "Even if, in the end, all of it is a lie born of illusion."
90002010-0112 = "But... is it really okay...?"
90002010-0113 = "Of course, it's not a good thing."
90002010-0114 = "Big Sister!?"
90002010-0115 = "This is a 'bad thing' we will do together."
90002010-0116 = "A bad... thing...!"
90002010-0117 = "And bad things are, for some reason, apparently 'fun'."
90002010-0118 = "Yeah. They call it a sense of immorality, apparently..."
90002010-0119 = "So, just this once, let's do something bad together."
90002010-0120 = "Tiphareth is still with us."
90002010-0121 = "But... you're troubled because you don't want to forget Tiphareth, aren't you?"
90002010-0122 = "And above all, we are awaiting 'the final moment'."
90002010-0123 = "You were the one who said it first, Big Sister, remember...?"
90002010-0124 = "Yes. Let's play a prank together, like good sisters."
90002010-0125 = "Okay!"
90002010-0130 = "Anyway..."
90002010-0131 = "Is the phase conversion of the 'Power of the Nameless Gods' progressing smoothly?"
90002010-0132 = "Oh, that? You don't need to worry, Big Sister. Even if those two arrive at the Steel Continent, they shouldn't be able to freely manipulate the energy."
90002010-0133 = "...It's a shame we couldn't convert it completely from the root."
90002010-0134 = "But if we're not careful, the Steel Continent, which is built with that power,#nmight become unusable..."
90002010-0135 = "I see. Then, let us compensate for what is lacking."
90002010-0136 = "Yeah..."
90002010-0140 = "Ohr? What are you doing?"
90002010-0141 = "..."
90002010-0142 = "..."
90002010-0143 = "I see, you're lost in your own world."
90002010-0144 = "Then, excuse me."
90002010-0152 = "Mumble mumble..."
90002010-0157 = "Ahem. Ohr? What are you doing?"
90002010-0158 = "Huh...?"
90002010-0162 = "Wha!? Big Sister Malkuth!? Why are you here...!?"
90002010-0163 = "There's no need to be surprised."
90002010-0164 = "As a rule, I can go anywhere on this Steel Continent."
90002010-0165 = "That's true, but..."
90002010-0166 = "Hmm... This is a very... 'natural' world, isn't it?"
90002010-0167 = "...Do you think so too, Big Sister?"
90002010-0168 = "We have a part in our consciousness circuits that could be called a 'black box', don't we?"
90002010-0169 = "Yes. To borrow a human expression, it could be called the unconscious realm."
90002010-0170 = "Curious about what it was like, I extracted a part of my consciousness circuit as big data."
90002010-0171 = "And such an inner world was reproduced just from that?"
90002010-0172 = "That's right.#nSof talks about life and nature so much, it seems I've been influenced too."
90002010-0173 = "For all that, it's not a particularly impressive landscape, though."
90002010-0174 = "But, well..."
90002010-0175 = "However..."
90002010-0176 = "When I'm here, I feel like the noise in my thought circuits quiets down..."
90002010-0177 = "I feel the same way."
90002010-0178 = "By the way, I heard from Ein and Sof that you are converting the phase of the 'Power of the Nameless Gods'."
90002010-0179 = "Eh? Oh, yes...#nSigh, to have to do something like this at the very end..."
90002010-0180 = "I also had to readjust Big Sister's body...#nWell, it won't take long."
90002010-0181 = "This is all because of that human called Professor [USERNAME]! Honestly!"
90002010-0182 = "Now, now, don't get so angry."
90002010-0183 = "If we talk sincerely, Professor [USERNAME] should understand us too."
90002010-0184 = "So, why don't we sunbathe together?"
90002010-0185 = "Sunbathing, you say?"
90002010-0186 = "It's the act of lying down and basking in the sun without doing anything."
90002010-0187 = "It's merely the 'sensation of being bathed in light' provided as an electrical signal--"
90002010-0188 = "and the sensory circuit that receives that signal is simply returning a feedback signal of 'satisfaction'."
90002010-0189 = "Nevertheless, just being able to spend time with Ohr, I believe, is a sufficiently meaningful act."
90002010-0193 = "Yes! Of course, Big Sister!"
90002010-0194 = "Then, let's do that."
90002010-0198 = "After all, we are awaiting 'the final moment'."
90002010-0201 = "Next Time;The Winds of Change Are Blowing"