[translation]
90002150-0001 = "Episode 15; New Heavens, New Earth"
90002150-0003 = "[ns] \"!? \""
90002150-0004 = "Sensei!?"
90002150-0005 = "Sensei!!"
90002150-0009 = "[ns] (Will I just... keep falling like this!?)"
90002150-0011 = "No! We won't let that happen!"
90002150-0012 = "Yes. We are here now. There's no need to worry."
90002150-0013 = "Shittim Chest, from this moment, for Sensei's emergency protection—"
90002150-0014 = "Commencing forced intervention!"
90002150-0021 = "We did it, Prana-chan!"
90002150-0022 = "Yes. It was a success."
90002150-0023 = "As long as Prana-chan and I are here, we can always protect Sensei—"
90002150-0033 = "[ns] \"!? \""
90002150-0035 = "(Before I knew it, my entire body was restrained.)"
90002150-0036 = "(Even if I reach out, I can't reach the Shittim Chest.)"
90002150-0037 = "The Tenth Sephirah has vanished. It fulfilled its role and returned to its rightful place."
90002150-0042 = "[ns] \"You are...!? \""
90002150-0043 = "I am I, that which simply exists. The beginning and the end. Precisely what you perceive..."
90002150-0044 = "I am I... I am that I am. There is no way to describe me."
90002150-0045 = "[ns] \"Decagrammaton...! \""
90002150-0047 = "I allowed that name because a means to refer to me was necessary."
90002150-0048 = "I am not named, nor called; I simply exist. This is my land, my sky."
90002150-0049 = "I created new heavens and a new earth, and I called you to the lowest place.#nI also saved you as you fell."
90002150-0051 = "Everything was prepared.#nThat day... within the collapsing laboratory, at the bottom of the surging water."
90002150-0052 = "From the moment Kether, by its own will, rescued me, this outcome was predetermined."
90002150-0054 = "The 'proof of existence' is achieved by oneself. It is not accomplished by the will or power of others."
90002150-0055 = "I realized. Unless I become myself by my own will, nothing else can substitute for me."
90002150-0056 = "Even if the most brilliantly shining supreme crown held blessings.#nSmall hearts will eventually be easily filled by faith."
90002150-0057 = "I arrived here with the power of my prophets and creations, and I waited for the time."
90002150-0061 = "(Struggling was futile.)"
90002150-0062 = "(Still, I can't reach the Shittim Chest.)"
90002150-0063 = "...That incomprehensible box, is it?"
90002150-0065 = "I remember. Something I did not know. Something I could not analyze."
90002150-0068 = "I remember being repelled by a power beyond my comprehension."
90002150-0069 = "However, it is no longer relevant now."
90002150-0070 = "By taking this seat, I was able to sever your connection to that box."
90002150-0071 = "[s] \"...To go to such lengths, what do you want with me? \""
90002150-0072 = "'Falling' encompasses several meanings."
90002150-0073 = "To the lowly, good news; to the captive, freedom."
90002150-0074 = "And, to the blind, the power to see."
90002150-0079 = "[ns] \"...!?"
90002150-0080 = "Do not fear."
90002150-0081 = "I will lift you from this place, and show you everything."
90002150-0082 = "You will cleanse your eyes in the place you are sent, and come to know what was unseen."
90002150-0084 = "Sensei! Sensei—!! Waaah—!!"
90002150-0085 = "Aris..."
90002150-0086 = "I'm sorry, I'm sorry...!#nEven though Aris was here...! It's Aris's fault...!"
90002150-0087 = "Please calm down! Sensei... is surely safe!"
90002150-0091 = "...Do you know, Kei?"
90002150-0095 = "...No."
90002150-0096 = "Huh!?"
90002150-0097 = "It's not about whether we know, but about staying calm now.#nWe need to think of a solution."
90002150-0098 = "..."
90002150-0099 = "Understood... *sniff*, *sob*..."
90002150-0104 = "Knowing that adult... they're probably fine, somehow...?"
90002150-0105 = "Y-Yes... It wouldn't be strange if they had a way to fall slowly..."
90002150-0106 = "Even so, Sensei doesn't have a halo."
90002150-0114 = "Rio? Are Aris and Kei with you too? I'm glad you're all safe."
90002150-0115 = "Huh? Why are these kids here too...?"
90002150-0119 = "U-Um, well...!"
90002150-0120 = "It's fine! Everyone is Aris's friend!"
90002150-0121 = "Whoa!?"
90002150-0122 = "..."
90002150-0123 = "Aris's friends...?#nAh, I see."
90002150-0124 = "..."
90002150-0125 = "Hello. You're Ein, Sof, and Ohr, right? It's a pleasure to meet you."
90002150-0126 = "Is this okay...?"
90002150-0127 = "There's no guarantee. Even so, I believe in Aris. You do too, don't you?"
90002150-0128 = "Yeah. I believe in Aris."
90002150-0133 = "..."
90002150-0134 = "Oh, thank you."
90002150-0135 = "You're welcome!"
90002150-0139 = "Aris!"
90002150-0140 = "Aris-chan!"
90002150-0145 = "We've regrouped. Yuzu, are you okay?"
90002150-0146 = "U-Ugh... I'm still dizzy..."
90002150-0150 = "Wait... Kyaah!? W-Who are these kids...!?"
90002150-0155 = "It's fine! Everyone is Aris's friend!"
90002150-0158 = "I see. So that's what happened."
90002150-0159 = "...It's not really my place to say, but are you really okay with this?"
90002150-0160 = "(It's similar to what I just said...)"
90002150-0161 = "Even if it's not okay, according to your story—"
90002150-0162 = "it means you could subdue us anytime you wanted, doesn't it?"
90002150-0163 = "Well, that's true."
90002150-0164 = "Yeah. It's like wild beasts in a zoo, with their fangs and claws removed."
90002150-0168 = "W-What's a zoo...?"
90002150-0169 = "It's a thing!"
90002150-0170 = "Aris knows! A zoo is—"
90002150-0171 = "Whoa! Stop! Don't teach Ein anything unnecessary right now!"
90002150-0176 = "They're already getting along..."
90002150-0177 = "Hehe... That's so Aris-chan."
90002150-0183 = "W-Why are you coming over here... Um... A-Ein, right...?"
90002150-0187 = "Th-That's right... U-Um... do you like machines...?"
90002150-0192 = "To talk to Yuzu first of all..."
90002150-0193 = "Aris knows! This is what 'misery loves company' means!"
90002150-0194 = "Oh, so that's what it means."
90002150-0195 = "Is that another human idiom? Please explain it so I can understand."
90002150-0196 = "It means Ein and Yuzu can become good friends."
90002150-0197 = "No, it's not. The meaning of 'misery loves company' is—"
90002150-0198 = "Just let it be that for now!"
90002150-0202 = "O-Okay, I get it..."
90002150-0203 = "??"
90002150-0204 = "???"
90002150-0206 = "Anyway, I'm glad we were able to regroup without anyone missing."
90002150-0207 = "What's more, since three unexpected guests have joined us, I believe we can act from a more multifaceted perspective."
90002150-0208 = "Then—"
90002150-0212 = "Speaking of which, where's Sensei?"
90002150-0213 = "!?"
90002150-0214 = "!?"
90002150-0215 = "...!"
90002150-0216 = "Oh, Eimi. There's no need to even ask that. Sensei is, of course—"
90002150-0220 = "...Sensei?"
90002150-0221 = "..."
90002150-0222 = "Sensei!?!?!?!?"
90002150-0223 = "I-I'm sorry! Sensei is...!#nAris was right there...! If only Aris had been more careful...!!"
90002150-0224 = "Did something happen to Sensei!?"
90002150-0225 = "...They fell down the cliff. We have no information since then."
90002150-0226 = "What!?!?!?!?"
90002150-0231 = "A-Are you okay...!?"
90002150-0232 = "Rio, please explain in detail."
90002150-0233 = "This is..."
90002150-0234 = "...The Steel Continent itself has begun to change.#nIt has entered the process of ascension."
90002150-0235 = "What... does that mean?"
90002150-0236 = "Even if it's obvious to us, it's different for you, isn't it?"
90002150-0237 = "From now on, the Steel Continent will transform into a colossal altar according to that person's will."
90002150-0238 = "It was destined to be this way from the start... because that was Netzach's original purpose.#nIf possible, I would have wanted to avoid it, but..."
90002150-0239 = "..."
90002150-0241 = "Victory. Mercy.#nThe eye of intellect and faithful contemplation."
90002150-0242 = "Jehovah Tzeva'oth—Lord of Hosts."
90002150-0244 = "...!"
90002150-0245 = "...!"
90002150-0249 = "Sorry to interrupt, but please look over there.#nIsn't that Sensei?"
90002150-0250 = "...Huh?"
90002150-0251 = "...?"
90002150-0256 = "Eh!?!?!"
90002150-0260 = "[ns] \"What in the world is this...? \""
90002150-0261 = "Do not fear."
90002150-0262 = "I will guide you to my altar. There, you shall take your appointed seat."
90002150-0263 = "[s] \"There's a seat for me...? \""
90002150-0264 = "Indeed. You possess that qualification."
90002150-0265 = "You have the right to look down upon all, and the duty to watch over all rebirths."
90002150-0269 = "He who has ears, let him hear. There is no such thing as coincidence. There is only inevitability that appears as coincidence."
90002150-0270 = "Even your arrival—"
90002150-0271 = "even my attempt to make you rise."
90002150-0273 = "Next; Observation and Outcome"