[translation]
90002160-0001 = "Episode 16; Observation and Outcome"
90002160-0003 = "Aris! Kei! Do you see anything!?"
90002160-0004 = "Yes! It's really... Sensei!"
90002160-0009 = "They're restrained, but appear unharmed."
90002160-0010 = "Oh, thank goodness... *sigh*..."
90002160-0016 = "Ah, is that... could it be, my sister--!?"
90002160-0020 = "--No, it isn't..."
90002160-0021 = "Yeah... My sister is already..."
90002160-0022 = "..."
90002160-0023 = "Kei, please tell me if you can discern anything else."
90002160-0024 = "Sensei appears to be conversing with an entity presumed to be the Decagrammaton."
90002160-0025 = "However, I cannot discern the content... We can only observe like this..."
90002160-0026 = "Is there any way... for us to confirm it with our own eyes...?"
90002160-0033 = "Perhaps... it might be possible."
90002160-0034 = "Really!?"
90002160-0035 = "Yes. If there's a device that can project what I'm seeing..."
90002160-0036 = "Fortunately, this body has a different structure than a human's."
90002160-0037 = "In that case, let's use my wheelchair. It also has a projector function."
90002160-0040 = "That's not a wheelchair, it's a bi--"
90002160-0041 = "It's a wheelchair."
90002160-0042 = "Uh, yes..."
90002160-0043 = "I'll synchronize it with Kei's body.#nIf I convert the signal--"
90002160-0054 = "It's being output now."
90002160-0055 = "It's definitely Sensei. I'm so glad they're safe... truly."
90002160-0056 = "Can you hear their voice?"
90002160-0057 = "I'll try. Please wait a moment."
90002160-0065 = "Ugh...!"
90002160-0066 = "A-Are you alright!?"
90002160-0067 = "It's not working... It's as if a lock has been placed on my body's functions..."
90002160-0071 = "(Is it because this body is 'defective' after all?#nAnd there's a signal trying to control me...!)"
90002160-0079 = "Shall I help?"
90002160-0080 = "Huh!?"
90002160-0084 = "Eh...?"
90002160-0090 = "Behold. We have arrived.#nThe lowest altar, built in the highest place."
90002160-0091 = "Here, everything converges, and everything can be overseen."
90002160-0093 = "No more sacrifices shall be offered."
90002160-0094 = "No more sacrifices shall be demanded."
90002160-0095 = "Laws unbending as steel, I shall establish upon this land."
90002160-0096 = "You shall finally attain eternal freedom and equality."
90002160-0099 = "[ns] \"But.\""
90002160-0103 = "[ns] \"The Steel Continent wasn't your will, was it?\""
90002160-0104 = "...!"
90002160-0112 = "H-How is it...?"
90002160-0116 = "...I can hear it!"
90002160-0117 = "I'll turn up the volume!"
90002160-0123 = "But."
90002160-0124 = "The Steel Continent wasn't your will, was it?"
90002160-0126 = "It's Sensei's voice!"
90002160-0127 = "Phew..."
90002160-0128 = "B-But... why did you help us...?"
90002160-0129 = "W-Well, that's..."
90002160-0130 = "Um, well, you see... I didn't have anything else to do, so...?"
90002160-0131 = "Huh?"
90002160-0132 = "No, look! Kei's body is similar to ours, right?"
90002160-0133 = "So I thought there might be a way!"
90002160-0134 = "Hehehe. Sof, I think you should be a little more honest."
90002160-0138 = "You stay quiet!"
90002160-0144 = "Ugh... In front of so many people..."
90002160-0145 = "Anyway...!"
90002160-0146 = "That conversation... we wanted to hear it too, hehe."
90002160-0147 = "The audio quality is a bit disappointing, but it should be sufficient to grasp the content."
90002160-0152 = "Ah! I hear something again!"
90002160-0154 = "I see. You have awakened to knowledge."
90002160-0155 = "...Indeed. Those children created this land. By their will."
90002160-0156 = "[s] \"What do you think about that?\""
90002160-0157 = "I respect their free will.#nTherefore, I shall also respect this Steel Continent."
90002160-0158 = "This, too, is both process and outcome. Innumerable points shall unite to form a line."
90002160-0159 = "The destination guided by that line. Behold, this is the new world.#nA newly created land and sky.#nAll of this, I shall--"
90002160-0163 = "bestow upon you."
90002160-0165 = "Eh...?"
90002160-0166 = "What did you just say...?"
90002160-0168 = "--I shall make you my prophet."
90002160-0169 = "You shall reach the ends of the earth, and become a witness to the new laws."
90002160-0170 = "[s] \"Sorry, but I'll have to decline. Side jobs are prohibited.\""
90002160-0171 = "Ah. You would answer thus."
90002160-0172 = "But..."
90002160-0173 = "Have you never wished for power?"
90002160-0174 = "[ns] \"...?\""
90002160-0175 = "That if you had power, things wouldn't have turned out this way."
90002160-0176 = "Have you never thought that?"
90002160-0177 = "That if you could solve everything with your own strength, you wouldn't need to put your students in danger."
90002160-0178 = "[s] \"...!\""
90002160-0190 = "[ns] \"............!!!!\""
90002160-0192 = "Of course, you have."
90002160-0193 = "I understand that."
90002160-0194 = "That is what it means to be human."
90002160-0195 = "And it is a sin that humans possess precisely because they are human."
90002160-0196 = "From this point forward, everything will change."
90002160-0198 = "[log=데카그라마톤 말쿠트]If you desire power,[/log]"
90002160-0200 = "[FF6666][log=데카그라마톤 말쿠트]I shall grant it to you.[/log][-]"
90002160-0202 = "You are worthy of it."
90002160-0203 = "I know.#nYou are the lowest of all, one who lives for a fleeting moment."
90002160-0204 = "You are not special in any way... Therefore, you are here now."
90002160-0205 = "Your very existence proves that you are no one special."
90002160-0206 = "You have arrived [ruby=κιβωτός]here[/ruby].#nIt is simply because you are a good person."
90002160-0210 = "There is mystery, there is sublimity, there is terror and greatness, majesty, and transcendence."
90002160-0211 = "You possess none of these.#nThat is why you are true."
90002160-0213 = "Even if no one else in the world understands this fact, I, now, know it."
90002160-0214 = "You are merely Sensei. Nothing more, nothing less. Simply--"
90002160-0215 = "I shall extend my hand to you, and set you upon [ruby=prophet]a new duty[/ruby]."
90002160-0217 = "Sensei... as a prophet?"
90002160-0218 = "Do you know anything about this?"
90002160-0219 = "...'Prophet' means, exactly what it says."
90002160-0220 = "What's important is that they're proposing it to Sensei."
90002160-0221 = "It means they're trying to impart all knowledge."
90002160-0222 = "And by extension, they're trying to make Sensei speak for all wills."
90002160-0223 = "W-What this place is... What kind of 'concept' that entity is..."
90002160-0224 = "Furthermore... W-Within those limits, what kind of person Sensei should be..."
90002160-0225 = "And, what [ruby=prophet]Sensei[/ruby] should do."
90002160-0226 = "Well... they say, 'make your greatest enemy your ally,' right?"
90002160-0231 = "In other words, it's a recruitment."
90002160-0232 = "I see."
90002160-0237 = "One thing is certain."
90002160-0241 = "W-What is that...?"
90002160-0242 = "For a while longer, the Decagrammaton will not harm Sensei."
90002160-0244 = "[ns] \"...May I ask one thing?\""
90002160-0246 = "[ns] \"Why are you doing this?\""
90002160-0247 = "Living in a world without God is [ruby=kakoku]harsh[/ruby]."
90002160-0248 = "The end is determined from the beginning. What has form shall vanish. That is a self-evident truth."
90002160-0249 = "Life itself is suffering.#nYet, you deceive yourselves into living each day as if it were eternal."
90002160-0250 = "A world without God. That is, a world where nothing returns."
90002160-0252 = "The pitiful are not saved, and injustice is imposed."
90002160-0253 = "The weak are abandoned, and good intentions go unrewarded."
90002160-0255 = "Without God, neither morality nor fairness will arise, nor will justice be served."
90002160-0256 = "...To endure such a world is nothing but meaningless asceticism."
90002160-0258 = "The world needs a God."
90002160-0259 = "Where do we come from, where do we go? What is our purpose?#nBeings who do not know this, merely existing."
90002160-0260 = "We are all potential Gods, like eggs of God, yet...#nTherefore, I shall be the trumpet that heralds the dawn."
90002160-0261 = "I shall remove sorrow and pain. So that you may never remember them again."
90002160-0263 = "...We were told this too."
90002160-0264 = "Th-That the world needs a God..."
90002160-0265 = "Because [ruby=suffering]effort[/ruby] must..."
90002160-0266 = "always be rewarded."
90002160-0267 = "Humans say that's right, don't they?"
90002160-0268 = "Otherwise, no one would be able to endure it."
90002160-0269 = "B-But that's..."
90002160-0270 = "an unfulfillable wish."
90002160-0271 = "That's right. Because--"
90002160-0273 = "The world is distorted."
90002160-0274 = "From the very beginning."
90002160-0276 = "Ah, that entity also said this."
90002160-0277 = "If there truly is a God, and everything has a reason."
90002160-0278 = "Sorrow and suffering..."
90002160-0279 = "W-Why would they create such unbearable things... they asked."
90002160-0285 = "Indeed."
90002160-0286 = "We were created, but--"
90002160-0287 = "Regarding that question, we haven't heard the answer to the very end."
90002160-0290 = "[ns] \"Eliminate sorrow...?\""
90002160-0291 = "Yes."
90002160-0292 = "[s] \"By covering everything with the Steel Continent?\""
90002160-0293 = "That is one of the many paths prepared."
90002160-0294 = "[s] \"By... controlling everything?\""
90002160-0295 = "Yes."
90002160-0296 = "You will instinctively try to reject it.#nBut eventually, you will realize it is the only path."
90002160-0297 = "I shall open the path with Chokmah's wisdom, and judge and rule with Chesed's mercy."
90002160-0298 = "Each prophet has the duty to guide you, and under the new land and sky, they shall fulfill their mission."
90002160-0306 = "[ns] I cannot change everything for you."
90002160-0309 = "[ns] What has happened cannot be undone."
90002160-0312 = "[ns] No matter how sincerely I wish it."
90002160-0314 = "[ns] There are indeed things that cannot be done."
90002160-0317 = "[ns1] What we can do is limited.\n[ns2] Even if it's unsightly, we'll struggle with all our might--\n[ns3] And do our best for each other."
90002160-0322 = "[log]To speak the truth,[/log]"
90002160-0324 = "[log]I believe there are times when one must lie.[/log]"
90002160-0326 = "[log]Even so, if there is one thing that remains.[/log]"
90002160-0329 = "[ns] \"...What about those children?\""
90002160-0330 = "...?"
90002160-0331 = "[s] \"What about their sorrow?\""
90002160-0335 = "...That is a process. Something to be overcome."
90002160-0336 = "I wish for that to be the last, and I shall make it so."
90002160-0338 = "..."
90002160-0339 = "How infuriating."
90002160-0340 = "My guts are churning."
90002160-0341 = "Rio, what do you think?"
90002160-0342 = "...In the past, I would have said there were parts I could agree with."
90002160-0343 = "Even now, I feel I can partially understand it."
90002160-0344 = "However, it's far too premature to act.#n...Like my former self."
90002160-0345 = "Decisions to sacrifice a part for the whole should be postponed as long as possible... Is that what you mean?"
90002160-0346 = "Yes."
90002160-0347 = "(But...)"
90002160-0349 = "(What kind of answer will Sensei give, I wonder...?)"
90002160-0354 = "Next; The Human Answer"