[translation]
90002210-0001 = "Episode 21; Conflict"
90002210-0002 = "You mere fake god...!!!"
90002210-0007 = "You killed them!"
90002210-0008 = "You're the one who killed them!"
90002210-0009 = "Don't presume to call yourself a god after that!!"
90002210-0013 = "I never asked for pruning!!"
90002210-0014 = "I will never accept that contradictions should just be cut away!!!"
90002210-0030 = "I will be happy."
90002210-0031 = "No matter what! I will!"
90002210-0032 = "Even if I wander through contradictions, even if I face any obstacle!"
90002210-0033 = "Foolish."
90002210-0034 = "The price of sin is death. The conclusion has already been decided."
90002210-0035 = "If that is the conclusion you envision—"
90002210-0040 = "[log]If we choose for ourselves and end up destroying ourselves as a result...[/log]"
90002210-0043 = "[log]It's far better than entrusting our choices to someone else just to be protected.[/log]"
90002210-0046 = "No matter what happens, I will continue to seek my own conclusion!!"
90002210-0047 = "!?"
90002210-0048 = "Why... can you move? Impossible."
90002210-0049 = "Ugh...!"
90002210-0056 = "Sen...sei...?"
90002210-0057 = "[ns1] \"...Mourn those who have vanished.\"\n[ns2] \"It's sad, but that is our limit.\""
90002210-0060 = "It's dangerous... Please, stay back..."
90002210-0061 = "[s] \"Could you let it slide, just this once?\""
90002210-0062 = "...Sigh, you're not the type to listen, are you?"
90002210-0063 = "Why do you test your own limits?"
90002210-0064 = "Sensei...!"
90002210-0065 = "Struggle is pain. It eventually leads to sin."
90002210-0066 = "[s3] \"I know. But I don't want you to take that away.\"\n[s4] \"Don't try to erase the possibilities from us.\""
90002210-0069 = "...!"
90002210-0070 = "[s5] \"As long as we live, there may be no way to escape pain.\"\n[s6] \"But I don't want anyone to bear it for me.\""
90002210-0073 = "Even if you must struggle like an insect and crawl upon the ground?"
90002210-0077 = "[log]That's right.[/log]"
90002210-0080 = "[log]Even so, I choose this path.[/log]"
90002210-0083 = "[log]Even if all I can do is fall, struggle, and crawl upon the ground.[/log]"
90002210-0086 = "[log]Because in the end, we will always stand back up.[/log]"
90002210-0089 = "[ns] \"Right, Aris?\""
90002210-0090 = "..."
90002210-0091 = "Yes. That's right, Sensei."
90002210-0092 = "Kei, do you remember?#nThat Aris said a Hero is a \"job where you move forward with everyone.\""
90002210-0093 = "Of course I remember."
90002210-0095 = "By doing so, a Hero—"
90002210-0096 = "Can reach places unattainable alone, as long as they are with everyone."
90002210-0102 = "...Insolent."