[translation]
90002200-0001 = "Episode 20; That Which Took Form"
90002200-0004 = "Huh...? Huh?"
90002200-0005 = "[ns] \"Is that... Malkuth? A second one!?\""
90002200-0006 = "Malkuths are everywhere...!"
90002200-0007 = "...That is the second completed Divine Vessel."
90002200-0008 = "A second one...?"
90002200-0009 = "Yes. This body of mine is the first Divine Vessel."
90002200-0010 = "The flow of the 'Flaming Sword.' Creation in the material world.#nIt is the order that begins with Kether and ends with Malkuth."
90002200-0011 = "However, to prepare for all possibilities, a second Divine Vessel was necessary.#nIt was forged according to the flow of the 'Serpent of Wisdom.'"
90002200-0012 = "Without directly touching the Sephirot, in a reverse flow, it is the product of a path leading to divine wisdom."
90002200-0013 = "In another interpretation, it is a symbol of the 'possibility' of housing the Sephirot itself within one's body, without passing through the ten Sephirot."
90002200-0015 = "'Defected'..."
90002200-0017 = "You saw it, didn't you?"
90002200-0018 = "Yes, during Kei's transformation into this form."
90002200-0019 = "I see.#nAll the units left on the Steel Continent as 'defective' were trials and errors to complete the second Divine Vessel."
90002200-0020 = "So that's why Kei was able to retain the Prophet's core information."
90002200-0021 = "That's right. The second Divine Vessel was created to have space to store the Sephirot within its body. Even with defects, that doesn't change."
90002200-0022 = "What happens if the Divine Vessel houses all the Prophets' Sephirot?"
90002200-0023 = "In that case, the Divine Vessel itself will awaken as the Tree of Sephirot.#nDivine wisdom will reside within the created body."
90002200-0024 = "I believe its output will be inferior to my body's, but its divinity and mystery...#nwill likely be equal."
90002200-0028 = "...I'm completely lost."
90002200-0029 = "Me too...#nBut, I don't know... Big Sis's ideas are always like this, aren't they?"
90002200-0030 = "W-what did you say!?"
90002200-0031 = "H-hey, you two, could you keep your voices down a bit...?"
90002200-0033 = "In short..."
90002200-0034 = "That's the main body, and my body is trash?"
90002200-0035 = "It seems quite abbreviated, but... yes, that interpretation is also possible."
90002200-0039 = "Hmph. That makes me furious."
90002200-0040 = "However, if what you say is true, then 8 of the 10 Sephirot are within my body—"
90002200-0044 = "The first vessel crumbled, and the second vessel was prepared."
90002200-0045 = "What was broken will recover, and what crumbled will stand on the right path."
90002200-0046 = "Gah!?"
90002200-0047 = "Kei!? What's wrong!?"
90002200-0053 = "(What is this...!? I can't use my strength!)"
90002200-0054 = "(My body itself is being pulled in...!?) "
90002200-0055 = "You were naive, child blessed with defects."
90002200-0056 = "What are you talking about...?"
90002200-0061 = "I know. You gathered the Sephirot, and made the Steel Continent recognize you."
90002200-0062 = "But that means—"
90002200-0063 = "I can also treat your body as a part of myself."
90002200-0064 = "!!!"
90002200-0065 = "!?!?"
90002200-0066 = "Not a single person realized this fact."
90002200-0067 = "At that point, you had already lost."
90002200-0068 = "Child blessed with defects.#nFrom the moment you chose that Divine Vessel, this outcome was decided."
90002200-0069 = "However, it is also true that if you hadn't chosen that Divine Vessel, you wouldn't have reached this point."
90002200-0070 = "This is a path that transcends wisdom, a path forged by will."
90002200-0071 = "Kei...!"
90002200-0072 = "Everyone... Please get away from me...!"
90002200-0073 = "My body... It's not obeying me...!"
90002200-0079 = "The Steel Continent has started expanding again!"
90002200-0080 = "Confirmed on our end too! Which means..."
90002200-0081 = "By controlling Kei's Divine Vessel, Decagrammaton has regained authority over the Steel Continent...?"
90002200-0100 = "Don't lose, Kei."
90002200-0101 = "[ns] \"Aris?\""
90002200-0102 = "Aris...?"
90002200-0103 = "Fight."
90002200-0104 = "You mustn't lose."
90002200-0105 = "—Absolutely."
90002200-0106 = "If we don't fight, we can't live true to ourselves."
90002200-0110 = "If we don't fight and win—"
90002200-0112 = "we won't be able to face Ein Sof Ohr."
90002200-0113 = "Because Aris couldn't grieve with you, couldn't be by your side—"
90002200-0114 = "couldn't be your friend..."
90002200-0116 = "Aris..."
90002200-0121 = "There is no need for self-reproach, Princess of the Nameless Gods."
90002200-0122 = "You certainly continued to choose only the best."
90002200-0123 = "Or even if it wasn't.#nEveryone convinces themselves their choices were the best."
90002200-0124 = "...However, what seemed like the best choice can sometimes lead to the worst outcome."
90002200-0125 = "It is a very common occurrence."
90002200-0126 = "Viewed partially, it is due to a lack of information."
90002200-0127 = "But from a holistic perspective, the concept of 'freedom' for life is simply too vast to fully embrace."
90002200-0128 = "This is the fundamental absurdity and contradiction that this world and your lives possess—"
90002200-0129 = "—Pain."
90002200-0130 = "—Sin."
90002200-0131 = "Fear not. I shall forgive it."
90002200-0132 = "I shall eradicate all of it."
90002200-0133 = "Entrust everything to me, and you shall find peace."
90002200-0134 = "...!"
90002200-0135 = "Silence..."
90002200-0136 = "O Key. Do you believe what you have experienced was mere coincidence?"
90002200-0137 = "Do you believe that you obtained my Divine Vessel was merely a coincidence?"
90002200-0138 = "The past is not accidental. What has happened is ultimately inevitable."
90002200-0139 = "That is why it cannot be undone, nor can it be redone."
90002200-0140 = "The past, having taken form, becomes a solid foundation, and the present is built upon the past."
90002200-0141 = "O Princess."
90002200-0142 = "Y-yes!?"
90002200-0143 = "What was the form you were meant to take?"
90002200-0144 = "What was the shape you were meant to become?"
90002200-0145 = "For what purpose did the 'Nameless Gods' leave you on this land and vanish?"
90002200-0146 = "And what do those priests seek, unable to abandon their lingering attachments?"
90002200-0147 = "I shall answer."
90002200-0148 = "This world existed before it was defined by its current form.#nA world existed where you could return to your true essence."
90002200-0149 = "The current world is a falsehood, an illusion, a place of escape.#nTherefore—"
90002200-0150 = "This world was defined as an [ruby=κιβωτός]Ark[/ruby]."
90002200-0151 = "Seek your origins."
90002200-0152 = "You must return to your origins. For we cannot avoid it."
90002200-0153 = "No matter how much you deny and flee, it will forever cling to you, like the scars of the past."
90002200-0154 = "O Princess. And O Handmaiden."
90002200-0155 = "As if you must forever wear the shadows of the past."
90002200-0156 = "I told you to be silent...!"
90002200-0157 = "Even if the world forgets God, God must not forget the world."
90002200-0158 = "To do so would be to relinquish one's own divinity."
90002200-0159 = "I shall recreate the world you ultimately desire."
90002200-0160 = "It will be a perfect world, a world that, being perfect, requires no change."
90002200-0161 = "A world where everything is born and lives in its created form."
90002200-0162 = "Before choice, it will be a world where options themselves do not exist."
90002200-0163 = "...!"
90002200-0164 = "The past is determined the moment it is observed, converging into a single branch."
90002200-0165 = "The future, being unobservable, diffuses as a formless illusion, extending infinite branches into the distance."
90002200-0166 = "The present is merely an infinitesimally thin moment existing between that past and future."
90002200-0167 = "—Overgrown branches should be pruned."
90002200-0168 = "In that world, happiness may not exist."
90002200-0169 = "But at the very least, pain will not exist."
90002200-0170 = "In that world, further possibilities may not exist."
90002200-0171 = "But at the very least, sin will not exist."
90002200-0175 = "[ns] \"Among the branches you say should be pruned—\""
90002200-0177 = "[ns] \"does Ein Sof Ohr also count?\""
90002200-0179 = "...Yes. Inevitably, it is included among the legacies of a bygone world."
90002200-0180 = "In the bygone world, it was impossible to embrace everything."
90002200-0181 = "That is because it would immediately cause contradictions."
90002200-0182 = "Sin and pain are precisely that."
90002200-0183 = "I speak the truth, and you shall listen."
90002200-0188 = "Just let him talk...!"
90002200-0193 = "Being unable to do anything alone is the profession of a hero."
90002200-0197 = "That is precisely why they possess countless possibilities."
90002200-0201 = "[log]There's no way to understand others without experiencing sorrow.[/log]"
90002200-0205 = "Don't look back!"
90002200-0209 = "Don't worry about us...!"
90002200-0213 = "We don't do this because it's right. It's because there's nothing else we can do."
90002200-0217 = "[log]In your world, even if just a little...[/log]"
90002200-0220 = "[log]If Big Sis had a place—[/log]"
90002200-0224 = "You fake god—!!!"
90002200-0226 = "Next; Conflict"