[translation]
90002025-0002 = "We did it!"
90002025-0003 = "The enemy is retreating!"
90002025-0004 = "We managed somehow... Phew..."
90002025-0006 = "Thank you, Eimi!"
90002025-0007 = "I'm used to this."
90002025-0008 = "More importantly, Sensei's judgment in deploying me here was sound."
90002025-0012 = "Sensei, can you hear me? Emergency engine repairs are complete."
90002025-0013 = "I'm here too. Sensei, please commend me promptly."
90002025-0014 = "[s] \"Rio and Toki, excellent work! Well done!\""
90002025-0015 = "Thank you. We can continue fighting now."
90002025-0017 = "â€”Engine repairs have been confirmed.#nKei, what's your assessment of the transport ship's status?"
90002025-0018 = "I believe re-flight is possible. However, if it sustains any more damage..."
90002025-0025 = "This is Aris! We're finished here! Everyone is safe!"
90002025-0026 = "Excellent work, Game Development Department, and Eimi."
90002025-0027 = "I apologize for asking this while you're tired, but on your way back, could you please retrieve the enemy wreckage?"
90002025-0028 = "It looks like we can retrieve them this time. How many do you need? 20 units?"
90002025-0029 = "If there are too many, we won't be able to store them inside the ship..."
90002025-0031 = "External camera, restarting. Displaying on monitor."
90002025-0037 = "This is..."
90002025-0038 = "..."
90002025-0039 = "[s] \"...\""
90002025-0041 = "[ns] \"That is... the Steel Continent...\""
90002025-0044 = "Next; Sortie"