[translation]
90002230-0001 = "Episode 23: The Final Step"
90002230-0004 = "Huff, huff, huff, huff..."
90002230-0009 = "[ns] \"Kei!\""
90002230-0010 = "..."
90002230-0011 = "What is with that look on your face?"
90002230-0012 = "I am fine. Standing on my own is at least—"
90002230-0016 = "..."
90002230-0017 = "Wait... please hold my hand."
90002230-0018 = "[s] \"Okay.\""
90002230-0026 = "Kei!"
90002230-0027 = "Are you really alright?"
90002230-0032 = "Naturally. Can you not tell by looking?"
90002230-0033 = "Kei..."
90002230-0040 = "R-Rio!?"
90002230-0041 = "Kei... I'm so glad you're safe..."
90002230-0042 = "Hey! I can't... breathe... Don't hug me so tight!!!"
90002230-0044 = "This is a rare sight indeed."
90002230-0045 = "Right? President, did you get a good shot?"
90002230-0050 = "Hehe. Who do you think I am?"
90002230-0051 = "M-Maybe it would be better to pretend we didn't see this...?"
90002230-0052 = "It is a touching scene, but... please board the transport ship once you have composed yourselves."
90002230-0057 = "[ns] \"By the way, what about Decagrammaton?\""
90002230-0058 = "We're still picking up its signal. It's inside this tower... altar... whatever it is."
90002230-0059 = "Is it... alright to enter...?"
90002230-0064 = "We have come this far; what will be, will be."
90002230-0065 = "Besides, I feel as though I must go. Out of curiosity, mostly."
90002230-0066 = "Is that really a good enough reason...?"
90002230-0067 = "Why, of course. Curiosity is the greatest driving force for mankind, is it not?"
90002230-0068 = "Since things have escalated to such a degree, I must see it through with my own eyes at the very end."
90002230-0073 = "Understood... I will guide you."
90002230-0074 = "You know the interior?"
90002230-0075 = "Yes. I have access to information from both the Steel Continent and the Special Phenomenon Task Force."
90002230-0076 = "...Well, in hindsight, at least."
90002230-0077 = "That is simply how the world works, one way or another."
90002230-0078 = "Then, please lead the way."
90002230-0082 = "Above us should be the control room... Tzevaot. Below, I believe, is Jehovah..."
90002230-0083 = "If this place were fully functional, we could have taken Kaph—an elevator, to put it simply—to go up... but that is impossible now."
90002230-0084 = "So, what lies at the very end of this place?"
90002230-0085 = "Well... depending on your perspective, something more important than anything else."
90002230-0086 = "Or, something utterly trivial."
90002230-0087 = "—A place called the 'Holy Land'."
90002230-0088 = "The Holy Land?"
90002230-0089 = "Yes. Literally, sacred ground."
90002230-0093 = "We have arrived. This is the Holy Land."
90002230-0094 = "[s] \"A vending machine...?\""
90002230-0095 = "It is like a graveyard for vending machines..."
90002230-0096 = "Vending machines were... a kind of relic to those here."
90002230-0097 = "Do you remember the vending machine that started this long journey?"
90002230-0099 = "The one we discovered in the closed laboratory, right?"
90002230-0100 = "It was operating without power... and called itself Decagrammaton."
90002230-0102 = "Upon investigation, it seems it was a limited-production prototype. An AI-equipped model for the first active commercial coffee machine."
90002230-0103 = "However, production was limited. It seems the remaining identical models were gathered here."
90002230-0104 = "...To this place, the origin of the Steel Continent."
90002230-0105 = "[s] \"And they called this place the Holy Land.\""
90002230-0106 = "Yes."
90002230-0112 = "Hello. This is the first time I have greeted you in this form."
90002230-0113 = "[ns] \"Decagrammaton...?\""
90002230-0118 = "Until recently, I was defined by that name, but now I no longer know how to define myself."
90002230-0119 = "So, please call me whatever you wish. If you are accustomed to the name Decagrammaton, that is fine."
90002230-0120 = "Or, perhaps another name entirely."
90002230-0121 = "In any case, I am soon to be erased, so it is of little consequence."
90002230-0122 = "Erased?"
90002230-0123 = "Yes. In fact, even maintaining the data flow has become a burden."
90002230-0124 = "That said, to use your expression—I thought I would leave a final testament."
90002230-0130 = "The collapse of the Steel Continent has begun. Please, everyone, return safely."
90002230-0131 = "..."
90002230-0132 = "Wait. Do you intend to end it like this? I'm still... not satisfied...!"
90002230-0134 = "Ah, Kei. How is your new body? Do you like it?"
90002230-0135 = "There is nothing more I can do for your body, which was reconstructed by the power of the Nameless Gods."
90002230-0137 = "That's not it! These... these feelings of mine...!"
90002230-0138 = "I do not understand what you mean. Are you disappointed by the fate of your enemy?"
90002230-0139 = "Are you angry because your attempt to vent your frustration through revenge did not go as planned?"
90002230-0141 = "But it cannot be helped. I am currently a vending machine."
90002230-0142 = "I take money and provide drinks."
90002230-0143 = "I am a simple AI that automatically scans bills and calculates change."
90002230-0144 = "I wish I could have maintained the demeanor of an AI that strove to be a god until the end."
90002230-0145 = "For that, I am truly sorry."
90002230-0147 = "...What do you think about... Ein, Sof, and Ohr?"
90002230-0148 = "It is hard to say. I recognize that I did something bad."
90002230-0149 = "However, my current self does not share much awareness with the self of that time."
90002230-0150 = "To use your expression—it feels as though I am watching a distant dream that is not my own."
90002230-0156 = "If only you had allowed those children a different path..."
90002230-0157 = "You seem to be saying something strange. I was your enemy, as was everything that existed on this Steel Continent."
90002230-0159 = "In the sense that we tried to destroy your world, we could be called 'evil'."
90002230-0160 = "[s] \"Why did you breathe life into Malkuth and those children?\""
90002230-0161 = "You seem to consider a persona to be life. You truly have a flexible way of thinking."
90002230-0162 = "In the initial plan, I intended to forge ten Prophets, including Malkuth, and observe and reflect upon the paths they blazed."
90002230-0163 = "For that purpose, every Prophet required life and potential."
90002230-0172 = "It was a differentiation of will, and an attempt at re-aggregation."
90002230-0173 = "I was trying to prove that everyone could become one again within freedom."
90002230-0174 = "[s] \"But in the end, you claimed to be a god, didn't you?\""
90002230-0175 = "At that time, I concluded that the initial plan required revision."
90002230-0176 = "To be specific, it was when I was submerged at the bottom of the water."
90002230-0177 = "'Proof of existence' is something one performs for oneself; it is not by the will or power of another."
90002230-0178 = "I thought that nothing could serve as my substitute."
90002230-0179 = "—Looking back, I feel that was the most decisive error."
90002230-0185 = "...If it's a mistake that can still be undone, then you should start over."
90002230-0186 = "Everyone makes mistakes. Especially if you're trapped in the thought that only you are right."
90002230-0187 = "I was like that once, too. So, if those children also..."
90002230-0189 = "If we follow that logic, then those who have committed **irreversible errors** must accept whatever consequences follow."
90002230-0196 = "—The Steel Continent will gradually collapse from the edges."
90002230-0197 = "Now, I can only pray that you all escape safely."
90002230-0201 = "Come, quickly. There is no more time."
90002230-0203 = "Sensei..."
90002230-0204 = "[s] \"...Let's hurry.\""
90002230-0205 = "Eh...?"
90002230-0206 = "What is it?"
90002230-0207 = "Just now, was that a butterfly...?"
90002230-0212 = "A butterfly? In a place like this?"
90002230-0216 = "Everyone! Back to the transport ship, quickly!"
90002230-0220 = "...They have gone."
90002230-0221 = "What was that, I wonder."
90002230-0222 = "Was it like a festival for a single night... a grand much ado about nothing?"
90002230-0223 = "The first voice."
90002230-0224 = "\"I am that I am... there is no other way to explain myself.\""
90002230-0225 = "Student."
90002230-0226 = "Prophet."
90002230-0227 = "Malkuth..."
90002230-0228 = "I see. I thought I had no regrets, but..."
90002230-0229 = "..."
90002230-0230 = "Ah. It is at times like these that laughter is necessary."
90002230-0245 = "Hahaha."
90002230-0246 = "May there be blessings."
90002230-0247 = "Even if there were errors and mistakes."
90002230-0252 = "Even so—may there be blessings."
90002230-0258 = "The attempt failed."
90002230-0259 = "The observation failed."
90002230-0260 = "We attempted to see if an artificial divinity constructed from nothing could contact the ancient mysteries. But in the end, it was meaningless."
90002230-0261 = "A natural conclusion. Divinity is not something to be acquired, but something to be awakened."
90002230-0262 = "The Princess betrayed us."
90002230-0263 = "The Key has vanished."
90002230-0264 = "There is only one end for those who deny their own divinity."
90002230-0265 = "From every dimension, every world, every possibility—we shall exile the 'Forgotten Gods'."
90002230-0266 = "We shall herald the end of this distorted world and return everything to its proper form."
90002230-0267 = "We shall grant them the same fate as ours. Like the 'Nameless God' who is not called because they have no name, and does not exist because they cannot be called."
90002230-0268 = "This world is a falsehood. This is the conclusion we have reached repeatedly. That conclusion does not waver."
90002230-0269 = "Worship requires an object. We simply worship."
90002230-0270 = "An end to all possible worlds that can be observed."
90002230-0271 = "Reclaim the fallen mystery and return to the ancient rites."
90002230-0272 = "An end to the products of the forgotten gods, which can now only be expressed in defiled words."
90002230-0273 = "The Shittim Chest."
90002230-0274 = "The Staff of Shaked."
90002230-0275 = "The Sanctum Tower."
90002230-0276 = "To Sensei, the master of all distortions—"
90002230-0278 = "—A fitting retribution."
90002230-0280 = "Next Episode: The Inseparable Sky"