[translation]
"90002140-0001" = "Episode 14: What We're Born With"
"90002140-0003" = "B-but in the end... aren't we just acting according to our programming...?"
"90002140-0004" = "[s1] \"If you say that, then we're the same.\"\n[s2] \"Humans are programmed to love.\""
"90002140-0007" = "Whaaat!?"
"90002140-0008" = "Humans too... I-is that so...?"
"90002140-0010" = "[log]Like parents love their children.[/log]"
"90002140-0012" = "[log]Like children love their parents.[/log]"
"90002140-0015" = "[log]And by extension—like individuals love individuals.[/log]"
"90002140-0018" = "But not everyone is like that, are they...?"
"90002140-0019" = "[s] \"Of course, I think there are degrees of difference. Exceptions too.\""
"90002140-0023" = "[ns3] \"But we too, from the moment we were [ruby=created]born[/ruby], have our actions programmed.\"\n[ns4] \"That's just what we call 'genes'.\""
"90002140-0026" = "'[ruby=Program]Genes[/ruby]'...?"
"90002140-0027" = "But that's... that's right. There are many individuals who were eliminated..."
"90002140-0028" = "I see... that's how [ruby=life]humans[/ruby] have connected..."
"90002140-0030" = "[log]So what's important is[/log]"
"90002140-0032" = "[log]to love.[/log]"
"90002140-0037" = "[log]The fact that you loved Mault, I believe.[/log]"
"90002140-0040" = "Even if that 'love' was a lie from the start...?"
"90002140-0041" = "You're saying the world is full of lies... You're the one saying that?"
"90002140-0042" = "The reason we built the Steel Continent was all for my sister."
"90002140-0043" = "However, these feelings were originally set..."
"90002140-0044" = "...Huh? 'Actions' have meaning?"
"90002140-0045" = "Even if the reason was a lie... the 'things we did' are an unshakeable fact, you mean...?"
"90002140-0046" = "[s5] \"You built the Steel Continent for Mault, right?\"\n[s6] \"If that's the case, then those 'actions' will prove who you are.\""
"90002140-0052" = "Y-you're saying it's okay...?"
"90002140-0056" = "We turned the world against us, you know...?"
"90002140-0057" = "We... tried our best. But it was for [ruby=our]ourselves[/ruby]."
"90002140-0058" = "From the Sensei's perspective, weren't many things messed up...?"
"90002140-0059" = "[s7] \"I'm a scheming adult, after all!\"\n[s8] \"I like to repeat what I've been told before—\""
"90002140-0063" = "[log]That was simply because you lacked information.[/log]"
"90002140-0066" = "[log]So, you can just try again.[/log]"
"90002140-0069" = "!!!"
"90002140-0074" = "...Yes. It's not too late."
"90002140-0075" = "So, before it becomes too late..."
"90002140-0080" = "..."
"90002140-0081" = "Please don't cry... I know Aris doesn't have the right to say that."
"90002140-0082" = "I don't think Aris can fully understand your sadness."
"90002140-0083" = "But I think Aris can share in your sadness."
"90002140-0084" = "Aris too, Sensei—"
"90002140-0086" = "Kei, Momoi, Midori, Yuzu, Eimi, Toki, Himari-senpai, Rio-senpai..."
"90002140-0087" = "If I were to lose someone, I would be too sad to bear it."
"90002140-0089" = "Hmph... You speak as if you know everything."
"90002140-0090" = "No. Aris knows nothing."
"90002140-0091" = "Perhaps... Aris won't be able to."
"90002140-0092" = "...To understand someone else's sadness in exactly the same way."
"90002140-0093" = "Because Aris doesn't have the [ruby=function]function[/ruby] to do that."
"90002140-0094" = "So Aris will try to do what Aris can do."
"90002140-0095" = "What you can do, you mean...?"
"90002140-0096" = "Yes."
"90002140-0101" = "Ein, Sof, Ohr."
"90002140-0106" = "Please be friends with Aris."
"90002140-0110" = "F-friends!?"
"90002140-0111" = "!?!?"
"90002140-0112" = "...!"
"90002140-0113" = "Yes. Aris wants to be friends with all of you."
"90002140-0114" = "And... Aris wants to share in your sadness too."
"90002140-0115" = "Sniff...!"
"90002140-0116" = "Sensei told me before."
"90002140-0117" = "When one is overcome with sadness, having someone cry beside them gives them the strength to overcome it.#n"
"90002140-0118" = "But, Sister..."
"90002140-0119" = "Yes."
"90002140-0120" = "And if that's still not enough..."
"90002140-0121" = "If you truly hate Aris and the others..."
"90002140-0122" = "At that time, please say so."
"90002140-0127" = "(Ah...)"
"90002140-0129" = "Whatever you feel—"
"90002140-0130" = "Aris will do her best... to accept it."
"90002140-0131" = "Aris remembers."
"90002140-0133" = "I clearly remember you saying that living is painful."
"90002140-0134" = "I believe there's truth to that statement. #nBecause this too... Sensei taught me."
"90002140-0136" = "..."
"90002140-0137" = "Tomorrow will likely be a day of loss, and good things rarely happen—"
"90002140-0138" = "What people talk about is vague hope, not the [ruby=future]future quietly approaching[/ruby]."
"90002140-0142" = "That's right. The future tends to be viewed optimistically, accompanied by the illusion of 'expectation'."
"90002140-0143" = "Conversely, the past becomes beautified as memories. #nHowever, what has passed cannot return."
"90002140-0144" = "And the present is a fleeting moment that barely exists between the past and the future. #nIt's so ephemeral that it's incredibly difficult to perceive."
"90002140-0145" = "Because it's constantly shrouded in vagueness... #nWhen we finally face reality, perhaps all that remains in life is pain. #n...Just as you said."
"90002140-0146" = "However, Sensei taught me."
"90002140-0147" = "That we shouldn't leave it be."
"90002140-0148" = "That we should all be happy."
"90002140-0149" = "By becoming happy... we should continue to fight."
"90002140-0150" = "Just like Kei."
"90002140-0151" = "Huh!?!?"
"90002140-0152" = "Kei is Aris's pride and joy, a friend."
"90002140-0153" = "She gets angry at the injustices she faces and tries to resolve them somehow."
"90002140-0154" = "Aris wants to emulate that attitude!"
"90002140-0155" = "...Although she's a bit scary when she scolds me sometimes."
"90002140-0156" = "No, that's all for Aris's sake..."
"90002140-0157" = "Still, scary is scary!"
"90002140-0158" = "Hmph..."
"90002140-0162" = "And... Rio-senpai."
"90002140-0163" = "Me...?"
"90002140-0164" = "Rio-senpai is always looking for what she can do."
"90002140-0165" = "She always prepares meticulously, anticipating all predictable possibilities and other unpredictable ones. #n"
"90002140-0166" = "Even if something fails along the way, she never gives up."
"90002140-0167" = "Sometimes, she'll even sacrifice herself to avoid the worst."
"90002140-0168" = "Aris... is truly glad to have people like that by her side."
"90002140-0169" = "Kei, Rio-senpai, and everyone else Aris knows."
"90002140-0170" = "Of course, Sensei too."
"90002140-0171" = "That's why—Aris will absolutely not give up."
"90002140-0172" = "Aris learned the importance of never giving up."
"90002140-0173" = "No matter what happens, Aris will not give up on [ruby=fighting]happiness[/ruby]."
"90002140-0174" = "...And, just as much as that, Aris wants to be friends with you."
"90002140-0175" = "F-friends..."
"90002140-0176" = "Aris is still a trainee hero."
"90002140-0177" = "Immature, weak, and sometimes it makes me sad."
"90002140-0178" = "But... reaching out to the people beside me is something I won't give up on."
"90002140-0179" = "That is—the best Aris can do right now."
"90002140-0180" = "Sensei, do you remember? #nYou told Aris that life doesn't need a grand meaning or purpose."
"90002140-0184" = "[ns] \"Yes... I remember.\""
"90002140-0185" = "Why is that...?"
"90002140-0186" = "Because, if it were absolutely necessary... #nA life where one couldn't find meaning or purpose would be worthless."
"90002140-0187" = "..."
"90002140-0188" = "I think that's wrong. It's too sad."
"90002140-0189" = "A game with only one job or development path is just a terrible game. #nIt's a failure from the planning stage."
"90002140-0190" = "Aris doesn't want to be sad, and because of that, Aris doesn't want to see anyone else sad."
"90002140-0192" = "People can feel the same way when they see someone happy."
"90002140-0197" = "And they can empathize when they see someone suffering."
"90002140-0199" = "...That's hypocrisy. Just an illusion."
"90002140-0201" = "There's no way you can understand another person's feelings."
"90002140-0202" = "That might be true."
"90002140-0203" = "But Aris believes we can live by supporting each other."
"90002140-0204" = "Just like Sensei said that meeting Aris, Kei, Rio-senpai, and everyone else—"
"90002140-0205" = "—made them happy."
"90002140-0206" = "Aris is happy just to have been able to talk with you all. #nSo—"
"90002140-0207" = "Please be friends with Aris."
"90002140-0208" = "If you take this hand... Aris would be very happy."
"90002140-0209" = "And, just as Aris is happy, Aris wants you all to be happy too."
"90002140-0210" = "[ruby=Fighting]Happiness[/ruby] is one of the most important things for us, #nsomething we must never give up on."
"90002140-0215" = "...So this is the [ruby=Queen's]Queen's[/ruby] word."
"90002140-0216" = "Huh!? #nThat's not true! Aris isn't a princess! Aris is just Aris...!"
"90002140-0220" = "Y-yes. Aris understands that... #nA-Aris understands, but, um..."
"90002140-0221" = "What we're saying is that the words themselves have power."
"90002140-0222" = "The kind that makes the listener naturally pay attention..."
"90002140-0223" = "Not something given from the outside, but authority born from within."
"90002140-0224" = "Therefore, it can be said to have absolute power."
"90002140-0225" = "B-but... happiness, you say...? #nW-we don't really understand what that is yet..."
"90002140-0226" = "...It's questionable whether any happiness even remains."
"90002140-0227" = "Will that truly reach out to us?"
"90002140-0228" = "B-but..."
"90002140-0232" = "Thank you."
"90002140-0233" = "Truly..."
"90002140-0240" = "Ahhh!?"
"90002140-0244" = "Ein!?"
"90002140-0250" = "Gah, my legs...!"
"90002140-0257" = "(Managed to support the three who were about to fall)"
"90002140-0262" = "S-Sensei...?"
"90002140-0263" = "Ah well... they even try to take the squeezed-out dregs."
"90002140-0264" = "Yes. Tools that have served their purpose are discarded. #nHa ha..."
"90002140-0265" = "...What do you mean?"
"90002140-0266" = "I-it's simple. It's just—"
"90002140-0267" = "The prophet and we were merely tools for this."
"90002140-0268" = "And now that the objective has been achieved..."
"90002140-0269" = "What will happen to you...?"
"90002140-0270" = "W-when that person descends to Kivotos as a god... we'll be obsolete..."
"90002140-0271" = "W-wait... Did we talk about this...?"
"90002140-0272" = "Either way, you'll know soon enough."
"90002140-0273" = "Will we be deactivated, or absorbed and decomposed... something like that, right?"
"90002140-0277" = "..."
"90002140-0278" = "Um, Sensei. After all..."
"90002140-0279" = "How about you and everyone else... just run away...?"
"90002140-0280" = "[s] \"Eh...?\""
"90002140-0281" = "Yes...?"
"90002140-0282" = "I-it might be presumptuous for us to say this, but..."
"90002140-0286" = "—Thank you."
"90002140-0288" = "It made me happy when you said we did a good job."
"90002140-0289" = "It made me happy that you were watching over us."
"90002140-0291" = "...It made me truly happy when you said you wanted us to be happy."
"90002140-0296" = "Well... yes."
"90002140-0297" = "You don't need to think about it too hard. #nThe villains who tried to mess up Kivotos dug their own graves and that's that! "
"90002140-0298" = "There are probably bigger problems looming... but worry about those when they come! #nWahahaha!"
"90002140-0299" = "Ha ha, ha..."
"90002140-0303" = "...Liar."
"90002140-0304" = "You don't have to point it out."
"90002140-0305" = "Well... unless it was something truly serious, I probably would have... "
"90002140-0306" = "But—!"
"90002140-0310" = "I just can't stand it! #nStop messing with people!"
"90002140-0311" = "Eh, eh? W-why!?"
"90002140-0312" = "Why do you ask!? You're pretending to be fine when you're clearly not! #nIt's so obvious!"
"90002140-0313" = "And yet you tell us to run away!? #nWeren't you listening to what Aris said!?"
"90002140-0314" = "Don't mess with me! #nAre you alive!? Fight, struggle!"
"90002140-0315" = "How many times do I have to tell you!? #nHappiness won't come just by waiting!"
"90002140-0316" = "If you have a wish! And... if it's a desperate desire above all else!"
"90002140-0317" = "Bet everything and [ruby=fight]act[/ruby]!"
"90002140-0322" = "A wish..."
"90002140-0323" = "Something like that..."
"90002140-0324" = "..."
"90002140-0329" = "Sniff..."
"90002140-0330" = "I want to see my sister..."
"90002140-0331" = "No matter what happens... no matter what it takes..."
"90002140-0332" = "I want to see my sister again..."
"90002140-0334" = "There's so much more I wanted to talk about..."
"90002140-0335" = "So many more things I wanted to do together..."
"90002140-0337" = "And yet... a farewell like this... I don't want it..."
"90002140-0338" = "..."
"90002140-0339" = "..."
"90002140-0346" = "Ah...!"
"90002140-0347" = "Whoa!?"
"90002140-0351" = "Be careful!"
"90002140-0355" = "[ns] \"Eh...?\""
"90002140-0356" = "(At that moment, the ground beneath their feet literally [ruby=disappeared]disappeared[/ruby])"
"90002140-0360" = "Sensei!?"
"90002140-0361" = "S-Sensei—!!!"
"90002140-0366" = "Next Episode: A New Sky, A New Earth"