[translation]
90002090-0001 = "Episode 9: Dress Up"
90002090-0006 = "Sorry to keep you waiting, Sensei!"
90002090-0007 = "[s] \"Midori...?\""
90002090-0008 = "D-Does it look strange...?"
90002090-0009 = "[s] \"It's really cute...!\""
90002090-0010 = "Ehehe. Thank you. I'm glad..."
90002090-0015 = "To use Aris's words, we've crafted new armor and armaments for everyone."
90002090-0016 = "The protective suit Midori is wearing is one of them."
90002090-0017 = "[s1] \"For everyone?\"\n[s2] \"For all eight of us?\""
90002090-0020 = "Yes."
90002090-0021 = "It was simple enough."
90002090-0022 = "Midori prepared the designs."
90002090-0023 = "Toki and I checked the functional aspects."
90002090-0024 = "Kei-chan even built the equipment for generating the designs for this occasion. #nIt made the work much easier."
90002090-0025 = "Wait a second, little sister. Your big sister has something to say."
90002090-0026 = "Aren't the designs for just the two of us a bit different!?"
90002090-0028 = "There are no issues with actual movement. Though they do look a bit... bulky."
90002090-0030 = "Looks are important too!"
90002090-0031 = "You said you didn't want to get hurt, so I prioritized safety in the design, okay?"
90002090-0032 = "W-Well, I did say that, but..."
90002090-0033 = "But look, I wanted something more... protagonist-like! A cool design!"
90002090-0034 = "[s] \"I think it looks plenty cool.\""
90002090-0035 = "R-Really? Well, if you say so, Sensei..."
90002090-0037 = "Momoi and Midori's suits have the highest defense among these."
90002090-0038 = "Even if something happens... #nthey should survive until the end to at least clean up after everyone."
90002090-0039 = "K-Kei-chan!? #nYou didn't say anything like that while we were making them...!"
90002090-0040 = "I was just saying."
90002090-0041 = "Now, next is—"
90002090-0045 = "Moving away from heavy armament, this is the lightweight and optimized mobile-type Toki Asuma. #nHop, hop."
90002090-0046 = "You really can't stay still for a second, can you...?"
90002090-0047 = "You want Sensei to be the very first to see your new outfit, right?"
90002090-0048 = "Not everyone thinks that way..."
90002090-0049 = "But I do."
90002090-0050 = "I see..."
90002090-0051 = "[s] \"Ah, right. Since you handed over the Abi-Eshuh to Aris...\""
90002090-0052 = "Yes. I took this opportunity to completely refresh the concept and atmosphere. #nFrom now on, I plan to excel as a mobile investigator using speed as my weapon."
90002090-0053 = "Above all, I am very satisfied with its excellent heat retention. #nThe existing maid uniform had issues with dropping body temperature."
90002090-0057 = "[ns] \"...Wait, were you cold this whole time?\""
90002090-0058 = "Yes."
90002090-0059 = "[s] \"And yet, you still wore the maid uniform?\""
90002090-0060 = "Yes."
90002090-0061 = "You ask why?"
90002090-0062 = "..."
90002090-0063 = "Sensei. There are times when a person must show their grit."
90002090-0064 = "And why is that?"
90002090-0066 = "...Because I cannot lose to Eimi."
90002090-0067 = "[s] \"I really don't understand you sometimes, Toki...\""
90002090-0068 = "It is fine. I understand myself perfectly."
90002090-0073 = "T-Toki-san..."
90002090-0074 = "*Sigh*..."
90002090-0075 = "Cold protection aside... her main armament consists of dual energy pistols. #nDepleted batteries are ejected to the rear via an ejector."
90002090-0076 = "I did the coloring! #nI felt Toki-san's personal colors should definitely be white and blue!"
90002090-0077 = "And if I take off this jacket, my nice and perfect body will be revealed. Would you like to see?"
90002090-0078 = "Wh-What!?"
90002090-0079 = "[s] \"Not now! That would cause a huge scene!\""
90002090-0080 = "[ruby=・   ・]Now[/ruby] is not the time. I see. Then I shall show you someday, during a special time for just the two of us."
90002090-0081 = "Toki-san!?"
90002090-0082 = "...If you react to every little thing, the sun will go down."
90002090-0083 = "Now, next is Eimi... Eimi? Yes? You're hot already?"
90002090-0084 = "Please endure it a little... What is wrong with your constitution...?"
90002090-0090 = "Phew..."
90002090-0091 = "Where's your jacket!?"
90002090-0092 = "It was hot, so I took it off."
90002090-0093 = "I can see that, but..."
90002090-0094 = "Eimi is mainly in charge of rear support this time, right? #nIn that case, wouldn't it be 'efficient' to wear the jacket for camouflage?"
90002090-0095 = "But if I wore that the whole time, I'd collapse from heatstroke first."
90002090-0096 = "If I can't provide support because of the heat, wouldn't that be truly inefficient?"
90002090-0098 = "Yes... anticipating that, I designed Eimi-san's jacket so it's easy to tie around her waist."
90002090-0100 = "Thanks. That really helps."
90002090-0101 = "..."
90002090-0102 = "Come to think of it, she was always like this... It was my mistake to forget..."
90002090-0103 = "That aside, Eimi has also changed her main armament. #nIt shares the same concept as Toki's, being an energy weapon that uses batteries."
90002090-0104 = "Of course, the output and battery capacity are completely different."
90002090-0105 = "The visor for Eimi is a [ruby=HUD]Head-Up Display[/ruby] added to quickly identify support points."
90002090-0106 = "Since the visor is powered by the same battery as the weapon, the backpack is larger than Toki's."
90002090-0108 = "What do you think, Sensei?"
90002090-0109 = "Eh? It looks efficient? #nI see, hmm..."
90002090-0110 = "..."
90002090-0111 = "[s] \"Oh, what's wrong?\""
90002090-0112 = "Hmm, that would have been the best compliment until now, but..."
90002090-0113 = "It's strange even to me... but I want to hear something else."
90002090-0114 = "For example..."
90002090-0118 = "..."
90002090-0119 = "Like... it's cute?"
90002090-0121 = "!?"
90002090-0122 = "!?"
90002090-0127 = "[ns] \"It suits you well, and it's very cute.\""
90002090-0128 = "Yeah."
90002090-0129 = "Thank you, Sensei."
90002090-0131 = "Midori. I feel like I just witnessed a truly terrifying sight..."
90002090-0132 = "D-Don't say it like that!"
90002090-0133 = "I know, but..."
90002090-0137 = "..."
90002090-0138 = "Guaaah! Next! Next! #nThe person who's humming with excitement. It's your turn."
90002090-0141 = "Hehehe. How do I look?"
90002090-0142 = "[s] \"Um... this might be rude, but...\""
90002090-0143 = "Yes?"
90002090-0144 = "[s] \"Aren't you cold...?\""
90002090-0145 = "Oh, I wondered what you were going to say."
90002090-0146 = "There's no way this super-genius combat-type all-purpose sickly beautiful girl hacker wouldn't have a plan."
90002090-0147 = "Not only does it have environmental adaptability like cold and water resistance... #nit's an all-purpose field support suit that combines fragility and purity."
90002090-0151 = "[ns3] \"Fragility...\"\n[ns4] \"Purity...\""
90002090-0157 = "Um, I've been wondering for a while... #naren't you embarrassed to say things like that about yourself...?"
90002090-0158 = "Clearly stating the facts is the foundation of the scientific method."
90002090-0159 = "Clearly... stating... the facts... I see..."
90002090-0160 = "That said... wearing a pure white suit like this..."
90002090-0161 = "*Sniff*..."
90002090-0162 = "[s] \"What's wrong? Why are you crying all of a sudden...?\""
90002090-0163 = "What should I do... I'm so moved by my own beauty and cuteness that tears are—"
90002090-0164 = "Sorry, I'll take responsibility and handle the President."
90002090-0169 = "Wait, Eimi!? #nI'm not finished talk—!?"
90002090-0172 = "[ns] \"It feels like a storm just passed through...\""
90002090-0173 = "Exactly..."
90002090-0174 = "(I need to clear the air quickly...!)"
90002090-0178 = "N-Now then! Next is President Rio's turn!"
90002090-0185 = "[ns] \"Rio...?\""
90002090-0186 = "What is it?"
90002090-0187 = "[s] \"No, well...\""
90002090-0188 = "I don't know the reason for that reaction, but this is how it turned out."
90002090-0189 = "Field response, facility utilization, situational analysis... it's a combat suit focused on versatility for any scenario."
90002090-0190 = "Literally rational."
90002090-0191 = "I aimed for a contrast with Himari-senpai's suit color. #nI just felt like that's what I should do..."
90002090-0192 = "I still think there's a problem with that design!"
90002090-0193 = "President, calm down. Do you want to be forcibly locked in a room again?"
90002090-0194 = "Ugh..."
90002090-0195 = "This is a matter of designer's pride...! I couldn't compromise on this!"
90002090-0197 = "I have... no regrets about this choice!"
90002090-0202 = "I'll refrain from commenting..."
90002090-0203 = "So, I'll just explain plainly. #nRio's suit is designed for increased defense and electronic warfare capabilities."
90002090-0204 = "It reflects Rio's request to be able to provide technical support in the field."
90002090-0205 = "[s] \"Rio? Isn't that dangerous...?\""
90002090-0206 = "It's more rational than Himari going out."
90002090-0207 = "Above all, this is the Steel Continent. We should anticipate electronic warfare."
90002090-0208 = "[s5] \"I see.\"\n[s6] \"I'm counting on you.\""
90002090-0211 = "Yes."
90002090-0212 = "Leave it to me."
90002090-0213 = "And finally..."
90002090-0219 = "Yuzu?"
90002090-0220 = "Don't hide... please come out."
90002090-0221 = "Yuzu-chan, it's okay."
90002090-0229 = "Ugh..."
90002090-0230 = "[s] \"Oh? It's quite different from Momoi and Midori's.\""
90002090-0231 = "W-Well..."
90002090-0232 = "I requested it."
90002090-0233 = "They were originally going to use the same design as ours, but..."
90002090-0234 = "[s] \"Why is that?\""
90002090-0235 = "..."
90002090-0236 = "I'd like to keep it a secret for now, if that's okay."
90002090-0237 = "We've taken every precaution, but I can't completely rule out the possibility that this conversation is being intercepted."
90002090-0238 = "...This suit is, in a sense, a secret weapon."
90002090-0239 = "[s] \"So the trump card is a secret even from allies?\""
90002090-0240 = "...I'm sorry. I do feel bad about it."
90002090-0241 = "I know that we can only overcome this by trusting everyone. #nBut..."
90002090-0242 = "[s] \"It's okay. I trust you, Rio.\""
90002090-0243 = "Sensei..."
90002090-0245 = "Are you sure about that?"
90002090-0246 = "What? You're fine with it because Rio has never truly plotted anything evil before?"
90002090-0247 = "Well, that's true, but..."
90002090-0248 = "Yes! Aris thinks so too!"
90002090-0249 = "Aris!?"
90002090-0250 = "Aris-chan!?"
90002090-0251 = "A-Aris-chan...?"
90002090-0256 = "..."
90002090-0257 = "You... trust me...?"
90002090-0258 = "Yes. Because Rio-senpai worked hard to adjust Aris's Abi-Eshuh and Kei's gun until the very end!"
90002090-0259 = "If Rio-senpai were planning something bad, I'm sure she wouldn't have gone this far!"
90002090-0260 = "I helped too, you know!?"
90002090-0261 = "That's right! Himari-senpai was there too!"
90002090-0262 = "Hehe... for Aris's sake, I'll let it slide this time."
90002090-0263 = "Oh, right. There are hidden features too, so look forward to them."
90002090-0268 = "[ns] \"Wait, did you just say Kei's gun?\""
90002090-0269 = "Yes?"
90002090-0270 = "Ah, yes, well, technically..."
90002090-0271 = "Apparently, walking around Kivotos without a gun is said to be stranger than walking around naked..."
90002090-0272 = "Its name is 'Earendel: Luminous Nova.' It's an energy weapon."
90002090-0273 = "Ugh... I still don't know. #nDoes this outfit... suit me...?"
90002090-0274 = "A-And besides, are you sure I'm the right person for this...?"
90002090-0275 = "[s7] \"It's okay, it suits you well.\"\n[s8] \"We... need Yuzu's power!\""
90002090-0278 = "Y-Yes!?"
90002090-0279 = "That's, um..."
90002090-0280 = "I-If you say so, Sensei..."
90002090-0281 = "I'll... do my best..."
90002090-0282 = "[s] \"Alright, let's start the final inspection!\""
90002090-0294 = "Kei, do you have a moment?"
90002090-0295 = "What is it?"
90002090-0296 = "There's something I want to tell only you."
90002090-0297 = "Only me? Without even including Sensei?"
90002090-0298 = "Well..."
90002090-0299 = "I've been speculating for a while now..."
90002090-0300 = "I wonder... what kind of information can you hide from the Steel Continent and those three?"
90002090-0301 = "..."
90002090-0302 = "You're quite perceptive. How did you know?"
90002090-0303 = "Because those three didn't notice you or Aris until we reached Tiphareth."
90002090-0304 = "So you've decided that you can share that secret—the trump card—with me?"
90002090-0305 = "...Very well. #nHowever, the firewall will only last 30 seconds at most. Keep that in mind."
90002090-0306 = "Yes, that's fine."
90002090-0309 = "..."
90002090-0310 = "..."
90002090-0311 = "..."
90002090-0312 = "Kei...?"
90002090-0313 = "You..."
90002090-0314 = "Yes?"
90002090-0315 = "Are you sane?"
90002090-0316 = "Y-Yes... I think this is fairly normal..."
90002090-0317 = "Normal? This is?"
90002090-0318 = "...No, one can never be too prepared."
90002090-0319 = "Even so, to think that..."
90002090-0320 = "Is it... strange?"
90002090-0321 = "In any other situation, I might have thought so."
90002090-0322 = "But right now..."
90002090-0323 = "..."
90002090-0324 = "I'm glad you're here."
90002090-0325 = "I-I see...?"
90002090-0326 = "Now Yuzu's suit makes sense as well."
90002090-0327 = "Yes."
90002090-0328 = "And about that second stage we discussed..."
90002090-0329 = "I don't think it's impossible. #nThere's a precedent, so it might be surprisingly easy."
90002090-0330 = "Though as you said, it would be best if we didn't have to use it."
90002090-0331 = "Yes. A trump card is most powerful while it remains a trump card."
90002090-0332 = "[s] \"Hmm? Trump card?\""
90002090-0333 = "Sensei!?"
90002090-0334 = "Um, this is, well...!"
90002090-0335 = "..."
90002090-0336 = "We were discussing which menu item would be the 'trump card' for the after-party."
90002090-0337 = "[s] \"An after-party?\""
90002090-0338 = "Yes."
90002090-0339 = "We are going to win, aren't we?"
90002090-0340 = "[s] \"I see, so that's what you meant.\""
90002090-0341 = "Yes."
90002090-0342 = "Right, Rio?"
90002090-0343 = "..."
90002090-0344 = "Yes, that's right."
90002090-0345 = "Sensei, what are you doing here? Oh, Rio-senpai and Kei too!"
90002090-0346 = "What? Talking about the after-party? That sounds great!"
90002090-0347 = "Aris is happy with anything as long as she's with Sensei!"
90002090-0348 = "[s9] \"Yeah! Me too!\"\n[s10] \"To make that happen... let's all come back safely.\""
90002090-0351 = "...Yes."
90002090-0352 = "Now... to ensure victory, I will explain the strategy in more detail."
90002090-0353 = "Which is?"
90002090-0354 = "There is no specific order for defeating the Prophets or occupying the areas. #nI believe we can proceed according to Sensei's command."
90002090-0355 = "However, the 'Binah' area must be occupied first."
90002090-0356 = "[s] \"Why is that?\""
90002090-0357 = "I have just located Binah."
90002090-0358 = "[s] \"As expected of Kei-chan!\""
90002090-0359 = "Who are you calling Kei-chan!?"
90002090-0360 = "*Ahem*... Also, there is another reason."
90002090-0361 = "As I mentioned before, the entire Steel Continent is covered by a network."
90002090-0362 = "A firewall has been installed in Binah's area to protect it."
90002090-0363 = "In order for us to proceed, we must disable that firewall, whether physically or electronically."
90002090-0364 = "If we succeed in breaking through, it should be easier to locate the remaining Prophets."
90002090-0365 = "Conversely, if we leave the firewall alone... to use Aris's words—"
90002090-0366 = "No matter how much we level up, we won't be able to issue commands to the Steel Continent."
90002090-0367 = "[s] \"I... see?\""
90002090-0368 = "So, for the mission's success—"
90002090-0369 = "Yes. We must secure Binah's information core as quickly as possible."
90002090-0370 = "[s] \"Then it's settled.\""
90002090-0371 = "The first target is Decagrammaton's third Prophet."
90002090-0372 = "The one who calls itself 'The Understanding Observer who keenly feels the difference'—"
90002090-0374 = "Binah."
90002090-0376 = "Next Time;000, 00, 0"